// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

import { ValueSerializer } from "../src/value-serializer.js";

describe("ValueSerializer", () => {
  describe("path location", () => {
    test("null returns empty string", () => {
      expect(ValueSerializer.serialize(null, "path", "string")).toBe("");
    });

    test("undefined returns empty string", () => {
      expect(ValueSerializer.serialize(undefined, "path", "string")).toBe("");
    });

    test("string returns URL-encoded value", () => {
      expect(ValueSerializer.serialize("hello", "path", "string")).toBe(
        "hello",
      );
    });

    test("string with spaces is URL-encoded", () => {
      expect(ValueSerializer.serialize("hello world", "path", "string")).toBe(
        "hello%20world",
      );
    });

    test("string with slash is URL-encoded", () => {
      expect(ValueSerializer.serialize("a/b", "path", "string")).toBe("a%2Fb");
    });

    test("integer returns string", () => {
      expect(ValueSerializer.serialize(42, "path", "integer")).toBe("42");
    });

    test('boolean true returns "true"', () => {
      expect(ValueSerializer.serialize(true, "path", "boolean")).toBe("true");
    });

    test('boolean false returns "false"', () => {
      expect(ValueSerializer.serialize(false, "path", "boolean")).toBe("false");
    });
  });

  describe("query location", () => {
    test("null returns undefined", () => {
      expect(
        ValueSerializer.serialize(null, "query", "string"),
      ).toBeUndefined();
    });

    test("undefined returns undefined", () => {
      expect(
        ValueSerializer.serialize(undefined, "query", "string"),
      ).toBeUndefined();
    });

    test("string returns as-is", () => {
      expect(ValueSerializer.serialize("hello", "query", "string")).toBe(
        "hello",
      );
    });

    test("integer returns string", () => {
      expect(ValueSerializer.serialize(42, "query", "integer")).toBe("42");
    });

    test('boolean true returns "true"', () => {
      expect(ValueSerializer.serialize(true, "query", "boolean")).toBe("true");
    });

    test('boolean false returns "false"', () => {
      expect(ValueSerializer.serialize(false, "query", "boolean")).toBe(
        "false",
      );
    });

    test("array joins with comma by default", () => {
      expect(ValueSerializer.serialize(["a", "b", "c"], "query", "array")).toBe(
        "a,b,c",
      );
    });

    test("array joins with comma for csv", () => {
      expect(
        ValueSerializer.serialize(["a", "b", "c"], "query", "array", "csv"),
      ).toBe("a,b,c");
    });

    test("array joins with space for ssv", () => {
      expect(
        ValueSerializer.serialize(["a", "b", "c"], "query", "array", "ssv"),
      ).toBe("a b c");
    });

    test("array joins with tab for tsv", () => {
      expect(
        ValueSerializer.serialize(["a", "b", "c"], "query", "array", "tsv"),
      ).toBe("a\tb\tc");
    });

    test("array joins with pipe for pipes", () => {
      expect(
        ValueSerializer.serialize(["a", "b", "c"], "query", "array", "pipes"),
      ).toBe("a|b|c");
    });

    test("array returns list for multi", () => {
      expect(
        ValueSerializer.serialize(["a", "b", "c"], "query", "array", "multi"),
      ).toEqual(["a", "b", "c"]);
    });

    test("empty array returns empty string for csv", () => {
      expect(ValueSerializer.serialize([], "query", "array")).toBe("");
    });

    test("empty array returns empty list for multi", () => {
      expect(ValueSerializer.serialize([], "query", "array", "multi")).toEqual(
        [],
      );
    });

    test("single-element array returns single value", () => {
      expect(ValueSerializer.serialize(["a"], "query", "array")).toBe("a");
    });

    test("array of integers stringifies elements", () => {
      expect(ValueSerializer.serialize([1, 2, 3], "query", "array")).toBe(
        "1,2,3",
      );
    });

    test("array of booleans stringifies elements", () => {
      expect(ValueSerializer.serialize([true, false], "query", "array")).toBe(
        "true,false",
      );
    });
  });

  describe("header location", () => {
    test("null returns empty string", () => {
      expect(ValueSerializer.serialize(null, "header", "string")).toBe("");
    });

    test("string returns as-is", () => {
      expect(ValueSerializer.serialize("hello", "header", "string")).toBe(
        "hello",
      );
    });

    test("integer returns string", () => {
      expect(ValueSerializer.serialize(42, "header", "integer")).toBe("42");
    });

    test('boolean true returns "true"', () => {
      expect(ValueSerializer.serialize(true, "header", "boolean")).toBe("true");
    });

    test("array joins with comma", () => {
      expect(
        ValueSerializer.serialize(["a", "b", "c"], "header", "array"),
      ).toBe("a,b,c");
    });

    test("empty array joins to empty string", () => {
      expect(ValueSerializer.serialize([], "header", "array")).toBe("");
    });

    test("array of integers stringifies and joins", () => {
      expect(ValueSerializer.serialize([1, 2, 3], "header", "array")).toBe(
        "1,2,3",
      );
    });
  });

  describe("serializeStyled - matrix style", () => {
    test("scalar returns semicolon-prefixed name=value", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          "blue",
          "path",
          "string",
          null,
          "matrix",
          true,
        ),
      ).toBe(";color=blue");
    });

    test("array with explode false joins with comma", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          ["blue", "black"],
          "path",
          "array",
          null,
          "matrix",
          false,
        ),
      ).toBe(";color=blue,black");
    });

    test("array with explode true repeats name", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          ["blue", "black"],
          "path",
          "array",
          null,
          "matrix",
          true,
        ),
      ).toBe(";color=blue;color=black");
    });

    test("null returns empty string", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          null,
          "path",
          "string",
          null,
          "matrix",
          true,
        ),
      ).toBe("");
    });
  });

  describe("serializeStyled - label style", () => {
    test("scalar returns dot-prefixed value", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          "blue",
          "path",
          "string",
          null,
          "label",
          true,
        ),
      ).toBe(".blue");
    });

    test("array with explode false joins with dot then comma", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          ["blue", "black"],
          "path",
          "array",
          null,
          "label",
          false,
        ),
      ).toBe(".blue,black");
    });

    test("array with explode true joins with dot separator", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          ["blue", "black"],
          "path",
          "array",
          null,
          "label",
          true,
        ),
      ).toBe(".blue.black");
    });

    test("null returns empty string", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          null,
          "path",
          "string",
          null,
          "label",
          true,
        ),
      ).toBe("");
    });
  });

  describe("serializeStyled - spaceDelimited style", () => {
    test("array joins with space", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          ["blue", "black"],
          "query",
          "array",
          null,
          "spaceDelimited",
          false,
        ),
      ).toBe("blue black");
    });

    test("scalar returns stringified value", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          "blue",
          "query",
          "string",
          null,
          "spaceDelimited",
          false,
        ),
      ).toBe("blue");
    });
  });

  describe("serializeStyled - pipeDelimited style", () => {
    test("array joins with pipe", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          ["blue", "black"],
          "query",
          "array",
          null,
          "pipeDelimited",
          false,
        ),
      ).toBe("blue|black");
    });

    test("scalar returns stringified value", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          "blue",
          "query",
          "string",
          null,
          "pipeDelimited",
          false,
        ),
      ).toBe("blue");
    });
  });

  describe("serializeStyled - form style with explode", () => {
    test("array with explode false joins with comma", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          ["blue", "black"],
          "query",
          "array",
          null,
          "form",
          false,
        ),
      ).toBe("blue,black");
    });

    test("array with explode true returns list", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          ["blue", "black"],
          "query",
          "array",
          null,
          "form",
          true,
        ),
      ).toEqual(["blue", "black"]);
    });

    test("scalar with explode true returns string not list", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          "blue",
          "query",
          "string",
          null,
          "form",
          true,
        ),
      ).toBe("blue");
    });

    test("single-element array with explode true returns list", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          ["blue"],
          "query",
          "array",
          null,
          "form",
          true,
        ),
      ).toEqual(["blue"]);
    });

    test("null returns undefined for query location", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          null,
          "query",
          "string",
          null,
          "form",
          true,
        ),
      ).toBeUndefined();
    });
  });

  describe("serializeStyled - simple style backward compatibility", () => {
    test("scalar returns stringified value", () => {
      expect(
        ValueSerializer.serializeStyled(
          "id",
          "5",
          "path",
          "string",
          null,
          "simple",
          false,
        ),
      ).toBe("5");
    });

    test("array joins with comma", () => {
      expect(
        ValueSerializer.serializeStyled(
          "id",
          ["3", "4", "5"],
          "path",
          "array",
          null,
          "simple",
          false,
        ),
      ).toBe("3,4,5");
    });

    test("null returns empty string", () => {
      expect(
        ValueSerializer.serializeStyled(
          "id",
          null,
          "path",
          "string",
          null,
          "simple",
          true,
        ),
      ).toBe("");
    });

    test("scalar URL-encodes path value", () => {
      expect(
        ValueSerializer.serializeStyled(
          "id",
          "hello world",
          "path",
          "string",
          null,
          "simple",
          false,
        ),
      ).toBe("hello%20world");
    });

    test("path value is encoded exactly once (no double-encoding)", () => {
      // path-double-encoding: serializeStyled already percent-encodes the
      // path segment, so the API template must NOT wrap it again. A space
      // must become %20 (never %2520) and a slash %2F (never %252F).
      const space = ValueSerializer.serializeStyled(
        "id",
        "a b",
        "path",
        "string",
        null,
        "simple",
        false,
      );
      expect(space).toBe("a%20b");
      expect(space).not.toContain("%2520");
      const slash = ValueSerializer.serializeStyled(
        "id",
        "a/b",
        "path",
        "string",
        null,
        "simple",
        false,
      );
      expect(slash).toBe("a%2Fb");
      expect(slash).not.toContain("%252F");
    });
  });

  describe("serializeStyled - null style falls back to location default", () => {
    test("path with null style behaves like simple", () => {
      expect(
        ValueSerializer.serializeStyled(
          "id",
          "5",
          "path",
          "string",
          null,
          null,
          false,
        ),
      ).toBe("5");
    });

    test("empty style falls back to location default", () => {
      expect(
        ValueSerializer.serializeStyled(
          "id",
          "5",
          "path",
          "string",
          null,
          "",
          false,
        ),
      ).toBe("5");
    });
  });

  describe("cookie location", () => {
    test("string returns as-is", () => {
      expect(
        ValueSerializer.serialize("hello", "cookie", "string", undefined),
      ).toBe("hello");
    });

    test("null returns empty string", () => {
      expect(
        ValueSerializer.serialize(null, "cookie", "string", undefined),
      ).toBe("");
    });
  });

  describe("serializeDeepObject", () => {
    test("basic map returns bracketed keys", () => {
      const result = ValueSerializer.serializeDeepObject("filter", {
        color: "blue",
        size: "large",
      });
      expect(result["filter[color]"]).toBe("blue");
      expect(result["filter[size]"]).toBe("large");
    });

    test("null returns empty object", () => {
      const result = ValueSerializer.serializeDeepObject("filter", null);
      expect(result).toEqual({});
    });
  });

  describe("form location", () => {
    test("null returns empty string", () => {
      expect(ValueSerializer.serialize(null, "form", "string")).toBe("");
    });

    test("string returns as-is", () => {
      expect(ValueSerializer.serialize("hello", "form", "string")).toBe(
        "hello",
      );
    });

    test("integer returns string", () => {
      expect(ValueSerializer.serialize(42, "form", "integer")).toBe("42");
    });

    test('boolean true returns "true"', () => {
      expect(ValueSerializer.serialize(true, "form", "boolean")).toBe("true");
    });

    test('boolean false returns "false"', () => {
      expect(ValueSerializer.serialize(false, "form", "boolean")).toBe("false");
    });
  });

  // Cross-language parity tests for path-segment percent-encoding.
  // Every SDK must produce identical encoded strings for these inputs.
  describe("path encoding parity", () => {
    test("ASCII-safe pass-through", () => {
      expect(ValueSerializer.serialize("abc123", "path", "string")).toBe(
        "abc123",
      );
    });

    test("space encoded as %20", () => {
      expect(ValueSerializer.serialize("a b", "path", "string")).toBe("a%20b");
    });

    test("slash encoded", () => {
      expect(ValueSerializer.serialize("a/b", "path", "string")).toBe("a%2Fb");
    });

    test("question mark encoded", () => {
      expect(ValueSerializer.serialize("a?b", "path", "string")).toBe("a%3Fb");
    });

    test("hash encoded", () => {
      expect(ValueSerializer.serialize("a#b", "path", "string")).toBe("a%23b");
    });

    test("comma preserved (sub-delimiter)", () => {
      expect(ValueSerializer.serialize("a,b", "path", "string")).toBe("a,b");
    });

    test("colon preserved (sub-delimiter)", () => {
      expect(ValueSerializer.serialize("a:b", "path", "string")).toBe("a:b");
    });

    test("plus preserved (sub-delimiter)", () => {
      expect(ValueSerializer.serialize("a+b", "path", "string")).toBe("a+b");
    });

    test("unicode encoded as UTF-8 percent", () => {
      expect(ValueSerializer.serialize("日本", "path", "string")).toBe(
        "%E6%97%A5%E6%9C%AC",
      );
    });

    test("empty string preserved", () => {
      expect(ValueSerializer.serialize("", "path", "string")).toBe("");
    });

    test("null returns empty string in path location", () => {
      expect(ValueSerializer.serialize(null, "path", "string")).toBe("");
    });

    test("simple style encodes value", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          "a b",
          "path",
          "string",
          null,
          "simple",
          false,
        ),
      ).toBe("a%20b");
    });

    test("simple style array encodes each item", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          ["a b", "c?d"],
          "path",
          "array",
          null,
          "simple",
          false,
        ),
      ).toBe("a%20b,c%3Fd");
    });

    test("path_array_item_with_reserved_char_is_percent_encoded", () => {
      // Gap W1 regression: every per-item path value in a styled array
      // must be percent-encoded BEFORE being joined with the structural
      // separator. Otherwise '/', '?', '#', space leak into the URL.
      const items = ["a/b", "c"];
      expect(
        ValueSerializer.serializeStyled(
          "name",
          items,
          "path",
          "array",
          null,
          "simple",
          false,
        ),
      ).toBe("a%2Fb,c");
      expect(
        ValueSerializer.serializeStyled(
          "name",
          items,
          "path",
          "array",
          null,
          "label",
          true,
        ),
      ).toBe(".a%2Fb.c");
      expect(
        ValueSerializer.serializeStyled(
          "name",
          items,
          "path",
          "array",
          null,
          "matrix",
          false,
        ),
      ).toBe(";name=a%2Fb,c");
    });

    test("matrix style encodes value", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          "a b",
          "path",
          "string",
          null,
          "matrix",
          false,
        ),
      ).toBe(";color=a%20b");
    });

    test("label style encodes value", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          "a b",
          "path",
          "string",
          null,
          "label",
          false,
        ),
      ).toBe(".a%20b");
    });

    test("query location is not path-encoded", () => {
      expect(
        ValueSerializer.serializeStyled(
          "color",
          "a b",
          "query",
          "string",
          null,
          "form",
          false,
        ),
      ).toBe("a b");
    });

    test("empty string path param throws", () => {
      // Gap W — empty-string path values silently produce malformed
      // URLs like `/pet//details`; reject at serialization time so
      // callers see the real error rather than a downstream 404.
      expect(() =>
        ValueSerializer.serializeStyled(
          "id",
          "",
          "path",
          "string",
          null,
          "simple",
          false,
        ),
      ).toThrow();
    });
  });

  // N3/W3 parity: `format: date` path parameters must emit a date-only
  // string (YYYY-MM-DD), not a full ISO datetime. Node has only `Date`,
  // so the codegen routes such params through `stringifyDate` to strip
  // the time component before path-encoding.
  describe("format:date stringifyDate helper", () => {
    test("Date instance returns YYYY-MM-DD (UTC)", () => {
      const date = new Date(Date.UTC(2024, 0, 15, 14, 30, 45));
      expect(ValueSerializer.stringifyDate(date)).toBe("2024-01-15");
    });

    test("string passes through truncated to 10 chars", () => {
      expect(ValueSerializer.stringifyDate("2024-01-15")).toBe("2024-01-15");
      expect(ValueSerializer.stringifyDate("2024-01-15T14:30:45Z")).toBe(
        "2024-01-15",
      );
    });
  });
});
