// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

import type { ApiClient } from "../api-client.js";
import { ApiError } from "../api-error.js";
import type { ApiResult } from "../api-result.js";
import type { Authenticator } from "../auth/authenticator.js";
import { BaseApi } from "./base-api.js";
import { Configuration } from "../configuration.js";
import { ObjectSerializer } from "../object-serializer.js";
import { ValueSerializer } from "../value-serializer.js";
import type { DeepInput } from "../deep-input.js";
import {
  InternalPermissionServiceConnectError,
  InternalPermissionServiceCreateAdministratorRequest,
  InternalPermissionServiceCreateAdministratorResponse,
  InternalPermissionServiceDeleteAdministratorRequest,
  InternalPermissionServiceDeleteAdministratorResponse,
  InternalPermissionServiceListAdministratorsRequest,
  InternalPermissionServiceListAdministratorsResponse,
  InternalPermissionServiceUpdateAdministratorRequest,
  InternalPermissionServiceUpdateAdministratorResponse,
} from "../models/index.js";

/**
 * InternalPermissionServiceApi provides methods for the InternalPermissionService API group.
 */
export class InternalPermissionServiceApi extends BaseApi {
  constructor(
    apiClient?: ApiClient,
    config?: Configuration,
    authenticator?: Authenticator | null,
  ) {
    super(apiClient, config, authenticator);
  }

  /**
   * Create Administrator
   * CreateAdministrator grants an administrator role to a user for a specific resource.   Note that the roles are specific to the resource type.  This means that if you want to grant a user the administrator role for an organization and a project,  you need to create two administrator roles.   Required permissions depend on the resource type:    - \"iam.member.write\" for instance administrators    - \"org.member.write\" for organization administrators    - \"project.member.write\" for project administrators    - \"project.grant.member.write\" for project grant administrators
   * @param internalPermissionServiceCreateAdministratorRequest  (required)
   * @return InternalPermissionServiceCreateAdministratorResponse
   * @throws {ApiError} if fails to make API call
   */
  async createAdministrator(
    internalPermissionServiceCreateAdministratorRequest: DeepInput<InternalPermissionServiceCreateAdministratorRequest>,
  ): Promise<InternalPermissionServiceCreateAdministratorResponse> {
    const createAdministratorResult =
      await this.createAdministratorWithHttpInfo(
        internalPermissionServiceCreateAdministratorRequest,
      );
    /* convenience-empty-body-handling: a body-returning operation that
     * receives no decodable body (204 / empty / null) must surface a
     * typed ApiError, never a silently-cast `undefined`. */
    if (createAdministratorResult.data == null) {
      throw new ApiError(
        createAdministratorResult.statusCode,
        "Expected a response body for createAdministrator but received none",
        createAdministratorResult.headers,
        createAdministratorResult.rawBody,
        null,
      );
    }
    return createAdministratorResult.data as InternalPermissionServiceCreateAdministratorResponse;
  }

  /**
   * Create Administrator (with HTTP info)
   * @throws {ApiError} if fails to make API call
   */
  async createAdministratorWithHttpInfo(
    internalPermissionServiceCreateAdministratorRequest: DeepInput<InternalPermissionServiceCreateAdministratorRequest>,
  ): Promise<ApiResult<InternalPermissionServiceCreateAdministratorResponse>> {
    if (internalPermissionServiceCreateAdministratorRequest == null) {
      throw new Error(
        'Missing required parameter "internalPermissionServiceCreateAdministratorRequest" when calling createAdministrator',
      );
    }
    const path = `/zitadel.internal_permission.v2.InternalPermissionService/CreateAdministrator`;
    const queryParams: Record<string, unknown> = {};
    const headerParams: Record<string, string> = {};
    return await this.invokeApiForResult(
      "POST",
      path,
      queryParams,
      headerParams,
      internalPermissionServiceCreateAdministratorRequest,
      ["application/json"],
      "application/json",
      (json: unknown) =>
        ObjectSerializer.deserialize(
          json,
          InternalPermissionServiceCreateAdministratorResponse,
        )!,
      null,
    );
  }

  /**
   * Delete Administrator
   * DeleteAdministrator revokes an administrator role from a user.   In case the administrator role is not found, the request will return a successful response as  the desired state is already achieved.  You can check the deletion date in the response to verify if the administrator role was deleted during the request.   Required permissions depend on the resource type:    - \"iam.member.delete\" for instance administrators    - \"org.member.delete\" for organization administrators    - \"project.member.delete\" for project administrators    - \"project.grant.member.delete\" for project grant administrators
   * @param internalPermissionServiceDeleteAdministratorRequest  (required)
   * @return InternalPermissionServiceDeleteAdministratorResponse
   * @throws {ApiError} if fails to make API call
   */
  async deleteAdministrator(
    internalPermissionServiceDeleteAdministratorRequest: DeepInput<InternalPermissionServiceDeleteAdministratorRequest>,
  ): Promise<InternalPermissionServiceDeleteAdministratorResponse> {
    const deleteAdministratorResult =
      await this.deleteAdministratorWithHttpInfo(
        internalPermissionServiceDeleteAdministratorRequest,
      );
    /* convenience-empty-body-handling: a body-returning operation that
     * receives no decodable body (204 / empty / null) must surface a
     * typed ApiError, never a silently-cast `undefined`. */
    if (deleteAdministratorResult.data == null) {
      throw new ApiError(
        deleteAdministratorResult.statusCode,
        "Expected a response body for deleteAdministrator but received none",
        deleteAdministratorResult.headers,
        deleteAdministratorResult.rawBody,
        null,
      );
    }
    return deleteAdministratorResult.data as InternalPermissionServiceDeleteAdministratorResponse;
  }

  /**
   * Delete Administrator (with HTTP info)
   * @throws {ApiError} if fails to make API call
   */
  async deleteAdministratorWithHttpInfo(
    internalPermissionServiceDeleteAdministratorRequest: DeepInput<InternalPermissionServiceDeleteAdministratorRequest>,
  ): Promise<ApiResult<InternalPermissionServiceDeleteAdministratorResponse>> {
    if (internalPermissionServiceDeleteAdministratorRequest == null) {
      throw new Error(
        'Missing required parameter "internalPermissionServiceDeleteAdministratorRequest" when calling deleteAdministrator',
      );
    }
    const path = `/zitadel.internal_permission.v2.InternalPermissionService/DeleteAdministrator`;
    const queryParams: Record<string, unknown> = {};
    const headerParams: Record<string, string> = {};
    return await this.invokeApiForResult(
      "POST",
      path,
      queryParams,
      headerParams,
      internalPermissionServiceDeleteAdministratorRequest,
      ["application/json"],
      "application/json",
      (json: unknown) =>
        ObjectSerializer.deserialize(
          json,
          InternalPermissionServiceDeleteAdministratorResponse,
        )!,
      null,
    );
  }

  /**
   * List Administrators
   * ListAdministrators returns all administrators and their roles matching the request and the caller's permissions to retrieve.   Required permissions depend on the resource type:    - \"iam.member.read\" for instance administrators    - \"org.member.read\" for organization administrators    - \"project.member.read\" for project administrators    - \"project.grant.member.read\" for project grant administrators    - no permissions required for listing own administrator roles
   * @param internalPermissionServiceListAdministratorsRequest  (required)
   * @return InternalPermissionServiceListAdministratorsResponse
   * @throws {ApiError} if fails to make API call
   */
  async listAdministrators(
    internalPermissionServiceListAdministratorsRequest: DeepInput<InternalPermissionServiceListAdministratorsRequest>,
  ): Promise<InternalPermissionServiceListAdministratorsResponse> {
    const listAdministratorsResult = await this.listAdministratorsWithHttpInfo(
      internalPermissionServiceListAdministratorsRequest,
    );
    /* convenience-empty-body-handling: a body-returning operation that
     * receives no decodable body (204 / empty / null) must surface a
     * typed ApiError, never a silently-cast `undefined`. */
    if (listAdministratorsResult.data == null) {
      throw new ApiError(
        listAdministratorsResult.statusCode,
        "Expected a response body for listAdministrators but received none",
        listAdministratorsResult.headers,
        listAdministratorsResult.rawBody,
        null,
      );
    }
    return listAdministratorsResult.data as InternalPermissionServiceListAdministratorsResponse;
  }

  /**
   * List Administrators (with HTTP info)
   * @throws {ApiError} if fails to make API call
   */
  async listAdministratorsWithHttpInfo(
    internalPermissionServiceListAdministratorsRequest: DeepInput<InternalPermissionServiceListAdministratorsRequest>,
  ): Promise<ApiResult<InternalPermissionServiceListAdministratorsResponse>> {
    if (internalPermissionServiceListAdministratorsRequest == null) {
      throw new Error(
        'Missing required parameter "internalPermissionServiceListAdministratorsRequest" when calling listAdministrators',
      );
    }
    const path = `/zitadel.internal_permission.v2.InternalPermissionService/ListAdministrators`;
    const queryParams: Record<string, unknown> = {};
    const headerParams: Record<string, string> = {};
    return await this.invokeApiForResult(
      "POST",
      path,
      queryParams,
      headerParams,
      internalPermissionServiceListAdministratorsRequest,
      ["application/json"],
      "application/json",
      (json: unknown) =>
        ObjectSerializer.deserialize(
          json,
          InternalPermissionServiceListAdministratorsResponse,
        )!,
      null,
    );
  }

  /**
   * Update Administrator
   * UpdateAdministrator updates the specific administrator role.   Note that any role previously granted to the user and not present in the request will be revoked.   Required permissions depend on the resource type:    - \"iam.member.write\" for instance administrators    - \"org.member.write\" for organization administrators    - \"project.member.write\" for project administrators    - \"project.grant.member.write\" for project grant administrators
   * @param internalPermissionServiceUpdateAdministratorRequest  (required)
   * @return InternalPermissionServiceUpdateAdministratorResponse
   * @throws {ApiError} if fails to make API call
   */
  async updateAdministrator(
    internalPermissionServiceUpdateAdministratorRequest: DeepInput<InternalPermissionServiceUpdateAdministratorRequest>,
  ): Promise<InternalPermissionServiceUpdateAdministratorResponse> {
    const updateAdministratorResult =
      await this.updateAdministratorWithHttpInfo(
        internalPermissionServiceUpdateAdministratorRequest,
      );
    /* convenience-empty-body-handling: a body-returning operation that
     * receives no decodable body (204 / empty / null) must surface a
     * typed ApiError, never a silently-cast `undefined`. */
    if (updateAdministratorResult.data == null) {
      throw new ApiError(
        updateAdministratorResult.statusCode,
        "Expected a response body for updateAdministrator but received none",
        updateAdministratorResult.headers,
        updateAdministratorResult.rawBody,
        null,
      );
    }
    return updateAdministratorResult.data as InternalPermissionServiceUpdateAdministratorResponse;
  }

  /**
   * Update Administrator (with HTTP info)
   * @throws {ApiError} if fails to make API call
   */
  async updateAdministratorWithHttpInfo(
    internalPermissionServiceUpdateAdministratorRequest: DeepInput<InternalPermissionServiceUpdateAdministratorRequest>,
  ): Promise<ApiResult<InternalPermissionServiceUpdateAdministratorResponse>> {
    if (internalPermissionServiceUpdateAdministratorRequest == null) {
      throw new Error(
        'Missing required parameter "internalPermissionServiceUpdateAdministratorRequest" when calling updateAdministrator',
      );
    }
    const path = `/zitadel.internal_permission.v2.InternalPermissionService/UpdateAdministrator`;
    const queryParams: Record<string, unknown> = {};
    const headerParams: Record<string, string> = {};
    return await this.invokeApiForResult(
      "POST",
      path,
      queryParams,
      headerParams,
      internalPermissionServiceUpdateAdministratorRequest,
      ["application/json"],
      "application/json",
      (json: unknown) =>
        ObjectSerializer.deserialize(
          json,
          InternalPermissionServiceUpdateAdministratorResponse,
        )!,
      null,
    );
  }
}
