/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  BetaUserServiceAddHumanUserRequest,
  BetaUserServiceAddHumanUserResponse,
  BetaUserServiceAddIDPLinkRequest,
  BetaUserServiceAddIDPLinkResponse,
  BetaUserServiceAddOTPEmailRequest,
  BetaUserServiceAddOTPEmailResponse,
  BetaUserServiceAddOTPSMSRequest,
  BetaUserServiceAddOTPSMSResponse,
  BetaUserServiceConnectError,
  BetaUserServiceCreatePasskeyRegistrationLinkRequest,
  BetaUserServiceCreatePasskeyRegistrationLinkResponse,
  BetaUserServiceDeactivateUserRequest,
  BetaUserServiceDeactivateUserResponse,
  BetaUserServiceDeleteUserRequest,
  BetaUserServiceDeleteUserResponse,
  BetaUserServiceGetUserByIDRequest,
  BetaUserServiceGetUserByIDResponse,
  BetaUserServiceListAuthenticationMethodTypesRequest,
  BetaUserServiceListAuthenticationMethodTypesResponse,
  BetaUserServiceListUsersRequest,
  BetaUserServiceListUsersResponse,
  BetaUserServiceLockUserRequest,
  BetaUserServiceLockUserResponse,
  BetaUserServicePasswordResetRequest,
  BetaUserServicePasswordResetResponse,
  BetaUserServiceReactivateUserRequest,
  BetaUserServiceReactivateUserResponse,
  BetaUserServiceRegisterPasskeyRequest,
  BetaUserServiceRegisterPasskeyResponse,
  BetaUserServiceRegisterTOTPRequest,
  BetaUserServiceRegisterTOTPResponse,
  BetaUserServiceRegisterU2FRequest,
  BetaUserServiceRegisterU2FResponse,
  BetaUserServiceRemoveOTPEmailRequest,
  BetaUserServiceRemoveOTPEmailResponse,
  BetaUserServiceRemoveOTPSMSRequest,
  BetaUserServiceRemoveOTPSMSResponse,
  BetaUserServiceRemovePhoneRequest,
  BetaUserServiceRemovePhoneResponse,
  BetaUserServiceRemoveTOTPRequest,
  BetaUserServiceRemoveTOTPResponse,
  BetaUserServiceResendEmailCodeRequest,
  BetaUserServiceResendEmailCodeResponse,
  BetaUserServiceResendPhoneCodeRequest,
  BetaUserServiceResendPhoneCodeResponse,
  BetaUserServiceRetrieveIdentityProviderIntentRequest,
  BetaUserServiceRetrieveIdentityProviderIntentResponse,
  BetaUserServiceSetEmailRequest,
  BetaUserServiceSetEmailResponse,
  BetaUserServiceSetPasswordRequest,
  BetaUserServiceSetPasswordResponse,
  BetaUserServiceSetPhoneRequest,
  BetaUserServiceSetPhoneResponse,
  BetaUserServiceStartIdentityProviderIntentRequest,
  BetaUserServiceStartIdentityProviderIntentResponse,
  BetaUserServiceUnlockUserRequest,
  BetaUserServiceUnlockUserResponse,
  BetaUserServiceUpdateHumanUserRequest,
  BetaUserServiceUpdateHumanUserResponse,
  BetaUserServiceVerifyEmailRequest,
  BetaUserServiceVerifyEmailResponse,
  BetaUserServiceVerifyPasskeyRegistrationRequest,
  BetaUserServiceVerifyPasskeyRegistrationResponse,
  BetaUserServiceVerifyPhoneRequest,
  BetaUserServiceVerifyPhoneResponse,
  BetaUserServiceVerifyTOTPRegistrationRequest,
  BetaUserServiceVerifyTOTPRegistrationResponse,
  BetaUserServiceVerifyU2FRegistrationRequest,
  BetaUserServiceVerifyU2FRegistrationResponse,
  NoOp200Response9,
} from '../models/index.js';
import {
    BetaUserServiceAddHumanUserRequestFromJSON,
    BetaUserServiceAddHumanUserRequestToJSON,
    BetaUserServiceAddHumanUserResponseFromJSON,
    BetaUserServiceAddHumanUserResponseToJSON,
    BetaUserServiceAddIDPLinkRequestFromJSON,
    BetaUserServiceAddIDPLinkRequestToJSON,
    BetaUserServiceAddIDPLinkResponseFromJSON,
    BetaUserServiceAddIDPLinkResponseToJSON,
    BetaUserServiceAddOTPEmailRequestFromJSON,
    BetaUserServiceAddOTPEmailRequestToJSON,
    BetaUserServiceAddOTPEmailResponseFromJSON,
    BetaUserServiceAddOTPEmailResponseToJSON,
    BetaUserServiceAddOTPSMSRequestFromJSON,
    BetaUserServiceAddOTPSMSRequestToJSON,
    BetaUserServiceAddOTPSMSResponseFromJSON,
    BetaUserServiceAddOTPSMSResponseToJSON,
    BetaUserServiceConnectErrorFromJSON,
    BetaUserServiceConnectErrorToJSON,
    BetaUserServiceCreatePasskeyRegistrationLinkRequestFromJSON,
    BetaUserServiceCreatePasskeyRegistrationLinkRequestToJSON,
    BetaUserServiceCreatePasskeyRegistrationLinkResponseFromJSON,
    BetaUserServiceCreatePasskeyRegistrationLinkResponseToJSON,
    BetaUserServiceDeactivateUserRequestFromJSON,
    BetaUserServiceDeactivateUserRequestToJSON,
    BetaUserServiceDeactivateUserResponseFromJSON,
    BetaUserServiceDeactivateUserResponseToJSON,
    BetaUserServiceDeleteUserRequestFromJSON,
    BetaUserServiceDeleteUserRequestToJSON,
    BetaUserServiceDeleteUserResponseFromJSON,
    BetaUserServiceDeleteUserResponseToJSON,
    BetaUserServiceGetUserByIDRequestFromJSON,
    BetaUserServiceGetUserByIDRequestToJSON,
    BetaUserServiceGetUserByIDResponseFromJSON,
    BetaUserServiceGetUserByIDResponseToJSON,
    BetaUserServiceListAuthenticationMethodTypesRequestFromJSON,
    BetaUserServiceListAuthenticationMethodTypesRequestToJSON,
    BetaUserServiceListAuthenticationMethodTypesResponseFromJSON,
    BetaUserServiceListAuthenticationMethodTypesResponseToJSON,
    BetaUserServiceListUsersRequestFromJSON,
    BetaUserServiceListUsersRequestToJSON,
    BetaUserServiceListUsersResponseFromJSON,
    BetaUserServiceListUsersResponseToJSON,
    BetaUserServiceLockUserRequestFromJSON,
    BetaUserServiceLockUserRequestToJSON,
    BetaUserServiceLockUserResponseFromJSON,
    BetaUserServiceLockUserResponseToJSON,
    BetaUserServicePasswordResetRequestFromJSON,
    BetaUserServicePasswordResetRequestToJSON,
    BetaUserServicePasswordResetResponseFromJSON,
    BetaUserServicePasswordResetResponseToJSON,
    BetaUserServiceReactivateUserRequestFromJSON,
    BetaUserServiceReactivateUserRequestToJSON,
    BetaUserServiceReactivateUserResponseFromJSON,
    BetaUserServiceReactivateUserResponseToJSON,
    BetaUserServiceRegisterPasskeyRequestFromJSON,
    BetaUserServiceRegisterPasskeyRequestToJSON,
    BetaUserServiceRegisterPasskeyResponseFromJSON,
    BetaUserServiceRegisterPasskeyResponseToJSON,
    BetaUserServiceRegisterTOTPRequestFromJSON,
    BetaUserServiceRegisterTOTPRequestToJSON,
    BetaUserServiceRegisterTOTPResponseFromJSON,
    BetaUserServiceRegisterTOTPResponseToJSON,
    BetaUserServiceRegisterU2FRequestFromJSON,
    BetaUserServiceRegisterU2FRequestToJSON,
    BetaUserServiceRegisterU2FResponseFromJSON,
    BetaUserServiceRegisterU2FResponseToJSON,
    BetaUserServiceRemoveOTPEmailRequestFromJSON,
    BetaUserServiceRemoveOTPEmailRequestToJSON,
    BetaUserServiceRemoveOTPEmailResponseFromJSON,
    BetaUserServiceRemoveOTPEmailResponseToJSON,
    BetaUserServiceRemoveOTPSMSRequestFromJSON,
    BetaUserServiceRemoveOTPSMSRequestToJSON,
    BetaUserServiceRemoveOTPSMSResponseFromJSON,
    BetaUserServiceRemoveOTPSMSResponseToJSON,
    BetaUserServiceRemovePhoneRequestFromJSON,
    BetaUserServiceRemovePhoneRequestToJSON,
    BetaUserServiceRemovePhoneResponseFromJSON,
    BetaUserServiceRemovePhoneResponseToJSON,
    BetaUserServiceRemoveTOTPRequestFromJSON,
    BetaUserServiceRemoveTOTPRequestToJSON,
    BetaUserServiceRemoveTOTPResponseFromJSON,
    BetaUserServiceRemoveTOTPResponseToJSON,
    BetaUserServiceResendEmailCodeRequestFromJSON,
    BetaUserServiceResendEmailCodeRequestToJSON,
    BetaUserServiceResendEmailCodeResponseFromJSON,
    BetaUserServiceResendEmailCodeResponseToJSON,
    BetaUserServiceResendPhoneCodeRequestFromJSON,
    BetaUserServiceResendPhoneCodeRequestToJSON,
    BetaUserServiceResendPhoneCodeResponseFromJSON,
    BetaUserServiceResendPhoneCodeResponseToJSON,
    BetaUserServiceRetrieveIdentityProviderIntentRequestFromJSON,
    BetaUserServiceRetrieveIdentityProviderIntentRequestToJSON,
    BetaUserServiceRetrieveIdentityProviderIntentResponseFromJSON,
    BetaUserServiceRetrieveIdentityProviderIntentResponseToJSON,
    BetaUserServiceSetEmailRequestFromJSON,
    BetaUserServiceSetEmailRequestToJSON,
    BetaUserServiceSetEmailResponseFromJSON,
    BetaUserServiceSetEmailResponseToJSON,
    BetaUserServiceSetPasswordRequestFromJSON,
    BetaUserServiceSetPasswordRequestToJSON,
    BetaUserServiceSetPasswordResponseFromJSON,
    BetaUserServiceSetPasswordResponseToJSON,
    BetaUserServiceSetPhoneRequestFromJSON,
    BetaUserServiceSetPhoneRequestToJSON,
    BetaUserServiceSetPhoneResponseFromJSON,
    BetaUserServiceSetPhoneResponseToJSON,
    BetaUserServiceStartIdentityProviderIntentRequestFromJSON,
    BetaUserServiceStartIdentityProviderIntentRequestToJSON,
    BetaUserServiceStartIdentityProviderIntentResponseFromJSON,
    BetaUserServiceStartIdentityProviderIntentResponseToJSON,
    BetaUserServiceUnlockUserRequestFromJSON,
    BetaUserServiceUnlockUserRequestToJSON,
    BetaUserServiceUnlockUserResponseFromJSON,
    BetaUserServiceUnlockUserResponseToJSON,
    BetaUserServiceUpdateHumanUserRequestFromJSON,
    BetaUserServiceUpdateHumanUserRequestToJSON,
    BetaUserServiceUpdateHumanUserResponseFromJSON,
    BetaUserServiceUpdateHumanUserResponseToJSON,
    BetaUserServiceVerifyEmailRequestFromJSON,
    BetaUserServiceVerifyEmailRequestToJSON,
    BetaUserServiceVerifyEmailResponseFromJSON,
    BetaUserServiceVerifyEmailResponseToJSON,
    BetaUserServiceVerifyPasskeyRegistrationRequestFromJSON,
    BetaUserServiceVerifyPasskeyRegistrationRequestToJSON,
    BetaUserServiceVerifyPasskeyRegistrationResponseFromJSON,
    BetaUserServiceVerifyPasskeyRegistrationResponseToJSON,
    BetaUserServiceVerifyPhoneRequestFromJSON,
    BetaUserServiceVerifyPhoneRequestToJSON,
    BetaUserServiceVerifyPhoneResponseFromJSON,
    BetaUserServiceVerifyPhoneResponseToJSON,
    BetaUserServiceVerifyTOTPRegistrationRequestFromJSON,
    BetaUserServiceVerifyTOTPRegistrationRequestToJSON,
    BetaUserServiceVerifyTOTPRegistrationResponseFromJSON,
    BetaUserServiceVerifyTOTPRegistrationResponseToJSON,
    BetaUserServiceVerifyU2FRegistrationRequestFromJSON,
    BetaUserServiceVerifyU2FRegistrationRequestToJSON,
    BetaUserServiceVerifyU2FRegistrationResponseFromJSON,
    BetaUserServiceVerifyU2FRegistrationResponseToJSON,
    NoOp200Response9FromJSON,
    NoOp200Response9ToJSON,
} from '../models/index.js';

export interface AddHumanUserRequest {
    betaUserServiceAddHumanUserRequest: BetaUserServiceAddHumanUserRequest;
}

export interface AddIDPLinkRequest {
    betaUserServiceAddIDPLinkRequest: BetaUserServiceAddIDPLinkRequest;
}

export interface AddOTPEmailRequest {
    betaUserServiceAddOTPEmailRequest: BetaUserServiceAddOTPEmailRequest;
}

export interface AddOTPSMSRequest {
    betaUserServiceAddOTPSMSRequest: BetaUserServiceAddOTPSMSRequest;
}

export interface CreatePasskeyRegistrationLinkRequest {
    betaUserServiceCreatePasskeyRegistrationLinkRequest: BetaUserServiceCreatePasskeyRegistrationLinkRequest;
}

export interface DeactivateUserRequest {
    betaUserServiceDeactivateUserRequest: BetaUserServiceDeactivateUserRequest;
}

export interface DeleteUserRequest {
    betaUserServiceDeleteUserRequest: BetaUserServiceDeleteUserRequest;
}

export interface GetUserByIDRequest {
    betaUserServiceGetUserByIDRequest: BetaUserServiceGetUserByIDRequest;
}

export interface ListAuthenticationMethodTypesRequest {
    betaUserServiceListAuthenticationMethodTypesRequest: BetaUserServiceListAuthenticationMethodTypesRequest;
}

export interface ListUsersRequest {
    betaUserServiceListUsersRequest: BetaUserServiceListUsersRequest;
}

export interface LockUserRequest {
    betaUserServiceLockUserRequest: BetaUserServiceLockUserRequest;
}

export interface PasswordResetRequest {
    betaUserServicePasswordResetRequest: BetaUserServicePasswordResetRequest;
}

export interface ReactivateUserRequest {
    betaUserServiceReactivateUserRequest: BetaUserServiceReactivateUserRequest;
}

export interface RegisterPasskeyRequest {
    betaUserServiceRegisterPasskeyRequest: BetaUserServiceRegisterPasskeyRequest;
}

export interface RegisterTOTPRequest {
    betaUserServiceRegisterTOTPRequest: BetaUserServiceRegisterTOTPRequest;
}

export interface RegisterU2FRequest {
    betaUserServiceRegisterU2FRequest: BetaUserServiceRegisterU2FRequest;
}

export interface RemoveOTPEmailRequest {
    betaUserServiceRemoveOTPEmailRequest: BetaUserServiceRemoveOTPEmailRequest;
}

export interface RemoveOTPSMSRequest {
    betaUserServiceRemoveOTPSMSRequest: BetaUserServiceRemoveOTPSMSRequest;
}

export interface RemovePhoneRequest {
    betaUserServiceRemovePhoneRequest: BetaUserServiceRemovePhoneRequest;
}

export interface RemoveTOTPRequest {
    betaUserServiceRemoveTOTPRequest: BetaUserServiceRemoveTOTPRequest;
}

export interface ResendEmailCodeRequest {
    betaUserServiceResendEmailCodeRequest: BetaUserServiceResendEmailCodeRequest;
}

export interface ResendPhoneCodeRequest {
    betaUserServiceResendPhoneCodeRequest: BetaUserServiceResendPhoneCodeRequest;
}

export interface RetrieveIdentityProviderIntentRequest {
    betaUserServiceRetrieveIdentityProviderIntentRequest: BetaUserServiceRetrieveIdentityProviderIntentRequest;
}

export interface SetEmailRequest {
    betaUserServiceSetEmailRequest: BetaUserServiceSetEmailRequest;
}

export interface SetPasswordRequest {
    betaUserServiceSetPasswordRequest: BetaUserServiceSetPasswordRequest;
}

export interface SetPhoneRequest {
    betaUserServiceSetPhoneRequest: BetaUserServiceSetPhoneRequest;
}

export interface StartIdentityProviderIntentRequest {
    betaUserServiceStartIdentityProviderIntentRequest: BetaUserServiceStartIdentityProviderIntentRequest;
}

export interface UnlockUserRequest {
    betaUserServiceUnlockUserRequest: BetaUserServiceUnlockUserRequest;
}

export interface UpdateHumanUserRequest {
    betaUserServiceUpdateHumanUserRequest: BetaUserServiceUpdateHumanUserRequest;
}

export interface VerifyEmailRequest {
    betaUserServiceVerifyEmailRequest: BetaUserServiceVerifyEmailRequest;
}

export interface VerifyPasskeyRegistrationRequest {
    betaUserServiceVerifyPasskeyRegistrationRequest: BetaUserServiceVerifyPasskeyRegistrationRequest;
}

export interface VerifyPhoneRequest {
    betaUserServiceVerifyPhoneRequest: BetaUserServiceVerifyPhoneRequest;
}

export interface VerifyTOTPRegistrationRequest {
    betaUserServiceVerifyTOTPRegistrationRequest: BetaUserServiceVerifyTOTPRegistrationRequest;
}

export interface VerifyU2FRegistrationRequest {
    betaUserServiceVerifyU2FRegistrationRequest: BetaUserServiceVerifyU2FRegistrationRequest;
}

/**
 * 
 */
export class BetaUserServiceApi extends runtime.BaseAPI {

    /**
     * Create a new human user   Create/import a new user with the type human. The newly created user will get a verification email if either the email address is not marked as verified and you did not request the verification to be returned.   Deprecated: please move to the corresponding endpoint under user service v2 (GA)
     * AddHumanUser
     */
    async addHumanUserRaw(requestParameters: AddHumanUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceAddHumanUserResponse>> {
        if (requestParameters['betaUserServiceAddHumanUserRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceAddHumanUserRequest',
                'Required parameter "betaUserServiceAddHumanUserRequest" was null or undefined when calling addHumanUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/AddHumanUser`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceAddHumanUserRequestToJSON(requestParameters['betaUserServiceAddHumanUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceAddHumanUserResponseFromJSON(jsonValue));
    }

    /**
     * Create a new human user   Create/import a new user with the type human. The newly created user will get a verification email if either the email address is not marked as verified and you did not request the verification to be returned.   Deprecated: please move to the corresponding endpoint under user service v2 (GA)
     * AddHumanUser
     */
    async addHumanUser(requestParameters: AddHumanUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceAddHumanUserResponse> {
        const response = await this.addHumanUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add link to an identity provider to an user   Add link to an identity provider to an user.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * AddIDPLink
     */
    async addIDPLinkRaw(requestParameters: AddIDPLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceAddIDPLinkResponse>> {
        if (requestParameters['betaUserServiceAddIDPLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceAddIDPLinkRequest',
                'Required parameter "betaUserServiceAddIDPLinkRequest" was null or undefined when calling addIDPLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/AddIDPLink`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceAddIDPLinkRequestToJSON(requestParameters['betaUserServiceAddIDPLinkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceAddIDPLinkResponseFromJSON(jsonValue));
    }

    /**
     * Add link to an identity provider to an user   Add link to an identity provider to an user.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * AddIDPLink
     */
    async addIDPLink(requestParameters: AddIDPLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceAddIDPLinkResponse> {
        const response = await this.addIDPLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add OTP Email for a user   Add a new One-Time Password (OTP) Email factor to the authenticated user. OTP Email will enable the user to verify a OTP with the latest verified email. The email has to be verified to add the second factor.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * AddOTPEmail
     */
    async addOTPEmailRaw(requestParameters: AddOTPEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceAddOTPEmailResponse>> {
        if (requestParameters['betaUserServiceAddOTPEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceAddOTPEmailRequest',
                'Required parameter "betaUserServiceAddOTPEmailRequest" was null or undefined when calling addOTPEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/AddOTPEmail`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceAddOTPEmailRequestToJSON(requestParameters['betaUserServiceAddOTPEmailRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceAddOTPEmailResponseFromJSON(jsonValue));
    }

    /**
     * Add OTP Email for a user   Add a new One-Time Password (OTP) Email factor to the authenticated user. OTP Email will enable the user to verify a OTP with the latest verified email. The email has to be verified to add the second factor.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * AddOTPEmail
     */
    async addOTPEmail(requestParameters: AddOTPEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceAddOTPEmailResponse> {
        const response = await this.addOTPEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add OTP SMS for a user   Add a new One-Time Password (OTP) SMS factor to the authenticated user. OTP SMS will enable the user to verify a OTP with the latest verified phone number. The phone number has to be verified to add the second factor.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * AddOTPSMS
     */
    async addOTPSMSRaw(requestParameters: AddOTPSMSRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceAddOTPSMSResponse>> {
        if (requestParameters['betaUserServiceAddOTPSMSRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceAddOTPSMSRequest',
                'Required parameter "betaUserServiceAddOTPSMSRequest" was null or undefined when calling addOTPSMS().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/AddOTPSMS`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceAddOTPSMSRequestToJSON(requestParameters['betaUserServiceAddOTPSMSRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceAddOTPSMSResponseFromJSON(jsonValue));
    }

    /**
     * Add OTP SMS for a user   Add a new One-Time Password (OTP) SMS factor to the authenticated user. OTP SMS will enable the user to verify a OTP with the latest verified phone number. The phone number has to be verified to add the second factor.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * AddOTPSMS
     */
    async addOTPSMS(requestParameters: AddOTPSMSRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceAddOTPSMSResponse> {
        const response = await this.addOTPSMSRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a passkey registration link for a user   Create a passkey registration link which includes a code and either return it or send it to the user.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * CreatePasskeyRegistrationLink
     */
    async createPasskeyRegistrationLinkRaw(requestParameters: CreatePasskeyRegistrationLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceCreatePasskeyRegistrationLinkResponse>> {
        if (requestParameters['betaUserServiceCreatePasskeyRegistrationLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceCreatePasskeyRegistrationLinkRequest',
                'Required parameter "betaUserServiceCreatePasskeyRegistrationLinkRequest" was null or undefined when calling createPasskeyRegistrationLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/CreatePasskeyRegistrationLink`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceCreatePasskeyRegistrationLinkRequestToJSON(requestParameters['betaUserServiceCreatePasskeyRegistrationLinkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceCreatePasskeyRegistrationLinkResponseFromJSON(jsonValue));
    }

    /**
     * Create a passkey registration link for a user   Create a passkey registration link which includes a code and either return it or send it to the user.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * CreatePasskeyRegistrationLink
     */
    async createPasskeyRegistrationLink(requestParameters: CreatePasskeyRegistrationLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceCreatePasskeyRegistrationLinkResponse> {
        const response = await this.createPasskeyRegistrationLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deactivate user   The state of the user will be changed to \'deactivated\'. The user will not be able to log in anymore. The endpoint returns an error if the user is already in the state \'deactivated\'. Use deactivate user when the user should not be able to use the account anymore, but you still need access to the user data.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * DeactivateUser
     */
    async deactivateUserRaw(requestParameters: DeactivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceDeactivateUserResponse>> {
        if (requestParameters['betaUserServiceDeactivateUserRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceDeactivateUserRequest',
                'Required parameter "betaUserServiceDeactivateUserRequest" was null or undefined when calling deactivateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/DeactivateUser`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceDeactivateUserRequestToJSON(requestParameters['betaUserServiceDeactivateUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceDeactivateUserResponseFromJSON(jsonValue));
    }

    /**
     * Deactivate user   The state of the user will be changed to \'deactivated\'. The user will not be able to log in anymore. The endpoint returns an error if the user is already in the state \'deactivated\'. Use deactivate user when the user should not be able to use the account anymore, but you still need access to the user data.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * DeactivateUser
     */
    async deactivateUser(requestParameters: DeactivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceDeactivateUserResponse> {
        const response = await this.deactivateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete user   The state of the user will be changed to \'deleted\'. The user will not be able to log in anymore. Endpoints requesting this user will return an error \'User not found.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * DeleteUser
     */
    async deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceDeleteUserResponse>> {
        if (requestParameters['betaUserServiceDeleteUserRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceDeleteUserRequest',
                'Required parameter "betaUserServiceDeleteUserRequest" was null or undefined when calling deleteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/DeleteUser`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceDeleteUserRequestToJSON(requestParameters['betaUserServiceDeleteUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceDeleteUserResponseFromJSON(jsonValue));
    }

    /**
     * Delete user   The state of the user will be changed to \'deleted\'. The user will not be able to log in anymore. Endpoints requesting this user will return an error \'User not found.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * DeleteUser
     */
    async deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceDeleteUserResponse> {
        const response = await this.deleteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * User by ID   Returns the full user object (human or machine) including the profile, email, etc.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * GetUserByID
     */
    async getUserByIDRaw(requestParameters: GetUserByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceGetUserByIDResponse>> {
        if (requestParameters['betaUserServiceGetUserByIDRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceGetUserByIDRequest',
                'Required parameter "betaUserServiceGetUserByIDRequest" was null or undefined when calling getUserByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/GetUserByID`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceGetUserByIDRequestToJSON(requestParameters['betaUserServiceGetUserByIDRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceGetUserByIDResponseFromJSON(jsonValue));
    }

    /**
     * User by ID   Returns the full user object (human or machine) including the profile, email, etc.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * GetUserByID
     */
    async getUserByID(requestParameters: GetUserByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceGetUserByIDResponse> {
        const response = await this.getUserByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all possible authentication methods of a user   List all possible authentication methods of a user like password, passwordless, (T)OTP and more.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * ListAuthenticationMethodTypes
     */
    async listAuthenticationMethodTypesRaw(requestParameters: ListAuthenticationMethodTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceListAuthenticationMethodTypesResponse>> {
        if (requestParameters['betaUserServiceListAuthenticationMethodTypesRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceListAuthenticationMethodTypesRequest',
                'Required parameter "betaUserServiceListAuthenticationMethodTypesRequest" was null or undefined when calling listAuthenticationMethodTypes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/ListAuthenticationMethodTypes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceListAuthenticationMethodTypesRequestToJSON(requestParameters['betaUserServiceListAuthenticationMethodTypesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceListAuthenticationMethodTypesResponseFromJSON(jsonValue));
    }

    /**
     * List all possible authentication methods of a user   List all possible authentication methods of a user like password, passwordless, (T)OTP and more.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * ListAuthenticationMethodTypes
     */
    async listAuthenticationMethodTypes(requestParameters: ListAuthenticationMethodTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceListAuthenticationMethodTypesResponse> {
        const response = await this.listAuthenticationMethodTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search Users   Search for users. By default, we will return all users of your instance that you have permission to read. Make sure to include a limit and sorting for pagination.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * ListUsers
     */
    async listUsersRaw(requestParameters: ListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceListUsersResponse>> {
        if (requestParameters['betaUserServiceListUsersRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceListUsersRequest',
                'Required parameter "betaUserServiceListUsersRequest" was null or undefined when calling listUsers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/ListUsers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceListUsersRequestToJSON(requestParameters['betaUserServiceListUsersRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceListUsersResponseFromJSON(jsonValue));
    }

    /**
     * Search Users   Search for users. By default, we will return all users of your instance that you have permission to read. Make sure to include a limit and sorting for pagination.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * ListUsers
     */
    async listUsers(requestParameters: ListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceListUsersResponse> {
        const response = await this.listUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lock user   The state of the user will be changed to \'locked\'. The user will not be able to log in anymore. The endpoint returns an error if the user is already in the state \'locked\'. Use this endpoint if the user should not be able to log in temporarily because of an event that happened (wrong password, etc.).   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * LockUser
     */
    async lockUserRaw(requestParameters: LockUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceLockUserResponse>> {
        if (requestParameters['betaUserServiceLockUserRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceLockUserRequest',
                'Required parameter "betaUserServiceLockUserRequest" was null or undefined when calling lockUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/LockUser`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceLockUserRequestToJSON(requestParameters['betaUserServiceLockUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceLockUserResponseFromJSON(jsonValue));
    }

    /**
     * Lock user   The state of the user will be changed to \'locked\'. The user will not be able to log in anymore. The endpoint returns an error if the user is already in the state \'locked\'. Use this endpoint if the user should not be able to log in temporarily because of an event that happened (wrong password, etc.).   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * LockUser
     */
    async lockUser(requestParameters: LockUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceLockUserResponse> {
        const response = await this.lockUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Dummy endpoint to retain union-member schemas
     */
    async noOpRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NoOp200Response9>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/56a395ed`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NoOp200Response9FromJSON(jsonValue));
    }

    /**
     * Dummy endpoint to retain union-member schemas
     */
    async noOp(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NoOp200Response9> {
        const response = await this.noOpRaw(initOverrides);
        return await response.value();
    }

    /**
     * Request a code to reset a password   Request a code to reset a password.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * PasswordReset
     */
    async passwordResetRaw(requestParameters: PasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServicePasswordResetResponse>> {
        if (requestParameters['betaUserServicePasswordResetRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServicePasswordResetRequest',
                'Required parameter "betaUserServicePasswordResetRequest" was null or undefined when calling passwordReset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/PasswordReset`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServicePasswordResetRequestToJSON(requestParameters['betaUserServicePasswordResetRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServicePasswordResetResponseFromJSON(jsonValue));
    }

    /**
     * Request a code to reset a password   Request a code to reset a password.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * PasswordReset
     */
    async passwordReset(requestParameters: PasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServicePasswordResetResponse> {
        const response = await this.passwordResetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reactivate user   Reactivate a user with the state \'deactivated\'. The user will be able to log in again afterward. The endpoint returns an error if the user is not in the state \'deactivated\'.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * ReactivateUser
     */
    async reactivateUserRaw(requestParameters: ReactivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceReactivateUserResponse>> {
        if (requestParameters['betaUserServiceReactivateUserRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceReactivateUserRequest',
                'Required parameter "betaUserServiceReactivateUserRequest" was null or undefined when calling reactivateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/ReactivateUser`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceReactivateUserRequestToJSON(requestParameters['betaUserServiceReactivateUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceReactivateUserResponseFromJSON(jsonValue));
    }

    /**
     * Reactivate user   Reactivate a user with the state \'deactivated\'. The user will be able to log in again afterward. The endpoint returns an error if the user is not in the state \'deactivated\'.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * ReactivateUser
     */
    async reactivateUser(requestParameters: ReactivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceReactivateUserResponse> {
        const response = await this.reactivateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start the registration of passkey for a user   Start the registration of a passkey for a user, as a response the public key credential creation options are returned, which are used to verify the passkey.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RegisterPasskey
     */
    async registerPasskeyRaw(requestParameters: RegisterPasskeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceRegisterPasskeyResponse>> {
        if (requestParameters['betaUserServiceRegisterPasskeyRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceRegisterPasskeyRequest',
                'Required parameter "betaUserServiceRegisterPasskeyRequest" was null or undefined when calling registerPasskey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/RegisterPasskey`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceRegisterPasskeyRequestToJSON(requestParameters['betaUserServiceRegisterPasskeyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceRegisterPasskeyResponseFromJSON(jsonValue));
    }

    /**
     * Start the registration of passkey for a user   Start the registration of a passkey for a user, as a response the public key credential creation options are returned, which are used to verify the passkey.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RegisterPasskey
     */
    async registerPasskey(requestParameters: RegisterPasskeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceRegisterPasskeyResponse> {
        const response = await this.registerPasskeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start the registration of a TOTP generator for a user   Start the registration of a TOTP generator for a user, as a response a secret returned, which is used to initialize a TOTP app or device.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RegisterTOTP
     */
    async registerTOTPRaw(requestParameters: RegisterTOTPRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceRegisterTOTPResponse>> {
        if (requestParameters['betaUserServiceRegisterTOTPRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceRegisterTOTPRequest',
                'Required parameter "betaUserServiceRegisterTOTPRequest" was null or undefined when calling registerTOTP().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/RegisterTOTP`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceRegisterTOTPRequestToJSON(requestParameters['betaUserServiceRegisterTOTPRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceRegisterTOTPResponseFromJSON(jsonValue));
    }

    /**
     * Start the registration of a TOTP generator for a user   Start the registration of a TOTP generator for a user, as a response a secret returned, which is used to initialize a TOTP app or device.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RegisterTOTP
     */
    async registerTOTP(requestParameters: RegisterTOTPRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceRegisterTOTPResponse> {
        const response = await this.registerTOTPRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start the registration of a u2f token for a user   Start the registration of a u2f token for a user, as a response the public key credential creation options are returned, which are used to verify the u2f token.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RegisterU2F
     */
    async registerU2FRaw(requestParameters: RegisterU2FRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceRegisterU2FResponse>> {
        if (requestParameters['betaUserServiceRegisterU2FRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceRegisterU2FRequest',
                'Required parameter "betaUserServiceRegisterU2FRequest" was null or undefined when calling registerU2F().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/RegisterU2F`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceRegisterU2FRequestToJSON(requestParameters['betaUserServiceRegisterU2FRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceRegisterU2FResponseFromJSON(jsonValue));
    }

    /**
     * Start the registration of a u2f token for a user   Start the registration of a u2f token for a user, as a response the public key credential creation options are returned, which are used to verify the u2f token.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RegisterU2F
     */
    async registerU2F(requestParameters: RegisterU2FRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceRegisterU2FResponse> {
        const response = await this.registerU2FRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove One-Time Password (OTP) Email from a user   Remove the configured One-Time Password (OTP) Email factor of a user. As only one OTP Email per user is allowed, the user will not have OTP Email as a second factor afterward.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RemoveOTPEmail
     */
    async removeOTPEmailRaw(requestParameters: RemoveOTPEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceRemoveOTPEmailResponse>> {
        if (requestParameters['betaUserServiceRemoveOTPEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceRemoveOTPEmailRequest',
                'Required parameter "betaUserServiceRemoveOTPEmailRequest" was null or undefined when calling removeOTPEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/RemoveOTPEmail`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceRemoveOTPEmailRequestToJSON(requestParameters['betaUserServiceRemoveOTPEmailRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceRemoveOTPEmailResponseFromJSON(jsonValue));
    }

    /**
     * Remove One-Time Password (OTP) Email from a user   Remove the configured One-Time Password (OTP) Email factor of a user. As only one OTP Email per user is allowed, the user will not have OTP Email as a second factor afterward.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RemoveOTPEmail
     */
    async removeOTPEmail(requestParameters: RemoveOTPEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceRemoveOTPEmailResponse> {
        const response = await this.removeOTPEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove One-Time Password (OTP) SMS from a user   Remove the configured One-Time Password (OTP) SMS factor of a user. As only one OTP SMS per user is allowed, the user will not have OTP SMS as a second factor afterward.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RemoveOTPSMS
     */
    async removeOTPSMSRaw(requestParameters: RemoveOTPSMSRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceRemoveOTPSMSResponse>> {
        if (requestParameters['betaUserServiceRemoveOTPSMSRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceRemoveOTPSMSRequest',
                'Required parameter "betaUserServiceRemoveOTPSMSRequest" was null or undefined when calling removeOTPSMS().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/RemoveOTPSMS`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceRemoveOTPSMSRequestToJSON(requestParameters['betaUserServiceRemoveOTPSMSRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceRemoveOTPSMSResponseFromJSON(jsonValue));
    }

    /**
     * Remove One-Time Password (OTP) SMS from a user   Remove the configured One-Time Password (OTP) SMS factor of a user. As only one OTP SMS per user is allowed, the user will not have OTP SMS as a second factor afterward.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RemoveOTPSMS
     */
    async removeOTPSMS(requestParameters: RemoveOTPSMSRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceRemoveOTPSMSResponse> {
        const response = await this.removeOTPSMSRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove the user phone   Remove the user phone   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RemovePhone
     */
    async removePhoneRaw(requestParameters: RemovePhoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceRemovePhoneResponse>> {
        if (requestParameters['betaUserServiceRemovePhoneRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceRemovePhoneRequest',
                'Required parameter "betaUserServiceRemovePhoneRequest" was null or undefined when calling removePhone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/RemovePhone`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceRemovePhoneRequestToJSON(requestParameters['betaUserServiceRemovePhoneRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceRemovePhoneResponseFromJSON(jsonValue));
    }

    /**
     * Remove the user phone   Remove the user phone   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RemovePhone
     */
    async removePhone(requestParameters: RemovePhoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceRemovePhoneResponse> {
        const response = await this.removePhoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove TOTP generator from a user   Remove the configured TOTP generator of a user. As only one TOTP generator per user is allowed, the user will not have TOTP as a second factor afterward.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RemoveTOTP
     */
    async removeTOTPRaw(requestParameters: RemoveTOTPRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceRemoveTOTPResponse>> {
        if (requestParameters['betaUserServiceRemoveTOTPRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceRemoveTOTPRequest',
                'Required parameter "betaUserServiceRemoveTOTPRequest" was null or undefined when calling removeTOTP().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/RemoveTOTP`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceRemoveTOTPRequestToJSON(requestParameters['betaUserServiceRemoveTOTPRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceRemoveTOTPResponseFromJSON(jsonValue));
    }

    /**
     * Remove TOTP generator from a user   Remove the configured TOTP generator of a user. As only one TOTP generator per user is allowed, the user will not have TOTP as a second factor afterward.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RemoveTOTP
     */
    async removeTOTP(requestParameters: RemoveTOTPRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceRemoveTOTPResponse> {
        const response = await this.removeTOTPRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resend code to verify user email   Resend code to verify user email   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * ResendEmailCode
     */
    async resendEmailCodeRaw(requestParameters: ResendEmailCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceResendEmailCodeResponse>> {
        if (requestParameters['betaUserServiceResendEmailCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceResendEmailCodeRequest',
                'Required parameter "betaUserServiceResendEmailCodeRequest" was null or undefined when calling resendEmailCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/ResendEmailCode`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceResendEmailCodeRequestToJSON(requestParameters['betaUserServiceResendEmailCodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceResendEmailCodeResponseFromJSON(jsonValue));
    }

    /**
     * Resend code to verify user email   Resend code to verify user email   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * ResendEmailCode
     */
    async resendEmailCode(requestParameters: ResendEmailCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceResendEmailCodeResponse> {
        const response = await this.resendEmailCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resend code to verify user phone   Resend code to verify user phone   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * ResendPhoneCode
     */
    async resendPhoneCodeRaw(requestParameters: ResendPhoneCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceResendPhoneCodeResponse>> {
        if (requestParameters['betaUserServiceResendPhoneCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceResendPhoneCodeRequest',
                'Required parameter "betaUserServiceResendPhoneCodeRequest" was null or undefined when calling resendPhoneCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/ResendPhoneCode`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceResendPhoneCodeRequestToJSON(requestParameters['betaUserServiceResendPhoneCodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceResendPhoneCodeResponseFromJSON(jsonValue));
    }

    /**
     * Resend code to verify user phone   Resend code to verify user phone   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * ResendPhoneCode
     */
    async resendPhoneCode(requestParameters: ResendPhoneCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceResendPhoneCodeResponse> {
        const response = await this.resendPhoneCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the information returned by the identity provider   Retrieve the information returned by the identity provider for registration or updating an existing user with new information.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RetrieveIdentityProviderIntent
     */
    async retrieveIdentityProviderIntentRaw(requestParameters: RetrieveIdentityProviderIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceRetrieveIdentityProviderIntentResponse>> {
        if (requestParameters['betaUserServiceRetrieveIdentityProviderIntentRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceRetrieveIdentityProviderIntentRequest',
                'Required parameter "betaUserServiceRetrieveIdentityProviderIntentRequest" was null or undefined when calling retrieveIdentityProviderIntent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/RetrieveIdentityProviderIntent`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceRetrieveIdentityProviderIntentRequestToJSON(requestParameters['betaUserServiceRetrieveIdentityProviderIntentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceRetrieveIdentityProviderIntentResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the information returned by the identity provider   Retrieve the information returned by the identity provider for registration or updating an existing user with new information.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * RetrieveIdentityProviderIntent
     */
    async retrieveIdentityProviderIntent(requestParameters: RetrieveIdentityProviderIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceRetrieveIdentityProviderIntentResponse> {
        const response = await this.retrieveIdentityProviderIntentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change the user email   Change the email address of a user. If the state is set to not verified, a verification code will be generated, which can be either returned or sent to the user by email.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * SetEmail
     */
    async setEmailRaw(requestParameters: SetEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceSetEmailResponse>> {
        if (requestParameters['betaUserServiceSetEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceSetEmailRequest',
                'Required parameter "betaUserServiceSetEmailRequest" was null or undefined when calling setEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/SetEmail`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceSetEmailRequestToJSON(requestParameters['betaUserServiceSetEmailRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceSetEmailResponseFromJSON(jsonValue));
    }

    /**
     * Change the user email   Change the email address of a user. If the state is set to not verified, a verification code will be generated, which can be either returned or sent to the user by email.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * SetEmail
     */
    async setEmail(requestParameters: SetEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceSetEmailResponse> {
        const response = await this.setEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change password   Change the password of a user with either a verification code or the current password.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * SetPassword
     */
    async setPasswordRaw(requestParameters: SetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceSetPasswordResponse>> {
        if (requestParameters['betaUserServiceSetPasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceSetPasswordRequest',
                'Required parameter "betaUserServiceSetPasswordRequest" was null or undefined when calling setPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/SetPassword`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceSetPasswordRequestToJSON(requestParameters['betaUserServiceSetPasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceSetPasswordResponseFromJSON(jsonValue));
    }

    /**
     * Change password   Change the password of a user with either a verification code or the current password.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * SetPassword
     */
    async setPassword(requestParameters: SetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceSetPasswordResponse> {
        const response = await this.setPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set the user phone   Set the phone number of a user. If the state is set to not verified, a verification code will be generated, which can be either returned or sent to the user by sms.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * SetPhone
     */
    async setPhoneRaw(requestParameters: SetPhoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceSetPhoneResponse>> {
        if (requestParameters['betaUserServiceSetPhoneRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceSetPhoneRequest',
                'Required parameter "betaUserServiceSetPhoneRequest" was null or undefined when calling setPhone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/SetPhone`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceSetPhoneRequestToJSON(requestParameters['betaUserServiceSetPhoneRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceSetPhoneResponseFromJSON(jsonValue));
    }

    /**
     * Set the user phone   Set the phone number of a user. If the state is set to not verified, a verification code will be generated, which can be either returned or sent to the user by sms.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * SetPhone
     */
    async setPhone(requestParameters: SetPhoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceSetPhoneResponse> {
        const response = await this.setPhoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start flow with an identity provider   Start a flow with an identity provider, for external login, registration or linking.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * StartIdentityProviderIntent
     */
    async startIdentityProviderIntentRaw(requestParameters: StartIdentityProviderIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceStartIdentityProviderIntentResponse>> {
        if (requestParameters['betaUserServiceStartIdentityProviderIntentRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceStartIdentityProviderIntentRequest',
                'Required parameter "betaUserServiceStartIdentityProviderIntentRequest" was null or undefined when calling startIdentityProviderIntent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/StartIdentityProviderIntent`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceStartIdentityProviderIntentRequestToJSON(requestParameters['betaUserServiceStartIdentityProviderIntentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceStartIdentityProviderIntentResponseFromJSON(jsonValue));
    }

    /**
     * Start flow with an identity provider   Start a flow with an identity provider, for external login, registration or linking.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * StartIdentityProviderIntent
     */
    async startIdentityProviderIntent(requestParameters: StartIdentityProviderIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceStartIdentityProviderIntentResponse> {
        const response = await this.startIdentityProviderIntentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlock user   The state of the user will be changed to \'locked\'. The user will not be able to log in anymore. The endpoint returns an error if the user is already in the state \'locked\'. Use this endpoint if the user should not be able to log in temporarily because of an event that happened (wrong password, etc.).   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * UnlockUser
     */
    async unlockUserRaw(requestParameters: UnlockUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceUnlockUserResponse>> {
        if (requestParameters['betaUserServiceUnlockUserRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceUnlockUserRequest',
                'Required parameter "betaUserServiceUnlockUserRequest" was null or undefined when calling unlockUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/UnlockUser`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceUnlockUserRequestToJSON(requestParameters['betaUserServiceUnlockUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceUnlockUserResponseFromJSON(jsonValue));
    }

    /**
     * Unlock user   The state of the user will be changed to \'locked\'. The user will not be able to log in anymore. The endpoint returns an error if the user is already in the state \'locked\'. Use this endpoint if the user should not be able to log in temporarily because of an event that happened (wrong password, etc.).   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * UnlockUser
     */
    async unlockUser(requestParameters: UnlockUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceUnlockUserResponse> {
        const response = await this.unlockUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update User   Update all information from a user.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * UpdateHumanUser
     */
    async updateHumanUserRaw(requestParameters: UpdateHumanUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceUpdateHumanUserResponse>> {
        if (requestParameters['betaUserServiceUpdateHumanUserRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceUpdateHumanUserRequest',
                'Required parameter "betaUserServiceUpdateHumanUserRequest" was null or undefined when calling updateHumanUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/UpdateHumanUser`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceUpdateHumanUserRequestToJSON(requestParameters['betaUserServiceUpdateHumanUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceUpdateHumanUserResponseFromJSON(jsonValue));
    }

    /**
     * Update User   Update all information from a user.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * UpdateHumanUser
     */
    async updateHumanUser(requestParameters: UpdateHumanUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceUpdateHumanUserResponse> {
        const response = await this.updateHumanUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify the email   Verify the email with the generated code.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * VerifyEmail
     */
    async verifyEmailRaw(requestParameters: VerifyEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceVerifyEmailResponse>> {
        if (requestParameters['betaUserServiceVerifyEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceVerifyEmailRequest',
                'Required parameter "betaUserServiceVerifyEmailRequest" was null or undefined when calling verifyEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/VerifyEmail`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceVerifyEmailRequestToJSON(requestParameters['betaUserServiceVerifyEmailRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceVerifyEmailResponseFromJSON(jsonValue));
    }

    /**
     * Verify the email   Verify the email with the generated code.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * VerifyEmail
     */
    async verifyEmail(requestParameters: VerifyEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceVerifyEmailResponse> {
        const response = await this.verifyEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify a passkey for a user   Verify the passkey registration with the public key credential.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * VerifyPasskeyRegistration
     */
    async verifyPasskeyRegistrationRaw(requestParameters: VerifyPasskeyRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceVerifyPasskeyRegistrationResponse>> {
        if (requestParameters['betaUserServiceVerifyPasskeyRegistrationRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceVerifyPasskeyRegistrationRequest',
                'Required parameter "betaUserServiceVerifyPasskeyRegistrationRequest" was null or undefined when calling verifyPasskeyRegistration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/VerifyPasskeyRegistration`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceVerifyPasskeyRegistrationRequestToJSON(requestParameters['betaUserServiceVerifyPasskeyRegistrationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceVerifyPasskeyRegistrationResponseFromJSON(jsonValue));
    }

    /**
     * Verify a passkey for a user   Verify the passkey registration with the public key credential.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * VerifyPasskeyRegistration
     */
    async verifyPasskeyRegistration(requestParameters: VerifyPasskeyRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceVerifyPasskeyRegistrationResponse> {
        const response = await this.verifyPasskeyRegistrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify the phone   Verify the phone with the generated code.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * VerifyPhone
     */
    async verifyPhoneRaw(requestParameters: VerifyPhoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceVerifyPhoneResponse>> {
        if (requestParameters['betaUserServiceVerifyPhoneRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceVerifyPhoneRequest',
                'Required parameter "betaUserServiceVerifyPhoneRequest" was null or undefined when calling verifyPhone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/VerifyPhone`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceVerifyPhoneRequestToJSON(requestParameters['betaUserServiceVerifyPhoneRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceVerifyPhoneResponseFromJSON(jsonValue));
    }

    /**
     * Verify the phone   Verify the phone with the generated code.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * VerifyPhone
     */
    async verifyPhone(requestParameters: VerifyPhoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceVerifyPhoneResponse> {
        const response = await this.verifyPhoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify a TOTP generator for a user   Verify the TOTP registration with a generated code.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * VerifyTOTPRegistration
     */
    async verifyTOTPRegistrationRaw(requestParameters: VerifyTOTPRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceVerifyTOTPRegistrationResponse>> {
        if (requestParameters['betaUserServiceVerifyTOTPRegistrationRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceVerifyTOTPRegistrationRequest',
                'Required parameter "betaUserServiceVerifyTOTPRegistrationRequest" was null or undefined when calling verifyTOTPRegistration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/VerifyTOTPRegistration`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceVerifyTOTPRegistrationRequestToJSON(requestParameters['betaUserServiceVerifyTOTPRegistrationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceVerifyTOTPRegistrationResponseFromJSON(jsonValue));
    }

    /**
     * Verify a TOTP generator for a user   Verify the TOTP registration with a generated code.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * VerifyTOTPRegistration
     */
    async verifyTOTPRegistration(requestParameters: VerifyTOTPRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceVerifyTOTPRegistrationResponse> {
        const response = await this.verifyTOTPRegistrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify a u2f token for a user   Verify the u2f token registration with the public key credential.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * VerifyU2FRegistration
     */
    async verifyU2FRegistrationRaw(requestParameters: VerifyU2FRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaUserServiceVerifyU2FRegistrationResponse>> {
        if (requestParameters['betaUserServiceVerifyU2FRegistrationRequest'] == null) {
            throw new runtime.RequiredError(
                'betaUserServiceVerifyU2FRegistrationRequest',
                'Required parameter "betaUserServiceVerifyU2FRegistrationRequest" was null or undefined when calling verifyU2FRegistration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("zitadelAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/zitadel.user.v2beta.UserService/VerifyU2FRegistration`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BetaUserServiceVerifyU2FRegistrationRequestToJSON(requestParameters['betaUserServiceVerifyU2FRegistrationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaUserServiceVerifyU2FRegistrationResponseFromJSON(jsonValue));
    }

    /**
     * Verify a u2f token for a user   Verify the u2f token registration with the public key credential.   Deprecated: please move to the corresponding endpoint under user service v2 (GA).
     * VerifyU2FRegistration
     */
    async verifyU2FRegistration(requestParameters: VerifyU2FRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaUserServiceVerifyU2FRegistrationResponse> {
        const response = await this.verifyU2FRegistrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
