/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ActionServiceListExecutionServicesResponse
 */
export interface ActionServiceListExecutionServicesResponse {
    /**
     * All available services to use in conditions.
     * @type {Array<string>}
     * @memberof ActionServiceListExecutionServicesResponse
     */
    services?: Array<string>;
}

/**
 * Check if a given object implements the ActionServiceListExecutionServicesResponse interface.
 */
export function instanceOfActionServiceListExecutionServicesResponse(value: object): value is ActionServiceListExecutionServicesResponse {
    return true;
}

export function ActionServiceListExecutionServicesResponseFromJSON(json: any): ActionServiceListExecutionServicesResponse {
    return ActionServiceListExecutionServicesResponseFromJSONTyped(json, false);
}

export function ActionServiceListExecutionServicesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionServiceListExecutionServicesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'services': json['services'] == null ? undefined : json['services'],
    };
}

export function ActionServiceListExecutionServicesResponseToJSON(json: any): ActionServiceListExecutionServicesResponse {
    return ActionServiceListExecutionServicesResponseToJSONTyped(json, false);
}

export function ActionServiceListExecutionServicesResponseToJSONTyped(value?: ActionServiceListExecutionServicesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'services': value['services'],
    };
}

