// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

import { ActionServiceInIDsFilter } from "./action-service-in-ids-filter.js";
import { ActionServiceTimestampFilter } from "./action-service-timestamp-filter.js";
import { Expose, Type } from "class-transformer";

export class ActionServicePublicKeySearchFilter {
  /**
   * Filter the keys by their active status.
   * @example null
   */
  @Expose({ name: "activeFilter" })
  activeFilter?: boolean;
  /** @example null */
  @Expose({ name: "expirationDateFilter" })
  @Type(() => ActionServiceTimestampFilter)
  expirationDateFilter?: ActionServiceTimestampFilter;
  /** @example null */
  @Expose({ name: "keyIdsFilter" })
  @Type(() => ActionServiceInIDsFilter)
  keyIdsFilter?: ActionServiceInIDsFilter;

  constructor(data?: Partial<ActionServicePublicKeySearchFilter>) {
    Object.assign(this, data);
    if (this.activeFilter != null && typeof this.activeFilter !== "boolean") {
      throw new TypeError(
        `activeFilter must be a boolean, got ${typeof this.activeFilter}`,
      );
    }
  }

  /**
   * Value-equality across all declared fields. Two instances are equal when
   * every field deep-equals the other's. Arrays, plain objects, Sets, Maps,
   * Buffers and Date values are compared structurally; nested model fields
   * fall through to their own {@link equals} when present, otherwise to a
   * recursive structural compare. Mirrors the value-equality exposed by the
   * other SDKs (node-model-equality).
   */
  equals(other: unknown): boolean {
    if (this === other) {
      return true;
    }
    if (!(other instanceof ActionServicePublicKeySearchFilter)) {
      return false;
    }
    if (
      !ActionServicePublicKeySearchFilter.__deepEquals(
        this.activeFilter,
        (other as ActionServicePublicKeySearchFilter).activeFilter,
      )
    ) {
      return false;
    }
    if (
      !ActionServicePublicKeySearchFilter.__deepEquals(
        this.expirationDateFilter,
        (other as ActionServicePublicKeySearchFilter).expirationDateFilter,
      )
    ) {
      return false;
    }
    if (
      !ActionServicePublicKeySearchFilter.__deepEquals(
        this.keyIdsFilter,
        (other as ActionServicePublicKeySearchFilter).keyIdsFilter,
      )
    ) {
      return false;
    }
    return true;
  }

  /**
   * Recursive structural comparison used by {@link equals}. Defers to a
   * nested value's own `equals` method when it exposes one (generated
   * models do), so equality stays value-based all the way down.
   */
  private static __deepEquals(a: unknown, b: unknown): boolean {
    if (a === b) {
      return true;
    }
    if (a == null || b == null) {
      return a === b;
    }
    if (
      typeof (a as { equals?: unknown }).equals === "function" &&
      a.constructor === b.constructor
    ) {
      return (a as { equals(o: unknown): boolean }).equals(b);
    }
    if (Buffer.isBuffer(a) && Buffer.isBuffer(b)) {
      return a.equals(b);
    }
    if (a instanceof Date && b instanceof Date) {
      return a.getTime() === b.getTime();
    }
    if (Array.isArray(a) && Array.isArray(b)) {
      if (a.length !== b.length) {
        return false;
      }
      return a.every((v, i) =>
        ActionServicePublicKeySearchFilter.__deepEquals(v, b[i]),
      );
    }
    if (a instanceof Set && b instanceof Set) {
      if (a.size !== b.size) {
        return false;
      }
      const bvals = [...b];
      return [...a].every((v) =>
        bvals.some((w) =>
          ActionServicePublicKeySearchFilter.__deepEquals(v, w),
        ),
      );
    }
    if (a instanceof Map && b instanceof Map) {
      if (a.size !== b.size) {
        return false;
      }
      for (const [k, v] of a) {
        if (
          !b.has(k) ||
          !ActionServicePublicKeySearchFilter.__deepEquals(v, b.get(k))
        ) {
          return false;
        }
      }
      return true;
    }
    if (typeof a === "object" && typeof b === "object") {
      const ar = a as Record<string, unknown>;
      const br = b as Record<string, unknown>;
      const ak = Object.keys(ar);
      const bk = Object.keys(br);
      if (ak.length !== bk.length) {
        return false;
      }
      return ak.every(
        (k) =>
          Object.prototype.hasOwnProperty.call(br, k) &&
          ActionServicePublicKeySearchFilter.__deepEquals(ar[k], br[k]),
      );
    }
    return false;
  }
}
