/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ActionServiceBetaPaginationRequest } from './ActionServiceBetaPaginationRequest.js';
import {
    ActionServiceBetaPaginationRequestFromJSON,
    ActionServiceBetaPaginationRequestFromJSONTyped,
    ActionServiceBetaPaginationRequestToJSON,
    ActionServiceBetaPaginationRequestToJSONTyped,
} from './ActionServiceBetaPaginationRequest.js';
import type { ActionServiceBetaTargetSearchFilter } from './ActionServiceBetaTargetSearchFilter.js';
import {
    ActionServiceBetaTargetSearchFilterFromJSON,
    ActionServiceBetaTargetSearchFilterFromJSONTyped,
    ActionServiceBetaTargetSearchFilterToJSON,
    ActionServiceBetaTargetSearchFilterToJSONTyped,
} from './ActionServiceBetaTargetSearchFilter.js';
import type { ActionServiceBetaTargetFieldName } from './ActionServiceBetaTargetFieldName.js';
import {
    ActionServiceBetaTargetFieldNameFromJSON,
    ActionServiceBetaTargetFieldNameFromJSONTyped,
    ActionServiceBetaTargetFieldNameToJSON,
    ActionServiceBetaTargetFieldNameToJSONTyped,
} from './ActionServiceBetaTargetFieldName.js';

/**
 * 
 * @export
 * @interface ActionServiceListTargetsRequest
 */
export interface ActionServiceListTargetsRequest {
    /**
     * 
     * @type {ActionServiceBetaPaginationRequest}
     * @memberof ActionServiceListTargetsRequest
     */
    pagination?: ActionServiceBetaPaginationRequest;
    /**
     * 
     * @type {ActionServiceBetaTargetFieldName}
     * @memberof ActionServiceListTargetsRequest
     */
    sortingColumn?: ActionServiceBetaTargetFieldName;
    /**
     * Define the criteria to query for.
     * @type {Array<ActionServiceBetaTargetSearchFilter>}
     * @memberof ActionServiceListTargetsRequest
     */
    filters?: Array<ActionServiceBetaTargetSearchFilter>;
}



/**
 * Check if a given object implements the ActionServiceListTargetsRequest interface.
 */
export function instanceOfActionServiceListTargetsRequest(value: object): value is ActionServiceListTargetsRequest {
    return true;
}

export function ActionServiceListTargetsRequestFromJSON(json: any): ActionServiceListTargetsRequest {
    return ActionServiceListTargetsRequestFromJSONTyped(json, false);
}

export function ActionServiceListTargetsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionServiceListTargetsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination': json['pagination'] == null ? undefined : ActionServiceBetaPaginationRequestFromJSON(json['pagination']),
        'sortingColumn': json['sortingColumn'] == null ? undefined : ActionServiceBetaTargetFieldNameFromJSON(json['sortingColumn']),
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(ActionServiceBetaTargetSearchFilterFromJSON)),
    };
}

export function ActionServiceListTargetsRequestToJSON(json: any): ActionServiceListTargetsRequest {
    return ActionServiceListTargetsRequestToJSONTyped(json, false);
}

export function ActionServiceListTargetsRequestToJSONTyped(value?: ActionServiceListTargetsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': ActionServiceBetaPaginationRequestToJSON(value['pagination']),
        'sortingColumn': ActionServiceBetaTargetFieldNameToJSON(value['sortingColumn']),
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(ActionServiceBetaTargetSearchFilterToJSON)),
    };
}

