// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

import { ApplicationServiceUpdateAPIApplicationConfigurationRequest } from "./application-service-update-api-application-configuration-request.js";
import { ApplicationServiceUpdateOIDCApplicationConfigurationRequest } from "./application-service-update-oidc-application-configuration-request.js";
import { ApplicationServiceUpdateSAMLApplicationConfigurationRequest } from "./application-service-update-saml-application-configuration-request.js";
import { Expose, Type } from "class-transformer";

export class ApplicationServiceUpdateApplicationRequest {
  /**
   * The unique ID of the application to be updated.
   * @example null
   */
  @Expose({ name: "applicationId" })
  applicationId?: string;
  /**
   * The ID of the project the application belongs to.
   * @example null
   */
  @Expose({ name: "projectId" })
  projectId?: string;
  /**
   * Publicly visible name of the application. This might be presented to users if they sign in.  If not set, the name will not be changed.
   * @example null
   */
  @Expose({ name: "name" })
  name?: string;
  /** @example null */
  @Expose({ name: "apiConfiguration" })
  @Type(() => ApplicationServiceUpdateAPIApplicationConfigurationRequest)
  apiConfiguration?: ApplicationServiceUpdateAPIApplicationConfigurationRequest;
  /** @example null */
  @Expose({ name: "oidcConfiguration" })
  @Type(() => ApplicationServiceUpdateOIDCApplicationConfigurationRequest)
  oidcConfiguration?: ApplicationServiceUpdateOIDCApplicationConfigurationRequest;
  /** @example null */
  @Expose({ name: "samlConfiguration" })
  @Type(() => ApplicationServiceUpdateSAMLApplicationConfigurationRequest)
  samlConfiguration?: ApplicationServiceUpdateSAMLApplicationConfigurationRequest;

  constructor(data?: Partial<ApplicationServiceUpdateApplicationRequest>) {
    Object.assign(this, data);
    if (this.applicationId != null && typeof this.applicationId !== "string") {
      throw new TypeError(
        `applicationId must be a string, got ${typeof this.applicationId}`,
      );
    }
    if (this.projectId != null && typeof this.projectId !== "string") {
      throw new TypeError(
        `projectId must be a string, got ${typeof this.projectId}`,
      );
    }
    if (this.name != null && typeof this.name !== "string") {
      throw new TypeError(`name must be a string, got ${typeof this.name}`);
    }
  }

  /**
   * Value-equality across all declared fields. Two instances are equal when
   * every field deep-equals the other's. Arrays, plain objects, Sets, Maps,
   * Buffers and Date values are compared structurally; nested model fields
   * fall through to their own {@link equals} when present, otherwise to a
   * recursive structural compare. Mirrors the value-equality exposed by the
   * other SDKs (node-model-equality).
   */
  equals(other: unknown): boolean {
    if (this === other) {
      return true;
    }
    if (!(other instanceof ApplicationServiceUpdateApplicationRequest)) {
      return false;
    }
    if (
      !ApplicationServiceUpdateApplicationRequest.__deepEquals(
        this.applicationId,
        (other as ApplicationServiceUpdateApplicationRequest).applicationId,
      )
    ) {
      return false;
    }
    if (
      !ApplicationServiceUpdateApplicationRequest.__deepEquals(
        this.projectId,
        (other as ApplicationServiceUpdateApplicationRequest).projectId,
      )
    ) {
      return false;
    }
    if (
      !ApplicationServiceUpdateApplicationRequest.__deepEquals(
        this.name,
        (other as ApplicationServiceUpdateApplicationRequest).name,
      )
    ) {
      return false;
    }
    if (
      !ApplicationServiceUpdateApplicationRequest.__deepEquals(
        this.apiConfiguration,
        (other as ApplicationServiceUpdateApplicationRequest).apiConfiguration,
      )
    ) {
      return false;
    }
    if (
      !ApplicationServiceUpdateApplicationRequest.__deepEquals(
        this.oidcConfiguration,
        (other as ApplicationServiceUpdateApplicationRequest).oidcConfiguration,
      )
    ) {
      return false;
    }
    if (
      !ApplicationServiceUpdateApplicationRequest.__deepEquals(
        this.samlConfiguration,
        (other as ApplicationServiceUpdateApplicationRequest).samlConfiguration,
      )
    ) {
      return false;
    }
    return true;
  }

  /**
   * Recursive structural comparison used by {@link equals}. Defers to a
   * nested value's own `equals` method when it exposes one (generated
   * models do), so equality stays value-based all the way down.
   */
  private static __deepEquals(a: unknown, b: unknown): boolean {
    if (a === b) {
      return true;
    }
    if (a == null || b == null) {
      return a === b;
    }
    if (
      typeof (a as { equals?: unknown }).equals === "function" &&
      a.constructor === b.constructor
    ) {
      return (a as { equals(o: unknown): boolean }).equals(b);
    }
    if (Buffer.isBuffer(a) && Buffer.isBuffer(b)) {
      return a.equals(b);
    }
    if (a instanceof Date && b instanceof Date) {
      return a.getTime() === b.getTime();
    }
    if (Array.isArray(a) && Array.isArray(b)) {
      if (a.length !== b.length) {
        return false;
      }
      return a.every((v, i) =>
        ApplicationServiceUpdateApplicationRequest.__deepEquals(v, b[i]),
      );
    }
    if (a instanceof Set && b instanceof Set) {
      if (a.size !== b.size) {
        return false;
      }
      const bvals = [...b];
      return [...a].every((v) =>
        bvals.some((w) =>
          ApplicationServiceUpdateApplicationRequest.__deepEquals(v, w),
        ),
      );
    }
    if (a instanceof Map && b instanceof Map) {
      if (a.size !== b.size) {
        return false;
      }
      for (const [k, v] of a) {
        if (
          !b.has(k) ||
          !ApplicationServiceUpdateApplicationRequest.__deepEquals(v, b.get(k))
        ) {
          return false;
        }
      }
      return true;
    }
    if (typeof a === "object" && typeof b === "object") {
      const ar = a as Record<string, unknown>;
      const br = b as Record<string, unknown>;
      const ak = Object.keys(ar);
      const bk = Object.keys(br);
      if (ak.length !== bk.length) {
        return false;
      }
      return ak.every(
        (k) =>
          Object.prototype.hasOwnProperty.call(br, k) &&
          ApplicationServiceUpdateApplicationRequest.__deepEquals(ar[k], br[k]),
      );
    }
    return false;
  }
}
