// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

import { ApplicationServiceApplicationNameFilter } from "./application-service-application-name-filter.js";
import { ApplicationServiceApplicationState } from "./application-service-application-state.js";
import { ApplicationServiceApplicationType } from "./application-service-application-type.js";
import { ApplicationServiceClientIDFilter } from "./application-service-client-id-filter.js";
import { ApplicationServiceEntityIDFilter } from "./application-service-entity-id-filter.js";
import { ApplicationServiceProjectIDFilter } from "./application-service-project-id-filter.js";
import { Expose, Type } from "class-transformer";

export class ApplicationServiceApplicationSearchFilter {
  /**
   * 2.5 — Wire-serialization registry for `type: number` (no format)
   * fields. Such fields are carried as branded {@link Decimal} values,
   * which are plain strings at runtime to preserve arbitrary precision.
   * On the request path ObjectSerializer.serialize walks the instance with
   * JSON.stringify, which would quote a string and emit
   * `"weightKg":"12.345"` (a JSON string) instead of the spec-required
   * `"weightKg":12.345` (a JSON number). The serializer consults this set
   * (by runtime property name) to emit those fields unquoted via JSON.rawJSON,
   * preserving the full decimal text without a lossy Number() round-trip.
   * Empty when the model has no `type: number` no-format fields.
   */
  static readonly __decimalFields: ReadonlySet<string> = new Set([]);

  @Expose({ name: "clientIdFilter" })
  @Type(() => ApplicationServiceClientIDFilter)
  clientIdFilter?: ApplicationServiceClientIDFilter;
  @Expose({ name: "entityIdFilter" })
  @Type(() => ApplicationServiceEntityIDFilter)
  entityIdFilter?: ApplicationServiceEntityIDFilter;
  @Expose({ name: "nameFilter" })
  @Type(() => ApplicationServiceApplicationNameFilter)
  nameFilter?: ApplicationServiceApplicationNameFilter;
  @Expose({ name: "projectIdFilter" })
  @Type(() => ApplicationServiceProjectIDFilter)
  projectIdFilter?: ApplicationServiceProjectIDFilter;
  @Expose({ name: "stateFilter" })
  stateFilter?: ApplicationServiceApplicationState;
  @Expose({ name: "typeFilter" })
  typeFilter?: ApplicationServiceApplicationType;

  constructor(data?: Partial<ApplicationServiceApplicationSearchFilter>) {
    Object.assign(this, data);
    if (this.stateFilter != null) {
      const stateFilterValues = Object.values(
        ApplicationServiceApplicationState,
      ).filter(
        (v) =>
          typeof (
            ApplicationServiceApplicationState as Record<string, unknown>
          )[v as string] !== "number",
      );
      if (
        !(stateFilterValues as readonly unknown[]).includes(this.stateFilter)
      ) {
        throw new Error(
          `Unknown enum value for stateFilter: ${JSON.stringify(this.stateFilter)}. ` +
            `Expected one of [${stateFilterValues.map((v) => JSON.stringify(v)).join(", ")}].`,
        );
      }
    }
    if (this.typeFilter != null) {
      const typeFilterValues = Object.values(
        ApplicationServiceApplicationType,
      ).filter(
        (v) =>
          typeof (ApplicationServiceApplicationType as Record<string, unknown>)[
            v as string
          ] !== "number",
      );
      if (!(typeFilterValues as readonly unknown[]).includes(this.typeFilter)) {
        throw new Error(
          `Unknown enum value for typeFilter: ${JSON.stringify(this.typeFilter)}. ` +
            `Expected one of [${typeFilterValues.map((v) => JSON.stringify(v)).join(", ")}].`,
        );
      }
    }
  }

  /**
   * Value-equality across all declared fields. Two instances are equal when
   * every field deep-equals the other's. Arrays, plain objects, Sets, Maps,
   * Buffers and Date values are compared structurally; nested model fields
   * fall through to their own {@link equals} when present, otherwise to a
   * recursive structural compare. Mirrors the value-equality exposed by the
   * other SDKs (node-model-equality).
   */
  equals(other: unknown): boolean {
    if (this === other) {
      return true;
    }
    if (!(other instanceof ApplicationServiceApplicationSearchFilter)) {
      return false;
    }
    if (
      !ApplicationServiceApplicationSearchFilter.__deepEquals(
        this.clientIdFilter,
        (other as ApplicationServiceApplicationSearchFilter).clientIdFilter,
      )
    ) {
      return false;
    }
    if (
      !ApplicationServiceApplicationSearchFilter.__deepEquals(
        this.entityIdFilter,
        (other as ApplicationServiceApplicationSearchFilter).entityIdFilter,
      )
    ) {
      return false;
    }
    if (
      !ApplicationServiceApplicationSearchFilter.__deepEquals(
        this.nameFilter,
        (other as ApplicationServiceApplicationSearchFilter).nameFilter,
      )
    ) {
      return false;
    }
    if (
      !ApplicationServiceApplicationSearchFilter.__deepEquals(
        this.projectIdFilter,
        (other as ApplicationServiceApplicationSearchFilter).projectIdFilter,
      )
    ) {
      return false;
    }
    if (
      !ApplicationServiceApplicationSearchFilter.__deepEquals(
        this.stateFilter,
        (other as ApplicationServiceApplicationSearchFilter).stateFilter,
      )
    ) {
      return false;
    }
    if (
      !ApplicationServiceApplicationSearchFilter.__deepEquals(
        this.typeFilter,
        (other as ApplicationServiceApplicationSearchFilter).typeFilter,
      )
    ) {
      return false;
    }
    return true;
  }

  /**
   * Recursive structural comparison used by {@link equals}. Defers to a
   * nested value's own `equals` method when it exposes one (generated
   * models do), so equality stays value-based all the way down.
   */
  private static __deepEquals(a: unknown, b: unknown): boolean {
    if (a === b) {
      return true;
    }
    if (a == null || b == null) {
      return a === b;
    }
    if (
      typeof (a as { equals?: unknown }).equals === "function" &&
      a.constructor === b.constructor
    ) {
      return (a as { equals(o: unknown): boolean }).equals(b);
    }
    if (Buffer.isBuffer(a) && Buffer.isBuffer(b)) {
      return a.equals(b);
    }
    if (a instanceof Date && b instanceof Date) {
      return a.getTime() === b.getTime();
    }
    if (Array.isArray(a) && Array.isArray(b)) {
      if (a.length !== b.length) {
        return false;
      }
      return a.every((v, i) =>
        ApplicationServiceApplicationSearchFilter.__deepEquals(v, b[i]),
      );
    }
    if (a instanceof Set && b instanceof Set) {
      if (a.size !== b.size) {
        return false;
      }
      const bvals = [...b];
      return [...a].every((v) =>
        bvals.some((w) =>
          ApplicationServiceApplicationSearchFilter.__deepEquals(v, w),
        ),
      );
    }
    if (a instanceof Map && b instanceof Map) {
      if (a.size !== b.size) {
        return false;
      }
      for (const [k, v] of a) {
        if (
          !b.has(k) ||
          !ApplicationServiceApplicationSearchFilter.__deepEquals(v, b.get(k))
        ) {
          return false;
        }
      }
      return true;
    }
    if (typeof a === "object" && typeof b === "object") {
      const ar = a as Record<string, unknown>;
      const br = b as Record<string, unknown>;
      const ak = Object.keys(ar);
      const bk = Object.keys(br);
      if (ak.length !== bk.length) {
        return false;
      }
      return ak.every(
        (k) =>
          Object.prototype.hasOwnProperty.call(br, k) &&
          ApplicationServiceApplicationSearchFilter.__deepEquals(ar[k], br[k]),
      );
    }
    return false;
  }
}
