/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaSettingsServiceResourceOwnerType } from './BetaSettingsServiceResourceOwnerType.js';
import {
    BetaSettingsServiceResourceOwnerTypeFromJSON,
    BetaSettingsServiceResourceOwnerTypeFromJSONTyped,
    BetaSettingsServiceResourceOwnerTypeToJSON,
    BetaSettingsServiceResourceOwnerTypeToJSONTyped,
} from './BetaSettingsServiceResourceOwnerType.js';

/**
 * 
 * @export
 * @interface BetaSettingsServiceDomainSettings
 */
export interface BetaSettingsServiceDomainSettings {
    /**
     * 
     * @type {boolean}
     * @memberof BetaSettingsServiceDomainSettings
     */
    loginNameIncludesDomain?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BetaSettingsServiceDomainSettings
     */
    requireOrgDomainVerification?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BetaSettingsServiceDomainSettings
     */
    smtpSenderAddressMatchesInstanceDomain?: boolean;
    /**
     * 
     * @type {BetaSettingsServiceResourceOwnerType}
     * @memberof BetaSettingsServiceDomainSettings
     */
    resourceOwnerType?: BetaSettingsServiceResourceOwnerType;
}



/**
 * Check if a given object implements the BetaSettingsServiceDomainSettings interface.
 */
export function instanceOfBetaSettingsServiceDomainSettings(value: object): value is BetaSettingsServiceDomainSettings {
    return true;
}

export function BetaSettingsServiceDomainSettingsFromJSON(json: any): BetaSettingsServiceDomainSettings {
    return BetaSettingsServiceDomainSettingsFromJSONTyped(json, false);
}

export function BetaSettingsServiceDomainSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaSettingsServiceDomainSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'loginNameIncludesDomain': json['loginNameIncludesDomain'] == null ? undefined : json['loginNameIncludesDomain'],
        'requireOrgDomainVerification': json['requireOrgDomainVerification'] == null ? undefined : json['requireOrgDomainVerification'],
        'smtpSenderAddressMatchesInstanceDomain': json['smtpSenderAddressMatchesInstanceDomain'] == null ? undefined : json['smtpSenderAddressMatchesInstanceDomain'],
        'resourceOwnerType': json['resourceOwnerType'] == null ? undefined : BetaSettingsServiceResourceOwnerTypeFromJSON(json['resourceOwnerType']),
    };
}

export function BetaSettingsServiceDomainSettingsToJSON(json: any): BetaSettingsServiceDomainSettings {
    return BetaSettingsServiceDomainSettingsToJSONTyped(json, false);
}

export function BetaSettingsServiceDomainSettingsToJSONTyped(value?: BetaSettingsServiceDomainSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'loginNameIncludesDomain': value['loginNameIncludesDomain'],
        'requireOrgDomainVerification': value['requireOrgDomainVerification'],
        'smtpSenderAddressMatchesInstanceDomain': value['smtpSenderAddressMatchesInstanceDomain'],
        'resourceOwnerType': BetaSettingsServiceResourceOwnerTypeToJSON(value['resourceOwnerType']),
    };
}

