/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaSettingsServicePasswordComplexitySettings } from './BetaSettingsServicePasswordComplexitySettings.js';
import {
    BetaSettingsServicePasswordComplexitySettingsFromJSON,
    BetaSettingsServicePasswordComplexitySettingsFromJSONTyped,
    BetaSettingsServicePasswordComplexitySettingsToJSON,
    BetaSettingsServicePasswordComplexitySettingsToJSONTyped,
} from './BetaSettingsServicePasswordComplexitySettings.js';
import type { BetaSettingsServiceDetails } from './BetaSettingsServiceDetails.js';
import {
    BetaSettingsServiceDetailsFromJSON,
    BetaSettingsServiceDetailsFromJSONTyped,
    BetaSettingsServiceDetailsToJSON,
    BetaSettingsServiceDetailsToJSONTyped,
} from './BetaSettingsServiceDetails.js';

/**
 * 
 * @export
 * @interface BetaSettingsServiceGetPasswordComplexitySettingsResponse
 */
export interface BetaSettingsServiceGetPasswordComplexitySettingsResponse {
    /**
     * 
     * @type {BetaSettingsServiceDetails}
     * @memberof BetaSettingsServiceGetPasswordComplexitySettingsResponse
     */
    details?: BetaSettingsServiceDetails;
    /**
     * 
     * @type {BetaSettingsServicePasswordComplexitySettings}
     * @memberof BetaSettingsServiceGetPasswordComplexitySettingsResponse
     */
    settings?: BetaSettingsServicePasswordComplexitySettings;
}

/**
 * Check if a given object implements the BetaSettingsServiceGetPasswordComplexitySettingsResponse interface.
 */
export function instanceOfBetaSettingsServiceGetPasswordComplexitySettingsResponse(value: object): value is BetaSettingsServiceGetPasswordComplexitySettingsResponse {
    return true;
}

export function BetaSettingsServiceGetPasswordComplexitySettingsResponseFromJSON(json: any): BetaSettingsServiceGetPasswordComplexitySettingsResponse {
    return BetaSettingsServiceGetPasswordComplexitySettingsResponseFromJSONTyped(json, false);
}

export function BetaSettingsServiceGetPasswordComplexitySettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaSettingsServiceGetPasswordComplexitySettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'details': json['details'] == null ? undefined : BetaSettingsServiceDetailsFromJSON(json['details']),
        'settings': json['settings'] == null ? undefined : BetaSettingsServicePasswordComplexitySettingsFromJSON(json['settings']),
    };
}

export function BetaSettingsServiceGetPasswordComplexitySettingsResponseToJSON(json: any): BetaSettingsServiceGetPasswordComplexitySettingsResponse {
    return BetaSettingsServiceGetPasswordComplexitySettingsResponseToJSONTyped(json, false);
}

export function BetaSettingsServiceGetPasswordComplexitySettingsResponseToJSONTyped(value?: BetaSettingsServiceGetPasswordComplexitySettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': BetaSettingsServiceDetailsToJSON(value['details']),
        'settings': BetaSettingsServicePasswordComplexitySettingsToJSON(value['settings']),
    };
}

