// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

import { BetaOrganizationServiceOrgDomainFilter } from "./beta-organization-service-org-domain-filter.js";
import { BetaOrganizationServiceOrgIDFilter } from "./beta-organization-service-org-id-filter.js";
import { BetaOrganizationServiceOrgNameFilter } from "./beta-organization-service-org-name-filter.js";
import { BetaOrganizationServiceOrgStateFilter } from "./beta-organization-service-org-state-filter.js";
import { Expose, Type } from "class-transformer";

export class BetaOrganizationServiceOrganizationSearchFilter {
  /** @example null */
  @Expose({ name: "domainFilter" })
  @Type(() => BetaOrganizationServiceOrgDomainFilter)
  domainFilter?: BetaOrganizationServiceOrgDomainFilter;
  /** @example null */
  @Expose({ name: "idFilter" })
  @Type(() => BetaOrganizationServiceOrgIDFilter)
  idFilter?: BetaOrganizationServiceOrgIDFilter;
  /** @example null */
  @Expose({ name: "nameFilter" })
  @Type(() => BetaOrganizationServiceOrgNameFilter)
  nameFilter?: BetaOrganizationServiceOrgNameFilter;
  /** @example null */
  @Expose({ name: "stateFilter" })
  @Type(() => BetaOrganizationServiceOrgStateFilter)
  stateFilter?: BetaOrganizationServiceOrgStateFilter;

  constructor(data?: Partial<BetaOrganizationServiceOrganizationSearchFilter>) {
    Object.assign(this, data);
  }

  /**
   * Value-equality across all declared fields. Two instances are equal when
   * every field deep-equals the other's. Arrays, plain objects, Sets, Maps,
   * Buffers and Date values are compared structurally; nested model fields
   * fall through to their own {@link equals} when present, otherwise to a
   * recursive structural compare. Mirrors the value-equality exposed by the
   * other SDKs (node-model-equality).
   */
  equals(other: unknown): boolean {
    if (this === other) {
      return true;
    }
    if (!(other instanceof BetaOrganizationServiceOrganizationSearchFilter)) {
      return false;
    }
    if (
      !BetaOrganizationServiceOrganizationSearchFilter.__deepEquals(
        this.domainFilter,
        (other as BetaOrganizationServiceOrganizationSearchFilter).domainFilter,
      )
    ) {
      return false;
    }
    if (
      !BetaOrganizationServiceOrganizationSearchFilter.__deepEquals(
        this.idFilter,
        (other as BetaOrganizationServiceOrganizationSearchFilter).idFilter,
      )
    ) {
      return false;
    }
    if (
      !BetaOrganizationServiceOrganizationSearchFilter.__deepEquals(
        this.nameFilter,
        (other as BetaOrganizationServiceOrganizationSearchFilter).nameFilter,
      )
    ) {
      return false;
    }
    if (
      !BetaOrganizationServiceOrganizationSearchFilter.__deepEquals(
        this.stateFilter,
        (other as BetaOrganizationServiceOrganizationSearchFilter).stateFilter,
      )
    ) {
      return false;
    }
    return true;
  }

  /**
   * Recursive structural comparison used by {@link equals}. Defers to a
   * nested value's own `equals` method when it exposes one (generated
   * models do), so equality stays value-based all the way down.
   */
  private static __deepEquals(a: unknown, b: unknown): boolean {
    if (a === b) {
      return true;
    }
    if (a == null || b == null) {
      return a === b;
    }
    if (
      typeof (a as { equals?: unknown }).equals === "function" &&
      a.constructor === b.constructor
    ) {
      return (a as { equals(o: unknown): boolean }).equals(b);
    }
    if (Buffer.isBuffer(a) && Buffer.isBuffer(b)) {
      return a.equals(b);
    }
    if (a instanceof Date && b instanceof Date) {
      return a.getTime() === b.getTime();
    }
    if (Array.isArray(a) && Array.isArray(b)) {
      if (a.length !== b.length) {
        return false;
      }
      return a.every((v, i) =>
        BetaOrganizationServiceOrganizationSearchFilter.__deepEquals(v, b[i]),
      );
    }
    if (a instanceof Set && b instanceof Set) {
      if (a.size !== b.size) {
        return false;
      }
      const bvals = [...b];
      return [...a].every((v) =>
        bvals.some((w) =>
          BetaOrganizationServiceOrganizationSearchFilter.__deepEquals(v, w),
        ),
      );
    }
    if (a instanceof Map && b instanceof Map) {
      if (a.size !== b.size) {
        return false;
      }
      for (const [k, v] of a) {
        if (
          !b.has(k) ||
          !BetaOrganizationServiceOrganizationSearchFilter.__deepEquals(
            v,
            b.get(k),
          )
        ) {
          return false;
        }
      }
      return true;
    }
    if (typeof a === "object" && typeof b === "object") {
      const ar = a as Record<string, unknown>;
      const br = b as Record<string, unknown>;
      const ak = Object.keys(ar);
      const bk = Object.keys(br);
      if (ak.length !== bk.length) {
        return false;
      }
      return ak.every(
        (k) =>
          Object.prototype.hasOwnProperty.call(br, k) &&
          BetaOrganizationServiceOrganizationSearchFilter.__deepEquals(
            ar[k],
            br[k],
          ),
      );
    }
    return false;
  }
}
