/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaOrganizationServiceMetadata } from './beta-organization-service-metadata.js';
import {
    BetaOrganizationServiceMetadataFromJSON,
    BetaOrganizationServiceMetadataFromJSONTyped,
    BetaOrganizationServiceMetadataToJSON,
    BetaOrganizationServiceMetadataToJSONTyped,
} from './beta-organization-service-metadata.js';

/**
 * 
 * @export
 * @interface BetaOrganizationServiceSetOrganizationMetadataRequest
 */
export interface BetaOrganizationServiceSetOrganizationMetadataRequest {
    /**
     * Organization Id for the Organization doman to be verified.
     * @type {string}
     * @memberof BetaOrganizationServiceSetOrganizationMetadataRequest
     */
    organizationId?: string;
    /**
     * Metadata to set.
     * @type {Array<BetaOrganizationServiceMetadata>}
     * @memberof BetaOrganizationServiceSetOrganizationMetadataRequest
     */
    metadata?: Array<BetaOrganizationServiceMetadata>;
}

/**
 * Check if a given object implements the BetaOrganizationServiceSetOrganizationMetadataRequest interface.
 */
export function instanceOfBetaOrganizationServiceSetOrganizationMetadataRequest(value: object): value is BetaOrganizationServiceSetOrganizationMetadataRequest {
    return true;
}

export function BetaOrganizationServiceSetOrganizationMetadataRequestFromJSON(json: any): BetaOrganizationServiceSetOrganizationMetadataRequest {
    return BetaOrganizationServiceSetOrganizationMetadataRequestFromJSONTyped(json, false);
}

export function BetaOrganizationServiceSetOrganizationMetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaOrganizationServiceSetOrganizationMetadataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
        'metadata': json['metadata'] == null ? undefined : ((json['metadata'] as Array<any>).map(BetaOrganizationServiceMetadataFromJSON)),
    };
}

export function BetaOrganizationServiceSetOrganizationMetadataRequestToJSON(json: any): BetaOrganizationServiceSetOrganizationMetadataRequest {
    return BetaOrganizationServiceSetOrganizationMetadataRequestToJSONTyped(json, false);
}

export function BetaOrganizationServiceSetOrganizationMetadataRequestToJSONTyped(value?: BetaOrganizationServiceSetOrganizationMetadataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organizationId': value['organizationId'],
        'metadata': value['metadata'] == null ? undefined : ((value['metadata'] as Array<any>).map(BetaOrganizationServiceMetadataToJSON)),
    };
}

