/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaUserServiceListQuery } from './beta-user-service-list-query.js';
import {
    BetaUserServiceListQueryFromJSON,
    BetaUserServiceListQueryFromJSONTyped,
    BetaUserServiceListQueryToJSON,
    BetaUserServiceListQueryToJSONTyped,
} from './beta-user-service-list-query.js';
import type { BetaUserServiceSearchQuery } from './beta-user-service-search-query.js';
import {
    BetaUserServiceSearchQueryFromJSON,
    BetaUserServiceSearchQueryFromJSONTyped,
    BetaUserServiceSearchQueryToJSON,
    BetaUserServiceSearchQueryToJSONTyped,
} from './beta-user-service-search-query.js';
import type { BetaUserServiceUserFieldName } from './beta-user-service-user-field-name.js';
import {
    BetaUserServiceUserFieldNameFromJSON,
    BetaUserServiceUserFieldNameFromJSONTyped,
    BetaUserServiceUserFieldNameToJSON,
    BetaUserServiceUserFieldNameToJSONTyped,
} from './beta-user-service-user-field-name.js';

/**
 * 
 * @export
 * @interface BetaUserServiceListUsersRequest
 */
export interface BetaUserServiceListUsersRequest {
    /**
     * 
     * @type {BetaUserServiceListQuery}
     * @memberof BetaUserServiceListUsersRequest
     */
    query?: BetaUserServiceListQuery;
    /**
     * 
     * @type {BetaUserServiceUserFieldName}
     * @memberof BetaUserServiceListUsersRequest
     */
    sortingColumn?: BetaUserServiceUserFieldName;
    /**
     * criteria the client is looking for
     * @type {Array<BetaUserServiceSearchQuery>}
     * @memberof BetaUserServiceListUsersRequest
     */
    queries?: Array<BetaUserServiceSearchQuery>;
}



/**
 * Check if a given object implements the BetaUserServiceListUsersRequest interface.
 */
export function instanceOfBetaUserServiceListUsersRequest(value: object): value is BetaUserServiceListUsersRequest {
    return true;
}

export function BetaUserServiceListUsersRequestFromJSON(json: any): BetaUserServiceListUsersRequest {
    return BetaUserServiceListUsersRequestFromJSONTyped(json, false);
}

export function BetaUserServiceListUsersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaUserServiceListUsersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : BetaUserServiceListQueryFromJSON(json['query']),
        'sortingColumn': json['sortingColumn'] == null ? undefined : BetaUserServiceUserFieldNameFromJSON(json['sortingColumn']),
        'queries': json['queries'] == null ? undefined : ((json['queries'] as Array<any>).map(BetaUserServiceSearchQueryFromJSON)),
    };
}

export function BetaUserServiceListUsersRequestToJSON(json: any): BetaUserServiceListUsersRequest {
    return BetaUserServiceListUsersRequestToJSONTyped(json, false);
}

export function BetaUserServiceListUsersRequestToJSONTyped(value?: BetaUserServiceListUsersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': BetaUserServiceListQueryToJSON(value['query']),
        'sortingColumn': BetaUserServiceUserFieldNameToJSON(value['sortingColumn']),
        'queries': value['queries'] == null ? undefined : ((value['queries'] as Array<any>).map(BetaUserServiceSearchQueryToJSON)),
    };
}

