/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaFeatureServiceDetails } from './beta-feature-service-details.js';
import {
    BetaFeatureServiceDetailsFromJSON,
    BetaFeatureServiceDetailsFromJSONTyped,
    BetaFeatureServiceDetailsToJSON,
    BetaFeatureServiceDetailsToJSONTyped,
} from './beta-feature-service-details.js';

/**
 * 
 * @export
 * @interface BetaFeatureServiceGetOrganizationFeaturesResponse
 */
export interface BetaFeatureServiceGetOrganizationFeaturesResponse {
    /**
     * 
     * @type {BetaFeatureServiceDetails}
     * @memberof BetaFeatureServiceGetOrganizationFeaturesResponse
     */
    details?: BetaFeatureServiceDetails;
}

/**
 * Check if a given object implements the BetaFeatureServiceGetOrganizationFeaturesResponse interface.
 */
export function instanceOfBetaFeatureServiceGetOrganizationFeaturesResponse(value: object): value is BetaFeatureServiceGetOrganizationFeaturesResponse {
    return true;
}

export function BetaFeatureServiceGetOrganizationFeaturesResponseFromJSON(json: any): BetaFeatureServiceGetOrganizationFeaturesResponse {
    return BetaFeatureServiceGetOrganizationFeaturesResponseFromJSONTyped(json, false);
}

export function BetaFeatureServiceGetOrganizationFeaturesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaFeatureServiceGetOrganizationFeaturesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'details': json['details'] == null ? undefined : BetaFeatureServiceDetailsFromJSON(json['details']),
    };
}

export function BetaFeatureServiceGetOrganizationFeaturesResponseToJSON(json: any): BetaFeatureServiceGetOrganizationFeaturesResponse {
    return BetaFeatureServiceGetOrganizationFeaturesResponseToJSONTyped(json, false);
}

export function BetaFeatureServiceGetOrganizationFeaturesResponseToJSONTyped(value?: BetaFeatureServiceGetOrganizationFeaturesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': BetaFeatureServiceDetailsToJSON(value['details']),
    };
}

