/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BetaUserServiceListQuery
 */
export interface BetaUserServiceListQuery {
    /**
     * 
     * @type {any}
     * @memberof BetaUserServiceListQuery
     */
    offset?: any | null;
    /**
     * 
     * @type {number}
     * @memberof BetaUserServiceListQuery
     */
    limit?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BetaUserServiceListQuery
     */
    asc?: boolean;
}

/**
 * Check if a given object implements the BetaUserServiceListQuery interface.
 */
export function instanceOfBetaUserServiceListQuery(value: object): value is BetaUserServiceListQuery {
    return true;
}

export function BetaUserServiceListQueryFromJSON(json: any): BetaUserServiceListQuery {
    return BetaUserServiceListQueryFromJSONTyped(json, false);
}

export function BetaUserServiceListQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaUserServiceListQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['offset'] == null ? undefined : json['offset'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'asc': json['asc'] == null ? undefined : json['asc'],
    };
}

export function BetaUserServiceListQueryToJSON(json: any): BetaUserServiceListQuery {
    return BetaUserServiceListQueryToJSONTyped(json, false);
}

export function BetaUserServiceListQueryToJSONTyped(value?: BetaUserServiceListQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offset': value['offset'],
        'limit': value['limit'],
        'asc': value['asc'],
    };
}

