/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BetaUserServiceSetPhoneRequest
 */
export interface BetaUserServiceSetPhoneRequest {
    /**
     * 
     * @type {string}
     * @memberof BetaUserServiceSetPhoneRequest
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof BetaUserServiceSetPhoneRequest
     */
    phone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BetaUserServiceSetPhoneRequest
     */
    isVerified?: boolean;
    /**
     * 
     * @type {object}
     * @memberof BetaUserServiceSetPhoneRequest
     */
    returnCode?: object;
    /**
     * 
     * @type {object}
     * @memberof BetaUserServiceSetPhoneRequest
     */
    sendCode?: object;
}

/**
 * Check if a given object implements the BetaUserServiceSetPhoneRequest interface.
 */
export function instanceOfBetaUserServiceSetPhoneRequest(value: object): value is BetaUserServiceSetPhoneRequest {
    return true;
}

export function BetaUserServiceSetPhoneRequestFromJSON(json: any): BetaUserServiceSetPhoneRequest {
    return BetaUserServiceSetPhoneRequestFromJSONTyped(json, false);
}

export function BetaUserServiceSetPhoneRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaUserServiceSetPhoneRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'isVerified': json['isVerified'] == null ? undefined : json['isVerified'],
        'returnCode': json['returnCode'] == null ? undefined : json['returnCode'],
        'sendCode': json['sendCode'] == null ? undefined : json['sendCode'],
    };
}

export function BetaUserServiceSetPhoneRequestToJSON(json: any): BetaUserServiceSetPhoneRequest {
    return BetaUserServiceSetPhoneRequestToJSONTyped(json, false);
}

export function BetaUserServiceSetPhoneRequestToJSONTyped(value?: BetaUserServiceSetPhoneRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'phone': value['phone'],
        'isVerified': value['isVerified'],
        'returnCode': value['returnCode'],
        'sendCode': value['sendCode'],
    };
}

