/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AndQuery1 } from './AndQuery1.js';
import {
    instanceOfAndQuery1,
    AndQuery1FromJSON,
    AndQuery1FromJSONTyped,
    AndQuery1ToJSON,
} from './AndQuery1.js';
import type { DisplayNameQuery1 } from './DisplayNameQuery1.js';
import {
    instanceOfDisplayNameQuery1,
    DisplayNameQuery1FromJSON,
    DisplayNameQuery1FromJSONTyped,
    DisplayNameQuery1ToJSON,
} from './DisplayNameQuery1.js';
import type { EmailQuery1 } from './EmailQuery1.js';
import {
    instanceOfEmailQuery1,
    EmailQuery1FromJSON,
    EmailQuery1FromJSONTyped,
    EmailQuery1ToJSON,
} from './EmailQuery1.js';
import type { FirstNameQuery1 } from './FirstNameQuery1.js';
import {
    instanceOfFirstNameQuery1,
    FirstNameQuery1FromJSON,
    FirstNameQuery1FromJSONTyped,
    FirstNameQuery1ToJSON,
} from './FirstNameQuery1.js';
import type { InUserEmailsQuery1 } from './InUserEmailsQuery1.js';
import {
    instanceOfInUserEmailsQuery1,
    InUserEmailsQuery1FromJSON,
    InUserEmailsQuery1FromJSONTyped,
    InUserEmailsQuery1ToJSON,
} from './InUserEmailsQuery1.js';
import type { InUserIdsQuery1 } from './InUserIdsQuery1.js';
import {
    instanceOfInUserIdsQuery1,
    InUserIdsQuery1FromJSON,
    InUserIdsQuery1FromJSONTyped,
    InUserIdsQuery1ToJSON,
} from './InUserIdsQuery1.js';
import type { LastNameQuery1 } from './LastNameQuery1.js';
import {
    instanceOfLastNameQuery1,
    LastNameQuery1FromJSON,
    LastNameQuery1FromJSONTyped,
    LastNameQuery1ToJSON,
} from './LastNameQuery1.js';
import type { LoginNameQuery1 } from './LoginNameQuery1.js';
import {
    instanceOfLoginNameQuery1,
    LoginNameQuery1FromJSON,
    LoginNameQuery1FromJSONTyped,
    LoginNameQuery1ToJSON,
} from './LoginNameQuery1.js';
import type { NickNameQuery1 } from './NickNameQuery1.js';
import {
    instanceOfNickNameQuery1,
    NickNameQuery1FromJSON,
    NickNameQuery1FromJSONTyped,
    NickNameQuery1ToJSON,
} from './NickNameQuery1.js';
import type { NotQuery1 } from './NotQuery1.js';
import {
    instanceOfNotQuery1,
    NotQuery1FromJSON,
    NotQuery1FromJSONTyped,
    NotQuery1ToJSON,
} from './NotQuery1.js';
import type { OrQuery1 } from './OrQuery1.js';
import {
    instanceOfOrQuery1,
    OrQuery1FromJSON,
    OrQuery1FromJSONTyped,
    OrQuery1ToJSON,
} from './OrQuery1.js';
import type { OrganizationIdQuery1 } from './OrganizationIdQuery1.js';
import {
    instanceOfOrganizationIdQuery1,
    OrganizationIdQuery1FromJSON,
    OrganizationIdQuery1FromJSONTyped,
    OrganizationIdQuery1ToJSON,
} from './OrganizationIdQuery1.js';
import type { PhoneQuery1 } from './PhoneQuery1.js';
import {
    instanceOfPhoneQuery1,
    PhoneQuery1FromJSON,
    PhoneQuery1FromJSONTyped,
    PhoneQuery1ToJSON,
} from './PhoneQuery1.js';
import type { StateQuery2 } from './StateQuery2.js';
import {
    instanceOfStateQuery2,
    StateQuery2FromJSON,
    StateQuery2FromJSONTyped,
    StateQuery2ToJSON,
} from './StateQuery2.js';
import type { TypeQuery1 } from './TypeQuery1.js';
import {
    instanceOfTypeQuery1,
    TypeQuery1FromJSON,
    TypeQuery1FromJSONTyped,
    TypeQuery1ToJSON,
} from './TypeQuery1.js';
import type { UserNameQuery1 } from './UserNameQuery1.js';
import {
    instanceOfUserNameQuery1,
    UserNameQuery1FromJSON,
    UserNameQuery1FromJSONTyped,
    UserNameQuery1ToJSON,
} from './UserNameQuery1.js';

/**
 * @type BetaUserServiceSearchQuery
 * 
 * @export
 */
export type BetaUserServiceSearchQuery = AndQuery1 | DisplayNameQuery1 | EmailQuery1 | FirstNameQuery1 | InUserEmailsQuery1 | InUserIdsQuery1 | LastNameQuery1 | LoginNameQuery1 | NickNameQuery1 | NotQuery1 | OrQuery1 | OrganizationIdQuery1 | PhoneQuery1 | StateQuery2 | TypeQuery1 | UserNameQuery1;

export function BetaUserServiceSearchQueryFromJSON(json: any): BetaUserServiceSearchQuery {
    return BetaUserServiceSearchQueryFromJSONTyped(json, false);
}

export function BetaUserServiceSearchQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaUserServiceSearchQuery {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAndQuery1(json)) {
        return AndQuery1FromJSONTyped(json, true);
    }
    if (instanceOfDisplayNameQuery1(json)) {
        return DisplayNameQuery1FromJSONTyped(json, true);
    }
    if (instanceOfEmailQuery1(json)) {
        return EmailQuery1FromJSONTyped(json, true);
    }
    if (instanceOfFirstNameQuery1(json)) {
        return FirstNameQuery1FromJSONTyped(json, true);
    }
    if (instanceOfInUserEmailsQuery1(json)) {
        return InUserEmailsQuery1FromJSONTyped(json, true);
    }
    if (instanceOfInUserIdsQuery1(json)) {
        return InUserIdsQuery1FromJSONTyped(json, true);
    }
    if (instanceOfLastNameQuery1(json)) {
        return LastNameQuery1FromJSONTyped(json, true);
    }
    if (instanceOfLoginNameQuery1(json)) {
        return LoginNameQuery1FromJSONTyped(json, true);
    }
    if (instanceOfNickNameQuery1(json)) {
        return NickNameQuery1FromJSONTyped(json, true);
    }
    if (instanceOfNotQuery1(json)) {
        return NotQuery1FromJSONTyped(json, true);
    }
    if (instanceOfOrQuery1(json)) {
        return OrQuery1FromJSONTyped(json, true);
    }
    if (instanceOfOrganizationIdQuery1(json)) {
        return OrganizationIdQuery1FromJSONTyped(json, true);
    }
    if (instanceOfPhoneQuery1(json)) {
        return PhoneQuery1FromJSONTyped(json, true);
    }
    if (instanceOfStateQuery2(json)) {
        return StateQuery2FromJSONTyped(json, true);
    }
    if (instanceOfTypeQuery1(json)) {
        return TypeQuery1FromJSONTyped(json, true);
    }
    if (instanceOfUserNameQuery1(json)) {
        return UserNameQuery1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function BetaUserServiceSearchQueryToJSON(json: any): any {
    return BetaUserServiceSearchQueryToJSONTyped(json, false);
}

export function BetaUserServiceSearchQueryToJSONTyped(value?: BetaUserServiceSearchQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAndQuery1(value)) {
        return AndQuery1ToJSON(value as AndQuery1);
    }
    if (instanceOfDisplayNameQuery1(value)) {
        return DisplayNameQuery1ToJSON(value as DisplayNameQuery1);
    }
    if (instanceOfEmailQuery1(value)) {
        return EmailQuery1ToJSON(value as EmailQuery1);
    }
    if (instanceOfFirstNameQuery1(value)) {
        return FirstNameQuery1ToJSON(value as FirstNameQuery1);
    }
    if (instanceOfInUserEmailsQuery1(value)) {
        return InUserEmailsQuery1ToJSON(value as InUserEmailsQuery1);
    }
    if (instanceOfInUserIdsQuery1(value)) {
        return InUserIdsQuery1ToJSON(value as InUserIdsQuery1);
    }
    if (instanceOfLastNameQuery1(value)) {
        return LastNameQuery1ToJSON(value as LastNameQuery1);
    }
    if (instanceOfLoginNameQuery1(value)) {
        return LoginNameQuery1ToJSON(value as LoginNameQuery1);
    }
    if (instanceOfNickNameQuery1(value)) {
        return NickNameQuery1ToJSON(value as NickNameQuery1);
    }
    if (instanceOfNotQuery1(value)) {
        return NotQuery1ToJSON(value as NotQuery1);
    }
    if (instanceOfOrQuery1(value)) {
        return OrQuery1ToJSON(value as OrQuery1);
    }
    if (instanceOfOrganizationIdQuery1(value)) {
        return OrganizationIdQuery1ToJSON(value as OrganizationIdQuery1);
    }
    if (instanceOfPhoneQuery1(value)) {
        return PhoneQuery1ToJSON(value as PhoneQuery1);
    }
    if (instanceOfStateQuery2(value)) {
        return StateQuery2ToJSON(value as StateQuery2);
    }
    if (instanceOfTypeQuery1(value)) {
        return TypeQuery1ToJSON(value as TypeQuery1);
    }
    if (instanceOfUserNameQuery1(value)) {
        return UserNameQuery1ToJSON(value as UserNameQuery1);
    }

    return {};
}

