/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaOrganizationServiceAddHumanUserRequest } from './beta-organization-service-add-human-user-request.js';
import {
    BetaOrganizationServiceAddHumanUserRequestFromJSON,
    BetaOrganizationServiceAddHumanUserRequestFromJSONTyped,
    BetaOrganizationServiceAddHumanUserRequestToJSON,
    BetaOrganizationServiceAddHumanUserRequestToJSONTyped,
} from './beta-organization-service-add-human-user-request.js';

/**
 * The Admin for the newly created Organization.
 * @export
 * @interface BetaOrganizationServiceAdmin
 */
export interface BetaOrganizationServiceAdmin {
    /**
     * specify Organization Member Roles for the provided user (default is ORG_OWNER if roles are empty)
     * @type {Array<string>}
     * @memberof BetaOrganizationServiceAdmin
     */
    roles?: Array<string>;
    /**
     * 
     * @type {BetaOrganizationServiceAddHumanUserRequest}
     * @memberof BetaOrganizationServiceAdmin
     */
    human?: BetaOrganizationServiceAddHumanUserRequest;
    /**
     * 
     * @type {string}
     * @memberof BetaOrganizationServiceAdmin
     */
    userId?: string;
}

/**
 * Check if a given object implements the BetaOrganizationServiceAdmin interface.
 */
export function instanceOfBetaOrganizationServiceAdmin(value: object): value is BetaOrganizationServiceAdmin {
    return true;
}

export function BetaOrganizationServiceAdminFromJSON(json: any): BetaOrganizationServiceAdmin {
    return BetaOrganizationServiceAdminFromJSONTyped(json, false);
}

export function BetaOrganizationServiceAdminFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaOrganizationServiceAdmin {
    if (json == null) {
        return json;
    }
    return {
        
        'roles': json['roles'] == null ? undefined : json['roles'],
        'human': json['human'] == null ? undefined : BetaOrganizationServiceAddHumanUserRequestFromJSON(json['human']),
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function BetaOrganizationServiceAdminToJSON(json: any): BetaOrganizationServiceAdmin {
    return BetaOrganizationServiceAdminToJSONTyped(json, false);
}

export function BetaOrganizationServiceAdminToJSONTyped(value?: BetaOrganizationServiceAdmin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roles': value['roles'],
        'human': BetaOrganizationServiceAddHumanUserRequestToJSON(value['human']),
        'userId': value['userId'],
    };
}

