// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

export enum BetaAppServiceAPIAuthMethodType {
  APIAUTHMETHODTYPEBASIC = "API_AUTH_METHOD_TYPE_BASIC",
  APIAUTHMETHODTYPEPRIVATEKEYJWT = "API_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT",
}
