/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BetaFeatureServiceGetOrganizationFeaturesRequest
 */
export interface BetaFeatureServiceGetOrganizationFeaturesRequest {
    /**
     * 
     * @type {string}
     * @memberof BetaFeatureServiceGetOrganizationFeaturesRequest
     */
    organizationId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BetaFeatureServiceGetOrganizationFeaturesRequest
     */
    inheritance?: boolean;
}

/**
 * Check if a given object implements the BetaFeatureServiceGetOrganizationFeaturesRequest interface.
 */
export function instanceOfBetaFeatureServiceGetOrganizationFeaturesRequest(value: object): value is BetaFeatureServiceGetOrganizationFeaturesRequest {
    return true;
}

export function BetaFeatureServiceGetOrganizationFeaturesRequestFromJSON(json: any): BetaFeatureServiceGetOrganizationFeaturesRequest {
    return BetaFeatureServiceGetOrganizationFeaturesRequestFromJSONTyped(json, false);
}

export function BetaFeatureServiceGetOrganizationFeaturesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaFeatureServiceGetOrganizationFeaturesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
        'inheritance': json['inheritance'] == null ? undefined : json['inheritance'],
    };
}

export function BetaFeatureServiceGetOrganizationFeaturesRequestToJSON(json: any): BetaFeatureServiceGetOrganizationFeaturesRequest {
    return BetaFeatureServiceGetOrganizationFeaturesRequestToJSONTyped(json, false);
}

export function BetaFeatureServiceGetOrganizationFeaturesRequestToJSONTyped(value?: BetaFeatureServiceGetOrganizationFeaturesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organizationId': value['organizationId'],
        'inheritance': value['inheritance'],
    };
}

