/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RestAsync } from './RestAsync.js';
import {
    instanceOfRestAsync,
    RestAsyncFromJSON,
    RestAsyncFromJSONTyped,
    RestAsyncToJSON,
} from './RestAsync.js';
import type { RestCall } from './RestCall.js';
import {
    instanceOfRestCall,
    RestCallFromJSON,
    RestCallFromJSONTyped,
    RestCallToJSON,
} from './RestCall.js';
import type { RestWebhook } from './RestWebhook.js';
import {
    instanceOfRestWebhook,
    RestWebhookFromJSON,
    RestWebhookFromJSONTyped,
    RestWebhookToJSON,
} from './RestWebhook.js';

/**
 * @type BetaActionServiceTarget
 * 
 * @export
 */
export type BetaActionServiceTarget = RestAsync | RestCall | RestWebhook;

export function BetaActionServiceTargetFromJSON(json: any): BetaActionServiceTarget {
    return BetaActionServiceTargetFromJSONTyped(json, false);
}

export function BetaActionServiceTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaActionServiceTarget {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfRestAsync(json)) {
        return RestAsyncFromJSONTyped(json, true);
    }
    if (instanceOfRestCall(json)) {
        return RestCallFromJSONTyped(json, true);
    }
    if (instanceOfRestWebhook(json)) {
        return RestWebhookFromJSONTyped(json, true);
    }

    return {} as any;
}

export function BetaActionServiceTargetToJSON(json: any): any {
    return BetaActionServiceTargetToJSONTyped(json, false);
}

export function BetaActionServiceTargetToJSONTyped(value?: BetaActionServiceTarget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfRestAsync(value)) {
        return RestAsyncToJSON(value as RestAsync);
    }
    if (instanceOfRestCall(value)) {
        return RestCallToJSON(value as RestCall);
    }
    if (instanceOfRestWebhook(value)) {
        return RestWebhookToJSON(value as RestWebhook);
    }

    return {};
}

