/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ReturnCode10 } from './ReturnCode10.js';
import {
    instanceOfReturnCode10,
    ReturnCode10FromJSON,
    ReturnCode10FromJSONTyped,
    ReturnCode10ToJSON,
} from './ReturnCode10.js';
import type { SendCode8 } from './SendCode8.js';
import {
    instanceOfSendCode8,
    SendCode8FromJSON,
    SendCode8FromJSONTyped,
    SendCode8ToJSON,
} from './SendCode8.js';

/**
 * @type BetaUserServiceResendPhoneCodeRequest
 * 
 * @export
 */
export type BetaUserServiceResendPhoneCodeRequest = ReturnCode10 | SendCode8;

export function BetaUserServiceResendPhoneCodeRequestFromJSON(json: any): BetaUserServiceResendPhoneCodeRequest {
    return BetaUserServiceResendPhoneCodeRequestFromJSONTyped(json, false);
}

export function BetaUserServiceResendPhoneCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaUserServiceResendPhoneCodeRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfReturnCode10(json)) {
        return ReturnCode10FromJSONTyped(json, true);
    }
    if (instanceOfSendCode8(json)) {
        return SendCode8FromJSONTyped(json, true);
    }

    return {} as any;
}

export function BetaUserServiceResendPhoneCodeRequestToJSON(json: any): any {
    return BetaUserServiceResendPhoneCodeRequestToJSONTyped(json, false);
}

export function BetaUserServiceResendPhoneCodeRequestToJSONTyped(value?: BetaUserServiceResendPhoneCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfReturnCode10(value)) {
        return ReturnCode10ToJSON(value as ReturnCode10);
    }
    if (instanceOfSendCode8(value)) {
        return SendCode8ToJSON(value as SendCode8);
    }

    return {};
}

