/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BetaAuthorizationServiceCreateAuthorizationRequest
 */
export interface BetaAuthorizationServiceCreateAuthorizationRequest {
    /**
     * UserID is the ID of the user who should be granted the authorization.
     * @type {string}
     * @memberof BetaAuthorizationServiceCreateAuthorizationRequest
     */
    userId?: string;
    /**
     * Project ID is the ID of the project the user should be authorized for.
     * @type {string}
     * @memberof BetaAuthorizationServiceCreateAuthorizationRequest
     */
    projectId?: string;
    /**
     * OrganizationID is the ID of the organization on which the authorization should be created.
     *  The organization must either own the project or have a grant for the project.
     *  If omitted, the authorization is created on the projects organization.
     * @type {string}
     * @memberof BetaAuthorizationServiceCreateAuthorizationRequest
     */
    organizationId?: string | null;
    /**
     * RoleKeys are the keys of the roles the user should be granted.
     * @type {Array<string>}
     * @memberof BetaAuthorizationServiceCreateAuthorizationRequest
     */
    roleKeys?: Array<string>;
}

/**
 * Check if a given object implements the BetaAuthorizationServiceCreateAuthorizationRequest interface.
 */
export function instanceOfBetaAuthorizationServiceCreateAuthorizationRequest(value: object): value is BetaAuthorizationServiceCreateAuthorizationRequest {
    return true;
}

export function BetaAuthorizationServiceCreateAuthorizationRequestFromJSON(json: any): BetaAuthorizationServiceCreateAuthorizationRequest {
    return BetaAuthorizationServiceCreateAuthorizationRequestFromJSONTyped(json, false);
}

export function BetaAuthorizationServiceCreateAuthorizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaAuthorizationServiceCreateAuthorizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
        'roleKeys': json['roleKeys'] == null ? undefined : json['roleKeys'],
    };
}

export function BetaAuthorizationServiceCreateAuthorizationRequestToJSON(json: any): BetaAuthorizationServiceCreateAuthorizationRequest {
    return BetaAuthorizationServiceCreateAuthorizationRequestToJSONTyped(json, false);
}

export function BetaAuthorizationServiceCreateAuthorizationRequestToJSONTyped(value?: BetaAuthorizationServiceCreateAuthorizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'projectId': value['projectId'],
        'organizationId': value['organizationId'],
        'roleKeys': value['roleKeys'],
    };
}

