/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BetaUserServiceRegisterU2FRequest
 */
export interface BetaUserServiceRegisterU2FRequest {
    /**
     * 
     * @type {string}
     * @memberof BetaUserServiceRegisterU2FRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof BetaUserServiceRegisterU2FRequest
     */
    domain?: string;
}

/**
 * Check if a given object implements the BetaUserServiceRegisterU2FRequest interface.
 */
export function instanceOfBetaUserServiceRegisterU2FRequest(value: object): value is BetaUserServiceRegisterU2FRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function BetaUserServiceRegisterU2FRequestFromJSON(json: any): BetaUserServiceRegisterU2FRequest {
    return BetaUserServiceRegisterU2FRequestFromJSONTyped(json, false);
}

export function BetaUserServiceRegisterU2FRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaUserServiceRegisterU2FRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'domain': json['domain'] == null ? undefined : json['domain'],
    };
}

export function BetaUserServiceRegisterU2FRequestToJSON(json: any): BetaUserServiceRegisterU2FRequest {
    return BetaUserServiceRegisterU2FRequestToJSONTyped(json, false);
}

export function BetaUserServiceRegisterU2FRequestToJSONTyped(value?: BetaUserServiceRegisterU2FRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'domain': value['domain'],
    };
}

