/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ReturnCode11 } from './ReturnCode11.js';
import {
    instanceOfReturnCode11,
    ReturnCode11FromJSON,
    ReturnCode11FromJSONTyped,
    ReturnCode11ToJSON,
} from './ReturnCode11.js';
import type { SendLink2 } from './SendLink2.js';
import {
    instanceOfSendLink2,
    SendLink2FromJSON,
    SendLink2FromJSONTyped,
    SendLink2ToJSON,
} from './SendLink2.js';

/**
 * @type BetaUserServiceCreatePasskeyRegistrationLinkRequest
 * 
 * @export
 */
export type BetaUserServiceCreatePasskeyRegistrationLinkRequest = ReturnCode11 | SendLink2;

export function BetaUserServiceCreatePasskeyRegistrationLinkRequestFromJSON(json: any): BetaUserServiceCreatePasskeyRegistrationLinkRequest {
    return BetaUserServiceCreatePasskeyRegistrationLinkRequestFromJSONTyped(json, false);
}

export function BetaUserServiceCreatePasskeyRegistrationLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaUserServiceCreatePasskeyRegistrationLinkRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfReturnCode11(json)) {
        return ReturnCode11FromJSONTyped(json, true);
    }
    if (instanceOfSendLink2(json)) {
        return SendLink2FromJSONTyped(json, true);
    }

    return {} as any;
}

export function BetaUserServiceCreatePasskeyRegistrationLinkRequestToJSON(json: any): any {
    return BetaUserServiceCreatePasskeyRegistrationLinkRequestToJSONTyped(json, false);
}

export function BetaUserServiceCreatePasskeyRegistrationLinkRequestToJSONTyped(value?: BetaUserServiceCreatePasskeyRegistrationLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfReturnCode11(value)) {
        return ReturnCode11ToJSON(value as ReturnCode11);
    }
    if (instanceOfSendLink2(value)) {
        return SendLink2ToJSON(value as SendLink2);
    }

    return {};
}

