/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
 * @export
 * @interface BetaSessionServiceAny
 */
export interface BetaSessionServiceAny {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof BetaSessionServiceAny
     */
    type?: string;
    /**
     * 
     * @type {Blob}
     * @memberof BetaSessionServiceAny
     */
    value?: Blob;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BetaSessionServiceAny
     */
    debug?: { [key: string]: any; };
}

/**
 * Check if a given object implements the BetaSessionServiceAny interface.
 */
export function instanceOfBetaSessionServiceAny(value: object): value is BetaSessionServiceAny {
    return true;
}

export function BetaSessionServiceAnyFromJSON(json: any): BetaSessionServiceAny {
    return BetaSessionServiceAnyFromJSONTyped(json, false);
}

export function BetaSessionServiceAnyFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaSessionServiceAny {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
        'debug': json['debug'] == null ? undefined : json['debug'],
    };
}

export function BetaSessionServiceAnyToJSON(json: any): BetaSessionServiceAny {
    return BetaSessionServiceAnyToJSONTyped(json, false);
}

export function BetaSessionServiceAnyToJSONTyped(value?: BetaSessionServiceAny | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'value': value['value'],
        'debug': value['debug'],
    };
}

