/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BetaAuthorizationServiceUpdateAuthorizationRequest
 */
export interface BetaAuthorizationServiceUpdateAuthorizationRequest {
    /**
     * ID is the unique identifier of the authorization.
     * @type {string}
     * @memberof BetaAuthorizationServiceUpdateAuthorizationRequest
     */
    id?: string;
    /**
     * RoleKeys are the keys of the roles the user should be granted.
     *  Note that any role keys previously granted to the user and not present in the list will be revoked.
     * @type {Array<string>}
     * @memberof BetaAuthorizationServiceUpdateAuthorizationRequest
     */
    roleKeys?: Array<string>;
}

/**
 * Check if a given object implements the BetaAuthorizationServiceUpdateAuthorizationRequest interface.
 */
export function instanceOfBetaAuthorizationServiceUpdateAuthorizationRequest(value: object): value is BetaAuthorizationServiceUpdateAuthorizationRequest {
    return true;
}

export function BetaAuthorizationServiceUpdateAuthorizationRequestFromJSON(json: any): BetaAuthorizationServiceUpdateAuthorizationRequest {
    return BetaAuthorizationServiceUpdateAuthorizationRequestFromJSONTyped(json, false);
}

export function BetaAuthorizationServiceUpdateAuthorizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaAuthorizationServiceUpdateAuthorizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'roleKeys': json['roleKeys'] == null ? undefined : json['roleKeys'],
    };
}

export function BetaAuthorizationServiceUpdateAuthorizationRequestToJSON(json: any): BetaAuthorizationServiceUpdateAuthorizationRequest {
    return BetaAuthorizationServiceUpdateAuthorizationRequestToJSONTyped(json, false);
}

export function BetaAuthorizationServiceUpdateAuthorizationRequestToJSONTyped(value?: BetaAuthorizationServiceUpdateAuthorizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'roleKeys': value['roleKeys'],
    };
}

