// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

import { BetaUserServiceAndQuery } from "./beta-user-service-and-query.js";
import { BetaUserServiceDisplayNameQuery } from "./beta-user-service-display-name-query.js";
import { BetaUserServiceEmailQuery } from "./beta-user-service-email-query.js";
import { BetaUserServiceFirstNameQuery } from "./beta-user-service-first-name-query.js";
import { BetaUserServiceInUserEmailsQuery } from "./beta-user-service-in-user-emails-query.js";
import { BetaUserServiceInUserIDQuery } from "./beta-user-service-in-user-id-query.js";
import { BetaUserServiceLastNameQuery } from "./beta-user-service-last-name-query.js";
import { BetaUserServiceLoginNameQuery } from "./beta-user-service-login-name-query.js";
import { BetaUserServiceNickNameQuery } from "./beta-user-service-nick-name-query.js";
import { BetaUserServiceNotQuery } from "./beta-user-service-not-query.js";
import { BetaUserServiceOrQuery } from "./beta-user-service-or-query.js";
import { BetaUserServiceOrganizationIdQuery } from "./beta-user-service-organization-id-query.js";
import { BetaUserServicePhoneQuery } from "./beta-user-service-phone-query.js";
import { BetaUserServiceStateQuery } from "./beta-user-service-state-query.js";
import { BetaUserServiceTypeQuery } from "./beta-user-service-type-query.js";
import { BetaUserServiceUserNameQuery } from "./beta-user-service-user-name-query.js";
import { Expose, Type } from "class-transformer";
import { Email } from "../brand.js";

export class BetaUserServiceSearchQuery {
  /** @example null */
  @Expose({ name: "andQuery" })
  @Type(() => BetaUserServiceAndQuery)
  andQuery?: BetaUserServiceAndQuery;
  /** @example null */
  @Expose({ name: "displayNameQuery" })
  @Type(() => BetaUserServiceDisplayNameQuery)
  displayNameQuery?: BetaUserServiceDisplayNameQuery;
  /** @example null */
  @Expose({ name: "emailQuery" })
  @Type(() => BetaUserServiceEmailQuery)
  emailQuery?: BetaUserServiceEmailQuery;
  /** @example null */
  @Expose({ name: "firstNameQuery" })
  @Type(() => BetaUserServiceFirstNameQuery)
  firstNameQuery?: BetaUserServiceFirstNameQuery;
  /** @example null */
  @Expose({ name: "inUserEmailsQuery" })
  @Type(() => BetaUserServiceInUserEmailsQuery)
  inUserEmailsQuery?: BetaUserServiceInUserEmailsQuery;
  /** @example null */
  @Expose({ name: "inUserIdsQuery" })
  @Type(() => BetaUserServiceInUserIDQuery)
  inUserIdsQuery?: BetaUserServiceInUserIDQuery;
  /** @example null */
  @Expose({ name: "lastNameQuery" })
  @Type(() => BetaUserServiceLastNameQuery)
  lastNameQuery?: BetaUserServiceLastNameQuery;
  /** @example null */
  @Expose({ name: "loginNameQuery" })
  @Type(() => BetaUserServiceLoginNameQuery)
  loginNameQuery?: BetaUserServiceLoginNameQuery;
  /** @example null */
  @Expose({ name: "nickNameQuery" })
  @Type(() => BetaUserServiceNickNameQuery)
  nickNameQuery?: BetaUserServiceNickNameQuery;
  /** @example null */
  @Expose({ name: "notQuery" })
  @Type(() => BetaUserServiceNotQuery)
  notQuery?: BetaUserServiceNotQuery;
  /** @example null */
  @Expose({ name: "orQuery" })
  @Type(() => BetaUserServiceOrQuery)
  orQuery?: BetaUserServiceOrQuery;
  /** @example null */
  @Expose({ name: "organizationIdQuery" })
  @Type(() => BetaUserServiceOrganizationIdQuery)
  organizationIdQuery?: BetaUserServiceOrganizationIdQuery;
  /** @example null */
  @Expose({ name: "phoneQuery" })
  @Type(() => BetaUserServicePhoneQuery)
  phoneQuery?: BetaUserServicePhoneQuery;
  /** @example null */
  @Expose({ name: "stateQuery" })
  @Type(() => BetaUserServiceStateQuery)
  stateQuery?: BetaUserServiceStateQuery;
  /** @example null */
  @Expose({ name: "typeQuery" })
  @Type(() => BetaUserServiceTypeQuery)
  typeQuery?: BetaUserServiceTypeQuery;
  /** @example null */
  @Expose({ name: "userNameQuery" })
  @Type(() => BetaUserServiceUserNameQuery)
  userNameQuery?: BetaUserServiceUserNameQuery;

  constructor(data?: Partial<BetaUserServiceSearchQuery>) {
    Object.assign(this, data);
  }

  /**
   * Value-equality across all declared fields. Two instances are equal when
   * every field deep-equals the other's. Arrays, plain objects, Sets, Maps,
   * Buffers and Date values are compared structurally; nested model fields
   * fall through to their own {@link equals} when present, otherwise to a
   * recursive structural compare. Mirrors the value-equality exposed by the
   * other SDKs (node-model-equality).
   */
  equals(other: unknown): boolean {
    if (this === other) {
      return true;
    }
    if (!(other instanceof BetaUserServiceSearchQuery)) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.andQuery,
        (other as BetaUserServiceSearchQuery).andQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.displayNameQuery,
        (other as BetaUserServiceSearchQuery).displayNameQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.emailQuery,
        (other as BetaUserServiceSearchQuery).emailQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.firstNameQuery,
        (other as BetaUserServiceSearchQuery).firstNameQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.inUserEmailsQuery,
        (other as BetaUserServiceSearchQuery).inUserEmailsQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.inUserIdsQuery,
        (other as BetaUserServiceSearchQuery).inUserIdsQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.lastNameQuery,
        (other as BetaUserServiceSearchQuery).lastNameQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.loginNameQuery,
        (other as BetaUserServiceSearchQuery).loginNameQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.nickNameQuery,
        (other as BetaUserServiceSearchQuery).nickNameQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.notQuery,
        (other as BetaUserServiceSearchQuery).notQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.orQuery,
        (other as BetaUserServiceSearchQuery).orQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.organizationIdQuery,
        (other as BetaUserServiceSearchQuery).organizationIdQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.phoneQuery,
        (other as BetaUserServiceSearchQuery).phoneQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.stateQuery,
        (other as BetaUserServiceSearchQuery).stateQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.typeQuery,
        (other as BetaUserServiceSearchQuery).typeQuery,
      )
    ) {
      return false;
    }
    if (
      !BetaUserServiceSearchQuery.__deepEquals(
        this.userNameQuery,
        (other as BetaUserServiceSearchQuery).userNameQuery,
      )
    ) {
      return false;
    }
    return true;
  }

  /**
   * Recursive structural comparison used by {@link equals}. Defers to a
   * nested value's own `equals` method when it exposes one (generated
   * models do), so equality stays value-based all the way down.
   */
  private static __deepEquals(a: unknown, b: unknown): boolean {
    if (a === b) {
      return true;
    }
    if (a == null || b == null) {
      return a === b;
    }
    if (
      typeof (a as { equals?: unknown }).equals === "function" &&
      a.constructor === b.constructor
    ) {
      return (a as { equals(o: unknown): boolean }).equals(b);
    }
    if (Buffer.isBuffer(a) && Buffer.isBuffer(b)) {
      return a.equals(b);
    }
    if (a instanceof Date && b instanceof Date) {
      return a.getTime() === b.getTime();
    }
    if (Array.isArray(a) && Array.isArray(b)) {
      if (a.length !== b.length) {
        return false;
      }
      return a.every((v, i) =>
        BetaUserServiceSearchQuery.__deepEquals(v, b[i]),
      );
    }
    if (a instanceof Set && b instanceof Set) {
      if (a.size !== b.size) {
        return false;
      }
      const bvals = [...b];
      return [...a].every((v) =>
        bvals.some((w) => BetaUserServiceSearchQuery.__deepEquals(v, w)),
      );
    }
    if (a instanceof Map && b instanceof Map) {
      if (a.size !== b.size) {
        return false;
      }
      for (const [k, v] of a) {
        if (
          !b.has(k) ||
          !BetaUserServiceSearchQuery.__deepEquals(v, b.get(k))
        ) {
          return false;
        }
      }
      return true;
    }
    if (typeof a === "object" && typeof b === "object") {
      const ar = a as Record<string, unknown>;
      const br = b as Record<string, unknown>;
      const ak = Object.keys(ar);
      const bk = Object.keys(br);
      if (ak.length !== bk.length) {
        return false;
      }
      return ak.every(
        (k) =>
          Object.prototype.hasOwnProperty.call(br, k) &&
          BetaUserServiceSearchQuery.__deepEquals(ar[k], br[k]),
      );
    }
    return false;
  }
}
