/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaActionServiceTargetFieldName } from './BetaActionServiceTargetFieldName.js';
import {
    BetaActionServiceTargetFieldNameFromJSON,
    BetaActionServiceTargetFieldNameFromJSONTyped,
    BetaActionServiceTargetFieldNameToJSON,
    BetaActionServiceTargetFieldNameToJSONTyped,
} from './BetaActionServiceTargetFieldName.js';
import type { BetaActionServicePaginationRequest } from './BetaActionServicePaginationRequest.js';
import {
    BetaActionServicePaginationRequestFromJSON,
    BetaActionServicePaginationRequestFromJSONTyped,
    BetaActionServicePaginationRequestToJSON,
    BetaActionServicePaginationRequestToJSONTyped,
} from './BetaActionServicePaginationRequest.js';
import type { BetaActionServiceTargetSearchFilter } from './BetaActionServiceTargetSearchFilter.js';
import {
    BetaActionServiceTargetSearchFilterFromJSON,
    BetaActionServiceTargetSearchFilterFromJSONTyped,
    BetaActionServiceTargetSearchFilterToJSON,
    BetaActionServiceTargetSearchFilterToJSONTyped,
} from './BetaActionServiceTargetSearchFilter.js';

/**
 * 
 * @export
 * @interface BetaActionServiceListTargetsRequest
 */
export interface BetaActionServiceListTargetsRequest {
    /**
     * 
     * @type {BetaActionServicePaginationRequest}
     * @memberof BetaActionServiceListTargetsRequest
     */
    pagination?: BetaActionServicePaginationRequest;
    /**
     * 
     * @type {BetaActionServiceTargetFieldName}
     * @memberof BetaActionServiceListTargetsRequest
     */
    sortingColumn?: BetaActionServiceTargetFieldName;
    /**
     * Define the criteria to query for.
     * @type {Array<BetaActionServiceTargetSearchFilter>}
     * @memberof BetaActionServiceListTargetsRequest
     */
    filters?: Array<BetaActionServiceTargetSearchFilter>;
}



/**
 * Check if a given object implements the BetaActionServiceListTargetsRequest interface.
 */
export function instanceOfBetaActionServiceListTargetsRequest(value: object): value is BetaActionServiceListTargetsRequest {
    return true;
}

export function BetaActionServiceListTargetsRequestFromJSON(json: any): BetaActionServiceListTargetsRequest {
    return BetaActionServiceListTargetsRequestFromJSONTyped(json, false);
}

export function BetaActionServiceListTargetsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaActionServiceListTargetsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination': json['pagination'] == null ? undefined : BetaActionServicePaginationRequestFromJSON(json['pagination']),
        'sortingColumn': json['sortingColumn'] == null ? undefined : BetaActionServiceTargetFieldNameFromJSON(json['sortingColumn']),
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(BetaActionServiceTargetSearchFilterFromJSON)),
    };
}

export function BetaActionServiceListTargetsRequestToJSON(json: any): BetaActionServiceListTargetsRequest {
    return BetaActionServiceListTargetsRequestToJSONTyped(json, false);
}

export function BetaActionServiceListTargetsRequestToJSONTyped(value?: BetaActionServiceListTargetsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': BetaActionServicePaginationRequestToJSON(value['pagination']),
        'sortingColumn': BetaActionServiceTargetFieldNameToJSON(value['sortingColumn']),
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(BetaActionServiceTargetSearchFilterToJSON)),
    };
}

