/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BetaAppServiceOIDCTokenType = {
    OidcTokenTypeBearer: 'OIDC_TOKEN_TYPE_BEARER',
    OidcTokenTypeJwt: 'OIDC_TOKEN_TYPE_JWT',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type BetaAppServiceOIDCTokenType = typeof BetaAppServiceOIDCTokenType[keyof typeof BetaAppServiceOIDCTokenType];


export function instanceOfBetaAppServiceOIDCTokenType(value: any): boolean {
    for (const key in BetaAppServiceOIDCTokenType) {
        if (Object.prototype.hasOwnProperty.call(BetaAppServiceOIDCTokenType, key)) {
            if (BetaAppServiceOIDCTokenType[key as keyof typeof BetaAppServiceOIDCTokenType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BetaAppServiceOIDCTokenTypeFromJSON(json: any): BetaAppServiceOIDCTokenType {
    return BetaAppServiceOIDCTokenTypeFromJSONTyped(json, false);
}

export function BetaAppServiceOIDCTokenTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaAppServiceOIDCTokenType {
    return json as BetaAppServiceOIDCTokenType;
}

export function BetaAppServiceOIDCTokenTypeToJSON(value?: BetaAppServiceOIDCTokenType | null): any {
    return value as any;
}

export function BetaAppServiceOIDCTokenTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): BetaAppServiceOIDCTokenType {
    return value as BetaAppServiceOIDCTokenType;
}

