/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BetaUserServiceIDPIntent
 */
export interface BetaUserServiceIDPIntent {
    /**
     * 
     * @type {string}
     * @memberof BetaUserServiceIDPIntent
     */
    idpIntentId?: string;
    /**
     * 
     * @type {string}
     * @memberof BetaUserServiceIDPIntent
     */
    idpIntentToken?: string;
    /**
     * 
     * @type {string}
     * @memberof BetaUserServiceIDPIntent
     */
    userId?: string;
}

/**
 * Check if a given object implements the BetaUserServiceIDPIntent interface.
 */
export function instanceOfBetaUserServiceIDPIntent(value: object): value is BetaUserServiceIDPIntent {
    return true;
}

export function BetaUserServiceIDPIntentFromJSON(json: any): BetaUserServiceIDPIntent {
    return BetaUserServiceIDPIntentFromJSONTyped(json, false);
}

export function BetaUserServiceIDPIntentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaUserServiceIDPIntent {
    if (json == null) {
        return json;
    }
    return {
        
        'idpIntentId': json['idpIntentId'] == null ? undefined : json['idpIntentId'],
        'idpIntentToken': json['idpIntentToken'] == null ? undefined : json['idpIntentToken'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function BetaUserServiceIDPIntentToJSON(json: any): BetaUserServiceIDPIntent {
    return BetaUserServiceIDPIntentToJSONTyped(json, false);
}

export function BetaUserServiceIDPIntentToJSONTyped(value?: BetaUserServiceIDPIntent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idpIntentId': value['idpIntentId'],
        'idpIntentToken': value['idpIntentToken'],
        'userId': value['userId'],
    };
}

