/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaSessionServiceSession } from './beta-session-service-session.js';
import {
    BetaSessionServiceSessionFromJSON,
    BetaSessionServiceSessionFromJSONTyped,
    BetaSessionServiceSessionToJSON,
    BetaSessionServiceSessionToJSONTyped,
} from './beta-session-service-session.js';

/**
 * 
 * @export
 * @interface BetaSessionServiceGetSessionResponse
 */
export interface BetaSessionServiceGetSessionResponse {
    /**
     * 
     * @type {BetaSessionServiceSession}
     * @memberof BetaSessionServiceGetSessionResponse
     */
    session?: BetaSessionServiceSession;
}

/**
 * Check if a given object implements the BetaSessionServiceGetSessionResponse interface.
 */
export function instanceOfBetaSessionServiceGetSessionResponse(value: object): value is BetaSessionServiceGetSessionResponse {
    return true;
}

export function BetaSessionServiceGetSessionResponseFromJSON(json: any): BetaSessionServiceGetSessionResponse {
    return BetaSessionServiceGetSessionResponseFromJSONTyped(json, false);
}

export function BetaSessionServiceGetSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaSessionServiceGetSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'session': json['session'] == null ? undefined : BetaSessionServiceSessionFromJSON(json['session']),
    };
}

export function BetaSessionServiceGetSessionResponseToJSON(json: any): BetaSessionServiceGetSessionResponse {
    return BetaSessionServiceGetSessionResponseToJSONTyped(json, false);
}

export function BetaSessionServiceGetSessionResponseToJSONTyped(value?: BetaSessionServiceGetSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'session': BetaSessionServiceSessionToJSON(value['session']),
    };
}

