// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

export enum BetaUserServiceUserFieldName {
  USERFIELDNAMEUNSPECIFIED = "USER_FIELD_NAME_UNSPECIFIED",
  USERFIELDNAMEUSERNAME = "USER_FIELD_NAME_USER_NAME",
  USERFIELDNAMEFIRSTNAME = "USER_FIELD_NAME_FIRST_NAME",
  USERFIELDNAMELASTNAME = "USER_FIELD_NAME_LAST_NAME",
  USERFIELDNAMENICKNAME = "USER_FIELD_NAME_NICK_NAME",
  USERFIELDNAMEDISPLAYNAME = "USER_FIELD_NAME_DISPLAY_NAME",
  USERFIELDNAMEEMAIL = "USER_FIELD_NAME_EMAIL",
  USERFIELDNAMESTATE = "USER_FIELD_NAME_STATE",
  USERFIELDNAMETYPE = "USER_FIELD_NAME_TYPE",
  USERFIELDNAMECREATIONDATE = "USER_FIELD_NAME_CREATION_DATE",
}
