/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaUserServiceIDPIntent } from './beta-user-service-idp-intent.js';
import {
    BetaUserServiceIDPIntentFromJSON,
    BetaUserServiceIDPIntentFromJSONTyped,
    BetaUserServiceIDPIntentToJSON,
    BetaUserServiceIDPIntentToJSONTyped,
} from './beta-user-service-idp-intent.js';
import type { BetaUserServiceFormData } from './beta-user-service-form-data.js';
import {
    BetaUserServiceFormDataFromJSON,
    BetaUserServiceFormDataFromJSONTyped,
    BetaUserServiceFormDataToJSON,
    BetaUserServiceFormDataToJSONTyped,
} from './beta-user-service-form-data.js';
import type { BetaUserServiceDetails } from './beta-user-service-details.js';
import {
    BetaUserServiceDetailsFromJSON,
    BetaUserServiceDetailsFromJSONTyped,
    BetaUserServiceDetailsToJSON,
    BetaUserServiceDetailsToJSONTyped,
} from './beta-user-service-details.js';

/**
 * 
 * @export
 * @interface BetaUserServiceStartIdentityProviderIntentResponse
 */
export interface BetaUserServiceStartIdentityProviderIntentResponse {
    /**
     * 
     * @type {BetaUserServiceDetails}
     * @memberof BetaUserServiceStartIdentityProviderIntentResponse
     */
    details?: BetaUserServiceDetails;
    /**
     * URL to which the client should redirect
     * @type {string}
     * @memberof BetaUserServiceStartIdentityProviderIntentResponse
     */
    authUrl?: string;
    /**
     * 
     * @type {BetaUserServiceFormData}
     * @memberof BetaUserServiceStartIdentityProviderIntentResponse
     */
    formData?: BetaUserServiceFormData;
    /**
     * 
     * @type {BetaUserServiceIDPIntent}
     * @memberof BetaUserServiceStartIdentityProviderIntentResponse
     */
    idpIntent?: BetaUserServiceIDPIntent;
    /**
     * POST call information
     *  Deprecated: Use form_data instead
     * @type {string}
     * @memberof BetaUserServiceStartIdentityProviderIntentResponse
     */
    postForm?: string;
}

/**
 * Check if a given object implements the BetaUserServiceStartIdentityProviderIntentResponse interface.
 */
export function instanceOfBetaUserServiceStartIdentityProviderIntentResponse(value: object): value is BetaUserServiceStartIdentityProviderIntentResponse {
    return true;
}

export function BetaUserServiceStartIdentityProviderIntentResponseFromJSON(json: any): BetaUserServiceStartIdentityProviderIntentResponse {
    return BetaUserServiceStartIdentityProviderIntentResponseFromJSONTyped(json, false);
}

export function BetaUserServiceStartIdentityProviderIntentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaUserServiceStartIdentityProviderIntentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'details': json['details'] == null ? undefined : BetaUserServiceDetailsFromJSON(json['details']),
        'authUrl': json['authUrl'] == null ? undefined : json['authUrl'],
        'formData': json['formData'] == null ? undefined : BetaUserServiceFormDataFromJSON(json['formData']),
        'idpIntent': json['idpIntent'] == null ? undefined : BetaUserServiceIDPIntentFromJSON(json['idpIntent']),
        'postForm': json['postForm'] == null ? undefined : json['postForm'],
    };
}

export function BetaUserServiceStartIdentityProviderIntentResponseToJSON(json: any): BetaUserServiceStartIdentityProviderIntentResponse {
    return BetaUserServiceStartIdentityProviderIntentResponseToJSONTyped(json, false);
}

export function BetaUserServiceStartIdentityProviderIntentResponseToJSONTyped(value?: BetaUserServiceStartIdentityProviderIntentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': BetaUserServiceDetailsToJSON(value['details']),
        'authUrl': value['authUrl'],
        'formData': BetaUserServiceFormDataToJSON(value['formData']),
        'idpIntent': BetaUserServiceIDPIntentToJSON(value['idpIntent']),
        'postForm': value['postForm'],
    };
}

