/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaProjectServicePaginationResponse } from './beta-project-service-pagination-response.js';
import {
    BetaProjectServicePaginationResponseFromJSON,
    BetaProjectServicePaginationResponseFromJSONTyped,
    BetaProjectServicePaginationResponseToJSON,
    BetaProjectServicePaginationResponseToJSONTyped,
} from './beta-project-service-pagination-response.js';
import type { BetaProjectServiceProjectRole } from './beta-project-service-project-role.js';
import {
    BetaProjectServiceProjectRoleFromJSON,
    BetaProjectServiceProjectRoleFromJSONTyped,
    BetaProjectServiceProjectRoleToJSON,
    BetaProjectServiceProjectRoleToJSONTyped,
} from './beta-project-service-project-role.js';

/**
 * 
 * @export
 * @interface BetaProjectServiceListProjectRolesResponse
 */
export interface BetaProjectServiceListProjectRolesResponse {
    /**
     * 
     * @type {BetaProjectServicePaginationResponse}
     * @memberof BetaProjectServiceListProjectRolesResponse
     */
    pagination?: BetaProjectServicePaginationResponse;
    /**
     * 
     * @type {Array<BetaProjectServiceProjectRole>}
     * @memberof BetaProjectServiceListProjectRolesResponse
     */
    projectRoles?: Array<BetaProjectServiceProjectRole>;
}

/**
 * Check if a given object implements the BetaProjectServiceListProjectRolesResponse interface.
 */
export function instanceOfBetaProjectServiceListProjectRolesResponse(value: object): value is BetaProjectServiceListProjectRolesResponse {
    return true;
}

export function BetaProjectServiceListProjectRolesResponseFromJSON(json: any): BetaProjectServiceListProjectRolesResponse {
    return BetaProjectServiceListProjectRolesResponseFromJSONTyped(json, false);
}

export function BetaProjectServiceListProjectRolesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaProjectServiceListProjectRolesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination': json['pagination'] == null ? undefined : BetaProjectServicePaginationResponseFromJSON(json['pagination']),
        'projectRoles': json['projectRoles'] == null ? undefined : ((json['projectRoles'] as Array<any>).map(BetaProjectServiceProjectRoleFromJSON)),
    };
}

export function BetaProjectServiceListProjectRolesResponseToJSON(json: any): BetaProjectServiceListProjectRolesResponse {
    return BetaProjectServiceListProjectRolesResponseToJSONTyped(json, false);
}

export function BetaProjectServiceListProjectRolesResponseToJSONTyped(value?: BetaProjectServiceListProjectRolesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': BetaProjectServicePaginationResponseToJSON(value['pagination']),
        'projectRoles': value['projectRoles'] == null ? undefined : ((value['projectRoles'] as Array<any>).map(BetaProjectServiceProjectRoleToJSON)),
    };
}

