/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaUserServiceEmailQuery } from './BetaUserServiceEmailQuery.js';
import {
    BetaUserServiceEmailQueryFromJSON,
    BetaUserServiceEmailQueryFromJSONTyped,
    BetaUserServiceEmailQueryToJSON,
    BetaUserServiceEmailQueryToJSONTyped,
} from './BetaUserServiceEmailQuery.js';

/**
 * 
 * @export
 * @interface EmailQuery1
 */
export interface EmailQuery1 {
    /**
     * 
     * @type {BetaUserServiceEmailQuery}
     * @memberof EmailQuery1
     */
    emailQuery: BetaUserServiceEmailQuery;
}

/**
 * Check if a given object implements the EmailQuery1 interface.
 */
export function instanceOfEmailQuery1(value: object): value is EmailQuery1 {
    if (!('emailQuery' in value) || value['emailQuery'] === undefined) return false;
    return true;
}

export function EmailQuery1FromJSON(json: any): EmailQuery1 {
    return EmailQuery1FromJSONTyped(json, false);
}

export function EmailQuery1FromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailQuery1 {
    if (json == null) {
        return json;
    }
    return {
        
        'emailQuery': BetaUserServiceEmailQueryFromJSON(json['emailQuery']),
    };
}

export function EmailQuery1ToJSON(json: any): EmailQuery1 {
    return EmailQuery1ToJSONTyped(json, false);
}

export function EmailQuery1ToJSONTyped(value?: EmailQuery1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emailQuery': BetaUserServiceEmailQueryToJSON(value['emailQuery']),
    };
}

