/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface InstanceServicePaginationRequest
 */
export interface InstanceServicePaginationRequest {
    /**
     * Starting point for retrieval, in combination of offset used to query a set list of objects.
     * @type {any}
     * @memberof InstanceServicePaginationRequest
     */
    offset?: any | null;
    /**
     * limit is the maximum amount of objects returned. The default is set to 100
     *  with a maximum of 1000 in the runtime configuration.
     *  If the limit exceeds the maximum configured ZITADEL will throw an error.
     *  If no limit is present the default is taken.
     * @type {number}
     * @memberof InstanceServicePaginationRequest
     */
    limit?: number;
    /**
     * Asc is the sorting order. If true the list is sorted ascending, if false
     *  the list is sorted descending. The default is descending.
     * @type {boolean}
     * @memberof InstanceServicePaginationRequest
     */
    asc?: boolean;
}

/**
 * Check if a given object implements the InstanceServicePaginationRequest interface.
 */
export function instanceOfInstanceServicePaginationRequest(value: object): value is InstanceServicePaginationRequest {
    return true;
}

export function InstanceServicePaginationRequestFromJSON(json: any): InstanceServicePaginationRequest {
    return InstanceServicePaginationRequestFromJSONTyped(json, false);
}

export function InstanceServicePaginationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceServicePaginationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['offset'] == null ? undefined : json['offset'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'asc': json['asc'] == null ? undefined : json['asc'],
    };
}

export function InstanceServicePaginationRequestToJSON(json: any): InstanceServicePaginationRequest {
    return InstanceServicePaginationRequestToJSONTyped(json, false);
}

export function InstanceServicePaginationRequestToJSONTyped(value?: InstanceServicePaginationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offset': value['offset'],
        'limit': value['limit'],
        'asc': value['asc'],
    };
}

