/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const InstanceServiceFieldName = {
    FieldNameUnspecified: 'FIELD_NAME_UNSPECIFIED',
    FieldNameId: 'FIELD_NAME_ID',
    FieldNameName: 'FIELD_NAME_NAME',
    FieldNameCreationDate: 'FIELD_NAME_CREATION_DATE',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type InstanceServiceFieldName = typeof InstanceServiceFieldName[keyof typeof InstanceServiceFieldName];


export function instanceOfInstanceServiceFieldName(value: any): boolean {
    for (const key in InstanceServiceFieldName) {
        if (Object.prototype.hasOwnProperty.call(InstanceServiceFieldName, key)) {
            if (InstanceServiceFieldName[key as keyof typeof InstanceServiceFieldName] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InstanceServiceFieldNameFromJSON(json: any): InstanceServiceFieldName {
    return InstanceServiceFieldNameFromJSONTyped(json, false);
}

export function InstanceServiceFieldNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceServiceFieldName {
    return json as InstanceServiceFieldName;
}

export function InstanceServiceFieldNameToJSON(value?: InstanceServiceFieldName | null): any {
    return value as any;
}

export function InstanceServiceFieldNameToJSONTyped(value: any, ignoreDiscriminator: boolean): InstanceServiceFieldName {
    return value as InstanceServiceFieldName;
}

