/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { InstanceServiceInIDsFilter } from './instance-service-in-ids-filter.js';
import {
    InstanceServiceInIDsFilterFromJSON,
    InstanceServiceInIDsFilterFromJSONTyped,
    InstanceServiceInIDsFilterToJSON,
    InstanceServiceInIDsFilterToJSONTyped,
} from './instance-service-in-ids-filter.js';
import type { InstanceServiceCustomDomainsFilter } from './instance-service-custom-domains-filter.js';
import {
    InstanceServiceCustomDomainsFilterFromJSON,
    InstanceServiceCustomDomainsFilterFromJSONTyped,
    InstanceServiceCustomDomainsFilterToJSON,
    InstanceServiceCustomDomainsFilterToJSONTyped,
} from './instance-service-custom-domains-filter.js';

/**
 * 
 * @export
 * @interface InstanceServiceFilter
 */
export interface InstanceServiceFilter {
    /**
     * 
     * @type {InstanceServiceCustomDomainsFilter}
     * @memberof InstanceServiceFilter
     */
    customDomainsFilter?: InstanceServiceCustomDomainsFilter;
    /**
     * 
     * @type {InstanceServiceInIDsFilter}
     * @memberof InstanceServiceFilter
     */
    inIdsFilter?: InstanceServiceInIDsFilter;
}

/**
 * Check if a given object implements the InstanceServiceFilter interface.
 */
export function instanceOfInstanceServiceFilter(value: object): value is InstanceServiceFilter {
    return true;
}

export function InstanceServiceFilterFromJSON(json: any): InstanceServiceFilter {
    return InstanceServiceFilterFromJSONTyped(json, false);
}

export function InstanceServiceFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceServiceFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'customDomainsFilter': json['customDomainsFilter'] == null ? undefined : InstanceServiceCustomDomainsFilterFromJSON(json['customDomainsFilter']),
        'inIdsFilter': json['inIdsFilter'] == null ? undefined : InstanceServiceInIDsFilterFromJSON(json['inIdsFilter']),
    };
}

export function InstanceServiceFilterToJSON(json: any): InstanceServiceFilter {
    return InstanceServiceFilterToJSONTyped(json, false);
}

export function InstanceServiceFilterToJSONTyped(value?: InstanceServiceFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customDomainsFilter': InstanceServiceCustomDomainsFilterToJSON(value['customDomainsFilter']),
        'inIdsFilter': InstanceServiceInIDsFilterToJSON(value['inIdsFilter']),
    };
}

