/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface InstanceServiceInIDsFilter
 */
export interface InstanceServiceInIDsFilter {
    /**
     * Defines the ids to query for.
     * @type {Array<string>}
     * @memberof InstanceServiceInIDsFilter
     */
    ids?: Array<string>;
}

/**
 * Check if a given object implements the InstanceServiceInIDsFilter interface.
 */
export function instanceOfInstanceServiceInIDsFilter(value: object): value is InstanceServiceInIDsFilter {
    return true;
}

export function InstanceServiceInIDsFilterFromJSON(json: any): InstanceServiceInIDsFilter {
    return InstanceServiceInIDsFilterFromJSONTyped(json, false);
}

export function InstanceServiceInIDsFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceServiceInIDsFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
    };
}

export function InstanceServiceInIDsFilterToJSON(json: any): InstanceServiceInIDsFilter {
    return InstanceServiceInIDsFilterToJSONTyped(json, false);
}

export function InstanceServiceInIDsFilterToJSONTyped(value?: InstanceServiceInIDsFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
    };
}

