/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { InstanceServicePaginationResponse } from './instance-service-pagination-response.js';
import {
    InstanceServicePaginationResponseFromJSON,
    InstanceServicePaginationResponseFromJSONTyped,
    InstanceServicePaginationResponseToJSON,
    InstanceServicePaginationResponseToJSONTyped,
} from './instance-service-pagination-response.js';
import type { InstanceServiceTrustedDomain } from './instance-service-trusted-domain.js';
import {
    InstanceServiceTrustedDomainFromJSON,
    InstanceServiceTrustedDomainFromJSONTyped,
    InstanceServiceTrustedDomainToJSON,
    InstanceServiceTrustedDomainToJSONTyped,
} from './instance-service-trusted-domain.js';

/**
 * 
 * @export
 * @interface InstanceServiceListTrustedDomainsResponse
 */
export interface InstanceServiceListTrustedDomainsResponse {
    /**
     * The list of trusted domains matching the query.
     * @type {Array<InstanceServiceTrustedDomain>}
     * @memberof InstanceServiceListTrustedDomainsResponse
     */
    trustedDomain?: Array<InstanceServiceTrustedDomain>;
    /**
     * 
     * @type {InstanceServicePaginationResponse}
     * @memberof InstanceServiceListTrustedDomainsResponse
     */
    pagination?: InstanceServicePaginationResponse;
}

/**
 * Check if a given object implements the InstanceServiceListTrustedDomainsResponse interface.
 */
export function instanceOfInstanceServiceListTrustedDomainsResponse(value: object): value is InstanceServiceListTrustedDomainsResponse {
    return true;
}

export function InstanceServiceListTrustedDomainsResponseFromJSON(json: any): InstanceServiceListTrustedDomainsResponse {
    return InstanceServiceListTrustedDomainsResponseFromJSONTyped(json, false);
}

export function InstanceServiceListTrustedDomainsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceServiceListTrustedDomainsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'trustedDomain': json['trustedDomain'] == null ? undefined : ((json['trustedDomain'] as Array<any>).map(InstanceServiceTrustedDomainFromJSON)),
        'pagination': json['pagination'] == null ? undefined : InstanceServicePaginationResponseFromJSON(json['pagination']),
    };
}

export function InstanceServiceListTrustedDomainsResponseToJSON(json: any): InstanceServiceListTrustedDomainsResponse {
    return InstanceServiceListTrustedDomainsResponseToJSONTyped(json, false);
}

export function InstanceServiceListTrustedDomainsResponseToJSONTyped(value?: InstanceServiceListTrustedDomainsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trustedDomain': value['trustedDomain'] == null ? undefined : ((value['trustedDomain'] as Array<any>).map(InstanceServiceTrustedDomainToJSON)),
        'pagination': InstanceServicePaginationResponseToJSON(value['pagination']),
    };
}

