/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface InternalPermissionServiceProjectGrant
 */
export interface InternalPermissionServiceProjectGrant {
    /**
     * ProjectID is the unique identifier of the project the project grant belongs to.
     * @type {string}
     * @memberof InternalPermissionServiceProjectGrant
     */
    projectId?: string;
    /**
     * OrganizationID is the unique identifier of the organization the project was granted to
     *  and on which the administrator role should be granted.
     * @type {string}
     * @memberof InternalPermissionServiceProjectGrant
     */
    organizationId?: string;
}

/**
 * Check if a given object implements the InternalPermissionServiceProjectGrant interface.
 */
export function instanceOfInternalPermissionServiceProjectGrant(value: object): value is InternalPermissionServiceProjectGrant {
    return true;
}

export function InternalPermissionServiceProjectGrantFromJSON(json: any): InternalPermissionServiceProjectGrant {
    return InternalPermissionServiceProjectGrantFromJSONTyped(json, false);
}

export function InternalPermissionServiceProjectGrantFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalPermissionServiceProjectGrant {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
    };
}

export function InternalPermissionServiceProjectGrantToJSON(json: any): InternalPermissionServiceProjectGrant {
    return InternalPermissionServiceProjectGrantToJSONTyped(json, false);
}

export function InternalPermissionServiceProjectGrantToJSONTyped(value?: InternalPermissionServiceProjectGrant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'organizationId': value['organizationId'],
    };
}

