/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaUserServiceInUserEmailsQuery } from './BetaUserServiceInUserEmailsQuery.js';
import {
    BetaUserServiceInUserEmailsQueryFromJSON,
    BetaUserServiceInUserEmailsQueryFromJSONTyped,
    BetaUserServiceInUserEmailsQueryToJSON,
    BetaUserServiceInUserEmailsQueryToJSONTyped,
} from './BetaUserServiceInUserEmailsQuery.js';

/**
 * 
 * @export
 * @interface InUserEmailsQuery1
 */
export interface InUserEmailsQuery1 {
    /**
     * 
     * @type {BetaUserServiceInUserEmailsQuery}
     * @memberof InUserEmailsQuery1
     */
    inUserEmailsQuery: BetaUserServiceInUserEmailsQuery;
}

/**
 * Check if a given object implements the InUserEmailsQuery1 interface.
 */
export function instanceOfInUserEmailsQuery1(value: object): value is InUserEmailsQuery1 {
    if (!('inUserEmailsQuery' in value) || value['inUserEmailsQuery'] === undefined) return false;
    return true;
}

export function InUserEmailsQuery1FromJSON(json: any): InUserEmailsQuery1 {
    return InUserEmailsQuery1FromJSONTyped(json, false);
}

export function InUserEmailsQuery1FromJSONTyped(json: any, ignoreDiscriminator: boolean): InUserEmailsQuery1 {
    if (json == null) {
        return json;
    }
    return {
        
        'inUserEmailsQuery': BetaUserServiceInUserEmailsQueryFromJSON(json['inUserEmailsQuery']),
    };
}

export function InUserEmailsQuery1ToJSON(json: any): InUserEmailsQuery1 {
    return InUserEmailsQuery1ToJSONTyped(json, false);
}

export function InUserEmailsQuery1ToJSONTyped(value?: InUserEmailsQuery1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inUserEmailsQuery': BetaUserServiceInUserEmailsQueryToJSON(value['inUserEmailsQuery']),
    };
}

