/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaUserServiceInUserIDQuery } from './BetaUserServiceInUserIDQuery.js';
import {
    BetaUserServiceInUserIDQueryFromJSON,
    BetaUserServiceInUserIDQueryFromJSONTyped,
    BetaUserServiceInUserIDQueryToJSON,
    BetaUserServiceInUserIDQueryToJSONTyped,
} from './BetaUserServiceInUserIDQuery.js';

/**
 * 
 * @export
 * @interface InUserIdsQuery1
 */
export interface InUserIdsQuery1 {
    /**
     * 
     * @type {BetaUserServiceInUserIDQuery}
     * @memberof InUserIdsQuery1
     */
    inUserIdsQuery: BetaUserServiceInUserIDQuery;
}

/**
 * Check if a given object implements the InUserIdsQuery1 interface.
 */
export function instanceOfInUserIdsQuery1(value: object): value is InUserIdsQuery1 {
    if (!('inUserIdsQuery' in value) || value['inUserIdsQuery'] === undefined) return false;
    return true;
}

export function InUserIdsQuery1FromJSON(json: any): InUserIdsQuery1 {
    return InUserIdsQuery1FromJSONTyped(json, false);
}

export function InUserIdsQuery1FromJSONTyped(json: any, ignoreDiscriminator: boolean): InUserIdsQuery1 {
    if (json == null) {
        return json;
    }
    return {
        
        'inUserIdsQuery': BetaUserServiceInUserIDQueryFromJSON(json['inUserIdsQuery']),
    };
}

export function InUserIdsQuery1ToJSON(json: any): InUserIdsQuery1 {
    return InUserIdsQuery1ToJSONTyped(json, false);
}

export function InUserIdsQuery1ToJSONTyped(value?: InUserIdsQuery1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inUserIdsQuery': BetaUserServiceInUserIDQueryToJSON(value['inUserIdsQuery']),
    };
}

