/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IdentityProviderServiceGenericOIDCConfig } from './IdentityProviderServiceGenericOIDCConfig.js';
import {
    IdentityProviderServiceGenericOIDCConfigFromJSON,
    IdentityProviderServiceGenericOIDCConfigFromJSONTyped,
    IdentityProviderServiceGenericOIDCConfigToJSON,
    IdentityProviderServiceGenericOIDCConfigToJSONTyped,
} from './IdentityProviderServiceGenericOIDCConfig.js';
import type { IdentityProviderServiceAppleConfig } from './IdentityProviderServiceAppleConfig.js';
import {
    IdentityProviderServiceAppleConfigFromJSON,
    IdentityProviderServiceAppleConfigFromJSONTyped,
    IdentityProviderServiceAppleConfigToJSON,
    IdentityProviderServiceAppleConfigToJSONTyped,
} from './IdentityProviderServiceAppleConfig.js';
import type { IdentityProviderServiceGitLabSelfHostedConfig } from './IdentityProviderServiceGitLabSelfHostedConfig.js';
import {
    IdentityProviderServiceGitLabSelfHostedConfigFromJSON,
    IdentityProviderServiceGitLabSelfHostedConfigFromJSONTyped,
    IdentityProviderServiceGitLabSelfHostedConfigToJSON,
    IdentityProviderServiceGitLabSelfHostedConfigToJSONTyped,
} from './IdentityProviderServiceGitLabSelfHostedConfig.js';
import type { IdentityProviderServiceGitLabConfig } from './IdentityProviderServiceGitLabConfig.js';
import {
    IdentityProviderServiceGitLabConfigFromJSON,
    IdentityProviderServiceGitLabConfigFromJSONTyped,
    IdentityProviderServiceGitLabConfigToJSON,
    IdentityProviderServiceGitLabConfigToJSONTyped,
} from './IdentityProviderServiceGitLabConfig.js';
import type { IdentityProviderServiceJWTConfig } from './IdentityProviderServiceJWTConfig.js';
import {
    IdentityProviderServiceJWTConfigFromJSON,
    IdentityProviderServiceJWTConfigFromJSONTyped,
    IdentityProviderServiceJWTConfigToJSON,
    IdentityProviderServiceJWTConfigToJSONTyped,
} from './IdentityProviderServiceJWTConfig.js';
import type { IdentityProviderServiceGitHubConfig } from './IdentityProviderServiceGitHubConfig.js';
import {
    IdentityProviderServiceGitHubConfigFromJSON,
    IdentityProviderServiceGitHubConfigFromJSONTyped,
    IdentityProviderServiceGitHubConfigToJSON,
    IdentityProviderServiceGitHubConfigToJSONTyped,
} from './IdentityProviderServiceGitHubConfig.js';
import type { IdentityProviderServiceGoogleConfig } from './IdentityProviderServiceGoogleConfig.js';
import {
    IdentityProviderServiceGoogleConfigFromJSON,
    IdentityProviderServiceGoogleConfigFromJSONTyped,
    IdentityProviderServiceGoogleConfigToJSON,
    IdentityProviderServiceGoogleConfigToJSONTyped,
} from './IdentityProviderServiceGoogleConfig.js';
import type { IdentityProviderServiceSAMLConfig } from './IdentityProviderServiceSAMLConfig.js';
import {
    IdentityProviderServiceSAMLConfigFromJSON,
    IdentityProviderServiceSAMLConfigFromJSONTyped,
    IdentityProviderServiceSAMLConfigToJSON,
    IdentityProviderServiceSAMLConfigToJSONTyped,
} from './IdentityProviderServiceSAMLConfig.js';
import type { IdentityProviderServiceGitHubEnterpriseServerConfig } from './IdentityProviderServiceGitHubEnterpriseServerConfig.js';
import {
    IdentityProviderServiceGitHubEnterpriseServerConfigFromJSON,
    IdentityProviderServiceGitHubEnterpriseServerConfigFromJSONTyped,
    IdentityProviderServiceGitHubEnterpriseServerConfigToJSON,
    IdentityProviderServiceGitHubEnterpriseServerConfigToJSONTyped,
} from './IdentityProviderServiceGitHubEnterpriseServerConfig.js';
import type { IdentityProviderServiceAzureADTenantType } from './IdentityProviderServiceAzureADTenantType.js';
import {
    IdentityProviderServiceAzureADTenantTypeFromJSON,
    IdentityProviderServiceAzureADTenantTypeFromJSONTyped,
    IdentityProviderServiceAzureADTenantTypeToJSON,
    IdentityProviderServiceAzureADTenantTypeToJSONTyped,
} from './IdentityProviderServiceAzureADTenantType.js';
import type { IdentityProviderServiceLDAPConfig } from './IdentityProviderServiceLDAPConfig.js';
import {
    IdentityProviderServiceLDAPConfigFromJSON,
    IdentityProviderServiceLDAPConfigFromJSONTyped,
    IdentityProviderServiceLDAPConfigToJSON,
    IdentityProviderServiceLDAPConfigToJSONTyped,
} from './IdentityProviderServiceLDAPConfig.js';
import type { IdentityProviderServiceAzureADConfig } from './IdentityProviderServiceAzureADConfig.js';
import {
    IdentityProviderServiceAzureADConfigFromJSON,
    IdentityProviderServiceAzureADConfigFromJSONTyped,
    IdentityProviderServiceAzureADConfigToJSON,
    IdentityProviderServiceAzureADConfigToJSONTyped,
} from './IdentityProviderServiceAzureADConfig.js';
import type { IdentityProviderServiceOAuthConfig } from './IdentityProviderServiceOAuthConfig.js';
import {
    IdentityProviderServiceOAuthConfigFromJSON,
    IdentityProviderServiceOAuthConfigFromJSONTyped,
    IdentityProviderServiceOAuthConfigToJSON,
    IdentityProviderServiceOAuthConfigToJSONTyped,
} from './IdentityProviderServiceOAuthConfig.js';

/**
 * 
 * @export
 * @interface NoOp200Response
 */
export interface NoOp200Response {
    /**
     * 
     * @type {IdentityProviderServiceAppleConfig}
     * @memberof NoOp200Response
     */
    _8441420f_0f12_4dcb_850c_018df092eac6?: IdentityProviderServiceAppleConfig;
    /**
     * 
     * @type {IdentityProviderServiceAzureADConfig}
     * @memberof NoOp200Response
     */
    c649d0dc_722e_4d8f_a9d5_b66697477bdf?: IdentityProviderServiceAzureADConfig;
    /**
     * 
     * @type {IdentityProviderServiceAzureADTenantType}
     * @memberof NoOp200Response
     */
    a8fc9e9c_1722_45ea_b1db_d8d488cb7a73?: IdentityProviderServiceAzureADTenantType;
    /**
     * 
     * @type {IdentityProviderServiceGenericOIDCConfig}
     * @memberof NoOp200Response
     */
    _4a6eecea_4e11_4448_99a7_e62eacf0f00e?: IdentityProviderServiceGenericOIDCConfig;
    /**
     * 
     * @type {IdentityProviderServiceGitHubConfig}
     * @memberof NoOp200Response
     */
    d003c137_9066_4dab_b87a_f427f3569ecb?: IdentityProviderServiceGitHubConfig;
    /**
     * 
     * @type {IdentityProviderServiceGitHubEnterpriseServerConfig}
     * @memberof NoOp200Response
     */
    _0b5bc982_57a1_495e_a25d_7774c0ada464?: IdentityProviderServiceGitHubEnterpriseServerConfig;
    /**
     * 
     * @type {IdentityProviderServiceGitLabConfig}
     * @memberof NoOp200Response
     */
    aa233ae4_8316_4f3d_90c4_2355713c7829?: IdentityProviderServiceGitLabConfig;
    /**
     * 
     * @type {IdentityProviderServiceGitLabSelfHostedConfig}
     * @memberof NoOp200Response
     */
    _6b121e92_2e75_4bb6_ae63_79465b115116?: IdentityProviderServiceGitLabSelfHostedConfig;
    /**
     * 
     * @type {IdentityProviderServiceGoogleConfig}
     * @memberof NoOp200Response
     */
    d46c89de_23af_4ee4_9f8c_1af4e3f807ad?: IdentityProviderServiceGoogleConfig;
    /**
     * 
     * @type {IdentityProviderServiceJWTConfig}
     * @memberof NoOp200Response
     */
    e67c5d6b_04fe_448a_87f1_51211266e6a2?: IdentityProviderServiceJWTConfig;
    /**
     * 
     * @type {IdentityProviderServiceLDAPConfig}
     * @memberof NoOp200Response
     */
    fbb8d0c3_45bc_4c00_a78e_0b09da1dd662?: IdentityProviderServiceLDAPConfig;
    /**
     * 
     * @type {IdentityProviderServiceOAuthConfig}
     * @memberof NoOp200Response
     */
    dc49af89_1cfc_4f1c_b6ab_5b4a49223de2?: IdentityProviderServiceOAuthConfig;
    /**
     * 
     * @type {IdentityProviderServiceSAMLConfig}
     * @memberof NoOp200Response
     */
    c14fad73_15be_46c8_9763_7f7e5c31379c?: IdentityProviderServiceSAMLConfig;
}



/**
 * Check if a given object implements the NoOp200Response interface.
 */
export function instanceOfNoOp200Response(value: object): value is NoOp200Response {
    return true;
}

export function NoOp200ResponseFromJSON(json: any): NoOp200Response {
    return NoOp200ResponseFromJSONTyped(json, false);
}

export function NoOp200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoOp200Response {
    if (json == null) {
        return json;
    }
    return {
        
        '_8441420f_0f12_4dcb_850c_018df092eac6': json['8441420f-0f12-4dcb-850c-018df092eac6'] == null ? undefined : IdentityProviderServiceAppleConfigFromJSON(json['8441420f-0f12-4dcb-850c-018df092eac6']),
        'c649d0dc_722e_4d8f_a9d5_b66697477bdf': json['c649d0dc-722e-4d8f-a9d5-b66697477bdf'] == null ? undefined : IdentityProviderServiceAzureADConfigFromJSON(json['c649d0dc-722e-4d8f-a9d5-b66697477bdf']),
        'a8fc9e9c_1722_45ea_b1db_d8d488cb7a73': json['a8fc9e9c-1722-45ea-b1db-d8d488cb7a73'] == null ? undefined : IdentityProviderServiceAzureADTenantTypeFromJSON(json['a8fc9e9c-1722-45ea-b1db-d8d488cb7a73']),
        '_4a6eecea_4e11_4448_99a7_e62eacf0f00e': json['4a6eecea-4e11-4448-99a7-e62eacf0f00e'] == null ? undefined : IdentityProviderServiceGenericOIDCConfigFromJSON(json['4a6eecea-4e11-4448-99a7-e62eacf0f00e']),
        'd003c137_9066_4dab_b87a_f427f3569ecb': json['d003c137-9066-4dab-b87a-f427f3569ecb'] == null ? undefined : IdentityProviderServiceGitHubConfigFromJSON(json['d003c137-9066-4dab-b87a-f427f3569ecb']),
        '_0b5bc982_57a1_495e_a25d_7774c0ada464': json['0b5bc982-57a1-495e-a25d-7774c0ada464'] == null ? undefined : IdentityProviderServiceGitHubEnterpriseServerConfigFromJSON(json['0b5bc982-57a1-495e-a25d-7774c0ada464']),
        'aa233ae4_8316_4f3d_90c4_2355713c7829': json['aa233ae4-8316-4f3d-90c4-2355713c7829'] == null ? undefined : IdentityProviderServiceGitLabConfigFromJSON(json['aa233ae4-8316-4f3d-90c4-2355713c7829']),
        '_6b121e92_2e75_4bb6_ae63_79465b115116': json['6b121e92-2e75-4bb6-ae63-79465b115116'] == null ? undefined : IdentityProviderServiceGitLabSelfHostedConfigFromJSON(json['6b121e92-2e75-4bb6-ae63-79465b115116']),
        'd46c89de_23af_4ee4_9f8c_1af4e3f807ad': json['d46c89de-23af-4ee4-9f8c-1af4e3f807ad'] == null ? undefined : IdentityProviderServiceGoogleConfigFromJSON(json['d46c89de-23af-4ee4-9f8c-1af4e3f807ad']),
        'e67c5d6b_04fe_448a_87f1_51211266e6a2': json['e67c5d6b-04fe-448a-87f1-51211266e6a2'] == null ? undefined : IdentityProviderServiceJWTConfigFromJSON(json['e67c5d6b-04fe-448a-87f1-51211266e6a2']),
        'fbb8d0c3_45bc_4c00_a78e_0b09da1dd662': json['fbb8d0c3-45bc-4c00-a78e-0b09da1dd662'] == null ? undefined : IdentityProviderServiceLDAPConfigFromJSON(json['fbb8d0c3-45bc-4c00-a78e-0b09da1dd662']),
        'dc49af89_1cfc_4f1c_b6ab_5b4a49223de2': json['dc49af89-1cfc-4f1c-b6ab-5b4a49223de2'] == null ? undefined : IdentityProviderServiceOAuthConfigFromJSON(json['dc49af89-1cfc-4f1c-b6ab-5b4a49223de2']),
        'c14fad73_15be_46c8_9763_7f7e5c31379c': json['c14fad73-15be-46c8-9763-7f7e5c31379c'] == null ? undefined : IdentityProviderServiceSAMLConfigFromJSON(json['c14fad73-15be-46c8-9763-7f7e5c31379c']),
    };
}

export function NoOp200ResponseToJSON(json: any): NoOp200Response {
    return NoOp200ResponseToJSONTyped(json, false);
}

export function NoOp200ResponseToJSONTyped(value?: NoOp200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '8441420f-0f12-4dcb-850c-018df092eac6': IdentityProviderServiceAppleConfigToJSON(value['_8441420f_0f12_4dcb_850c_018df092eac6']),
        'c649d0dc-722e-4d8f-a9d5-b66697477bdf': IdentityProviderServiceAzureADConfigToJSON(value['c649d0dc_722e_4d8f_a9d5_b66697477bdf']),
        'a8fc9e9c-1722-45ea-b1db-d8d488cb7a73': IdentityProviderServiceAzureADTenantTypeToJSON(value['a8fc9e9c_1722_45ea_b1db_d8d488cb7a73']),
        '4a6eecea-4e11-4448-99a7-e62eacf0f00e': IdentityProviderServiceGenericOIDCConfigToJSON(value['_4a6eecea_4e11_4448_99a7_e62eacf0f00e']),
        'd003c137-9066-4dab-b87a-f427f3569ecb': IdentityProviderServiceGitHubConfigToJSON(value['d003c137_9066_4dab_b87a_f427f3569ecb']),
        '0b5bc982-57a1-495e-a25d-7774c0ada464': IdentityProviderServiceGitHubEnterpriseServerConfigToJSON(value['_0b5bc982_57a1_495e_a25d_7774c0ada464']),
        'aa233ae4-8316-4f3d-90c4-2355713c7829': IdentityProviderServiceGitLabConfigToJSON(value['aa233ae4_8316_4f3d_90c4_2355713c7829']),
        '6b121e92-2e75-4bb6-ae63-79465b115116': IdentityProviderServiceGitLabSelfHostedConfigToJSON(value['_6b121e92_2e75_4bb6_ae63_79465b115116']),
        'd46c89de-23af-4ee4-9f8c-1af4e3f807ad': IdentityProviderServiceGoogleConfigToJSON(value['d46c89de_23af_4ee4_9f8c_1af4e3f807ad']),
        'e67c5d6b-04fe-448a-87f1-51211266e6a2': IdentityProviderServiceJWTConfigToJSON(value['e67c5d6b_04fe_448a_87f1_51211266e6a2']),
        'fbb8d0c3-45bc-4c00-a78e-0b09da1dd662': IdentityProviderServiceLDAPConfigToJSON(value['fbb8d0c3_45bc_4c00_a78e_0b09da1dd662']),
        'dc49af89-1cfc-4f1c-b6ab-5b4a49223de2': IdentityProviderServiceOAuthConfigToJSON(value['dc49af89_1cfc_4f1c_b6ab_5b4a49223de2']),
        'c14fad73-15be-46c8-9763-7f7e5c31379c': IdentityProviderServiceSAMLConfigToJSON(value['c14fad73_15be_46c8_9763_7f7e5c31379c']),
    };
}

