/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganizationServiceGenerateOrganizationDomainValidationResponse
 */
export interface OrganizationServiceGenerateOrganizationDomainValidationResponse {
    /**
     * Token is a verification token that needs to be added to the DNS records or as a file to the webserver.
     *  Zitadel will check for this token to verify the domain.
     * @type {string}
     * @memberof OrganizationServiceGenerateOrganizationDomainValidationResponse
     */
    token?: string;
    /**
     * URL is the location where the token needs to be placed for HTTP challenge.
     * @type {string}
     * @memberof OrganizationServiceGenerateOrganizationDomainValidationResponse
     */
    url?: string;
}

/**
 * Check if a given object implements the OrganizationServiceGenerateOrganizationDomainValidationResponse interface.
 */
export function instanceOfOrganizationServiceGenerateOrganizationDomainValidationResponse(value: object): value is OrganizationServiceGenerateOrganizationDomainValidationResponse {
    return true;
}

export function OrganizationServiceGenerateOrganizationDomainValidationResponseFromJSON(json: any): OrganizationServiceGenerateOrganizationDomainValidationResponse {
    return OrganizationServiceGenerateOrganizationDomainValidationResponseFromJSONTyped(json, false);
}

export function OrganizationServiceGenerateOrganizationDomainValidationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationServiceGenerateOrganizationDomainValidationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OrganizationServiceGenerateOrganizationDomainValidationResponseToJSON(json: any): OrganizationServiceGenerateOrganizationDomainValidationResponse {
    return OrganizationServiceGenerateOrganizationDomainValidationResponseToJSONTyped(json, false);
}

export function OrganizationServiceGenerateOrganizationDomainValidationResponseToJSONTyped(value?: OrganizationServiceGenerateOrganizationDomainValidationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'url': value['url'],
    };
}

