/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HashedPassword1 } from './HashedPassword1.js';
import {
    instanceOfHashedPassword1,
    HashedPassword1FromJSON,
    HashedPassword1FromJSONTyped,
    HashedPassword1ToJSON,
} from './HashedPassword1.js';
import type { Password1 } from './Password1.js';
import {
    instanceOfPassword1,
    Password1FromJSON,
    Password1FromJSONTyped,
    Password1ToJSON,
} from './Password1.js';

/**
 * @type OrganizationServiceAddHumanUserRequest
 * 
 * @export
 */
export type OrganizationServiceAddHumanUserRequest = HashedPassword1 | Password1;

export function OrganizationServiceAddHumanUserRequestFromJSON(json: any): OrganizationServiceAddHumanUserRequest {
    return OrganizationServiceAddHumanUserRequestFromJSONTyped(json, false);
}

export function OrganizationServiceAddHumanUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationServiceAddHumanUserRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfHashedPassword1(json)) {
        return HashedPassword1FromJSONTyped(json, true);
    }
    if (instanceOfPassword1(json)) {
        return Password1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function OrganizationServiceAddHumanUserRequestToJSON(json: any): any {
    return OrganizationServiceAddHumanUserRequestToJSONTyped(json, false);
}

export function OrganizationServiceAddHumanUserRequestToJSONTyped(value?: OrganizationServiceAddHumanUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfHashedPassword1(value)) {
        return HashedPassword1ToJSON(value as HashedPassword1);
    }
    if (instanceOfPassword1(value)) {
        return Password1ToJSON(value as Password1);
    }

    return {};
}

