// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

import { OrganizationServiceDomainValidationType } from "./organization-service-domain-validation-type.js";
import { Expose } from "class-transformer";

export class OrganizationServiceDomain {
  /**
   * OrganizationID is the unique identifier of the organization the domain belongs to.
   * @example null
   */
  @Expose({ name: "organizationId" })
  organizationId?: string;
  /**
   * Domain is the fully qualified domain name.
   * @example null
   */
  @Expose({ name: "domain" })
  domain?: string;
  /**
   * IsVerified is a boolean flag indicating if the domain has been verified.
   * @example null
   */
  @Expose({ name: "isVerified" })
  isVerified?: boolean;
  /**
   * IsPrimary is a boolean flag indicating if the domain is the primary domain of the organization.
   * @example null
   */
  @Expose({ name: "isPrimary" })
  isPrimary?: boolean;
  /** @example null */
  @Expose({ name: "validationType" })
  validationType?: OrganizationServiceDomainValidationType;

  constructor(data?: Partial<OrganizationServiceDomain>) {
    Object.assign(this, data);
    if (
      this.organizationId != null &&
      typeof this.organizationId !== "string"
    ) {
      throw new TypeError(
        `organizationId must be a string, got ${typeof this.organizationId}`,
      );
    }
    if (this.domain != null && typeof this.domain !== "string") {
      throw new TypeError(`domain must be a string, got ${typeof this.domain}`);
    }
    if (this.isVerified != null && typeof this.isVerified !== "boolean") {
      throw new TypeError(
        `isVerified must be a boolean, got ${typeof this.isVerified}`,
      );
    }
    if (this.isPrimary != null && typeof this.isPrimary !== "boolean") {
      throw new TypeError(
        `isPrimary must be a boolean, got ${typeof this.isPrimary}`,
      );
    }
  }

  /**
   * Value-equality across all declared fields. Two instances are equal when
   * every field deep-equals the other's. Arrays, plain objects, Sets, Maps,
   * Buffers and Date values are compared structurally; nested model fields
   * fall through to their own {@link equals} when present, otherwise to a
   * recursive structural compare. Mirrors the value-equality exposed by the
   * other SDKs (node-model-equality).
   */
  equals(other: unknown): boolean {
    if (this === other) {
      return true;
    }
    if (!(other instanceof OrganizationServiceDomain)) {
      return false;
    }
    if (
      !OrganizationServiceDomain.__deepEquals(
        this.organizationId,
        (other as OrganizationServiceDomain).organizationId,
      )
    ) {
      return false;
    }
    if (
      !OrganizationServiceDomain.__deepEquals(
        this.domain,
        (other as OrganizationServiceDomain).domain,
      )
    ) {
      return false;
    }
    if (
      !OrganizationServiceDomain.__deepEquals(
        this.isVerified,
        (other as OrganizationServiceDomain).isVerified,
      )
    ) {
      return false;
    }
    if (
      !OrganizationServiceDomain.__deepEquals(
        this.isPrimary,
        (other as OrganizationServiceDomain).isPrimary,
      )
    ) {
      return false;
    }
    if (
      !OrganizationServiceDomain.__deepEquals(
        this.validationType,
        (other as OrganizationServiceDomain).validationType,
      )
    ) {
      return false;
    }
    return true;
  }

  /**
   * Recursive structural comparison used by {@link equals}. Defers to a
   * nested value's own `equals` method when it exposes one (generated
   * models do), so equality stays value-based all the way down.
   */
  private static __deepEquals(a: unknown, b: unknown): boolean {
    if (a === b) {
      return true;
    }
    if (a == null || b == null) {
      return a === b;
    }
    if (
      typeof (a as { equals?: unknown }).equals === "function" &&
      a.constructor === b.constructor
    ) {
      return (a as { equals(o: unknown): boolean }).equals(b);
    }
    if (Buffer.isBuffer(a) && Buffer.isBuffer(b)) {
      return a.equals(b);
    }
    if (a instanceof Date && b instanceof Date) {
      return a.getTime() === b.getTime();
    }
    if (Array.isArray(a) && Array.isArray(b)) {
      if (a.length !== b.length) {
        return false;
      }
      return a.every((v, i) => OrganizationServiceDomain.__deepEquals(v, b[i]));
    }
    if (a instanceof Set && b instanceof Set) {
      if (a.size !== b.size) {
        return false;
      }
      const bvals = [...b];
      return [...a].every((v) =>
        bvals.some((w) => OrganizationServiceDomain.__deepEquals(v, w)),
      );
    }
    if (a instanceof Map && b instanceof Map) {
      if (a.size !== b.size) {
        return false;
      }
      for (const [k, v] of a) {
        if (!b.has(k) || !OrganizationServiceDomain.__deepEquals(v, b.get(k))) {
          return false;
        }
      }
      return true;
    }
    if (typeof a === "object" && typeof b === "object") {
      const ar = a as Record<string, unknown>;
      const br = b as Record<string, unknown>;
      const ak = Object.keys(ar);
      const bk = Object.keys(br);
      if (ak.length !== bk.length) {
        return false;
      }
      return ak.every(
        (k) =>
          Object.prototype.hasOwnProperty.call(br, k) &&
          OrganizationServiceDomain.__deepEquals(ar[k], br[k]),
      );
    }
    return false;
  }
}
