/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganizationServicePassword
 */
export interface OrganizationServicePassword {
    /**
     * 
     * @type {string}
     * @memberof OrganizationServicePassword
     */
    password?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationServicePassword
     */
    changeRequired?: boolean;
}

/**
 * Check if a given object implements the OrganizationServicePassword interface.
 */
export function instanceOfOrganizationServicePassword(value: object): value is OrganizationServicePassword {
    return true;
}

export function OrganizationServicePasswordFromJSON(json: any): OrganizationServicePassword {
    return OrganizationServicePasswordFromJSONTyped(json, false);
}

export function OrganizationServicePasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationServicePassword {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
        'changeRequired': json['changeRequired'] == null ? undefined : json['changeRequired'],
    };
}

export function OrganizationServicePasswordToJSON(json: any): OrganizationServicePassword {
    return OrganizationServicePasswordToJSONTyped(json, false);
}

export function OrganizationServicePasswordToJSONTyped(value?: OrganizationServicePassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'changeRequired': value['changeRequired'],
    };
}

