/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { UserServicePhoneQuery } from './UserServicePhoneQuery.js';
import {
    UserServicePhoneQueryFromJSON,
    UserServicePhoneQueryFromJSONTyped,
    UserServicePhoneQueryToJSON,
    UserServicePhoneQueryToJSONTyped,
} from './UserServicePhoneQuery.js';

/**
 * 
 * @export
 * @interface PhoneQuery
 */
export interface PhoneQuery {
    /**
     * 
     * @type {UserServicePhoneQuery}
     * @memberof PhoneQuery
     */
    phoneQuery: UserServicePhoneQuery;
}

/**
 * Check if a given object implements the PhoneQuery interface.
 */
export function instanceOfPhoneQuery(value: object): value is PhoneQuery {
    if (!('phoneQuery' in value) || value['phoneQuery'] === undefined) return false;
    return true;
}

export function PhoneQueryFromJSON(json: any): PhoneQuery {
    return PhoneQueryFromJSONTyped(json, false);
}

export function PhoneQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhoneQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneQuery': UserServicePhoneQueryFromJSON(json['phoneQuery']),
    };
}

export function PhoneQueryToJSON(json: any): PhoneQuery {
    return PhoneQueryToJSONTyped(json, false);
}

export function PhoneQueryToJSONTyped(value?: PhoneQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phoneQuery': UserServicePhoneQueryToJSON(value['phoneQuery']),
    };
}

