/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProjectServiceActivateProjectRequest
 */
export interface ProjectServiceActivateProjectRequest {
    /**
     * ProjectID is the unique identifier of the project.
     * @type {string}
     * @memberof ProjectServiceActivateProjectRequest
     */
    projectId?: string;
}

/**
 * Check if a given object implements the ProjectServiceActivateProjectRequest interface.
 */
export function instanceOfProjectServiceActivateProjectRequest(value: object): value is ProjectServiceActivateProjectRequest {
    return true;
}

export function ProjectServiceActivateProjectRequestFromJSON(json: any): ProjectServiceActivateProjectRequest {
    return ProjectServiceActivateProjectRequestFromJSONTyped(json, false);
}

export function ProjectServiceActivateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectServiceActivateProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
    };
}

export function ProjectServiceActivateProjectRequestToJSON(json: any): ProjectServiceActivateProjectRequest {
    return ProjectServiceActivateProjectRequestToJSONTyped(json, false);
}

export function ProjectServiceActivateProjectRequestToJSONTyped(value?: ProjectServiceActivateProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
    };
}

