/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProjectServiceProjectGrantState = {
    ProjectGrantStateUnspecified: 'PROJECT_GRANT_STATE_UNSPECIFIED',
    ProjectGrantStateActive: 'PROJECT_GRANT_STATE_ACTIVE',
    ProjectGrantStateInactive: 'PROJECT_GRANT_STATE_INACTIVE',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ProjectServiceProjectGrantState = typeof ProjectServiceProjectGrantState[keyof typeof ProjectServiceProjectGrantState];


export function instanceOfProjectServiceProjectGrantState(value: any): boolean {
    for (const key in ProjectServiceProjectGrantState) {
        if (Object.prototype.hasOwnProperty.call(ProjectServiceProjectGrantState, key)) {
            if (ProjectServiceProjectGrantState[key as keyof typeof ProjectServiceProjectGrantState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProjectServiceProjectGrantStateFromJSON(json: any): ProjectServiceProjectGrantState {
    return ProjectServiceProjectGrantStateFromJSONTyped(json, false);
}

export function ProjectServiceProjectGrantStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectServiceProjectGrantState {
    return json as ProjectServiceProjectGrantState;
}

export function ProjectServiceProjectGrantStateToJSON(value?: ProjectServiceProjectGrantState | null): any {
    return value as any;
}

export function ProjectServiceProjectGrantStateToJSONTyped(value: any, ignoreDiscriminator: boolean): ProjectServiceProjectGrantState {
    return value as ProjectServiceProjectGrantState;
}

