/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RestAsync
 */
export interface RestAsync {
    /**
     * 
     * @type {object}
     * @memberof RestAsync
     */
    restAsync: object;
}

/**
 * Check if a given object implements the RestAsync interface.
 */
export function instanceOfRestAsync(value: object): value is RestAsync {
    if (!('restAsync' in value) || value['restAsync'] === undefined) return false;
    return true;
}

export function RestAsyncFromJSON(json: any): RestAsync {
    return RestAsyncFromJSONTyped(json, false);
}

export function RestAsyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestAsync {
    if (json == null) {
        return json;
    }
    return {
        
        'restAsync': json['restAsync'],
    };
}

export function RestAsyncToJSON(json: any): RestAsync {
    return RestAsyncToJSONTyped(json, false);
}

export function RestAsyncToJSONTyped(value?: RestAsync | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'restAsync': value['restAsync'],
    };
}

