/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ReturnCode
 */
export interface ReturnCode {
    /**
     * 
     * @type {object}
     * @memberof ReturnCode
     */
    returnCode: object;
}

/**
 * Check if a given object implements the ReturnCode interface.
 */
export function instanceOfReturnCode(value: object): value is ReturnCode {
    if (!('returnCode' in value) || value['returnCode'] === undefined) return false;
    return true;
}

export function ReturnCodeFromJSON(json: any): ReturnCode {
    return ReturnCodeFromJSONTyped(json, false);
}

export function ReturnCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnCode {
    if (json == null) {
        return json;
    }
    return {
        
        'returnCode': json['returnCode'],
    };
}

export function ReturnCodeToJSON(json: any): ReturnCode {
    return ReturnCodeToJSONTyped(json, false);
}

export function ReturnCodeToJSONTyped(value?: ReturnCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'returnCode': value['returnCode'],
    };
}

