/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BetaOrganizationServiceSendEmailVerificationCode } from './BetaOrganizationServiceSendEmailVerificationCode.js';
import {
    BetaOrganizationServiceSendEmailVerificationCodeFromJSON,
    BetaOrganizationServiceSendEmailVerificationCodeFromJSONTyped,
    BetaOrganizationServiceSendEmailVerificationCodeToJSON,
    BetaOrganizationServiceSendEmailVerificationCodeToJSONTyped,
} from './BetaOrganizationServiceSendEmailVerificationCode.js';

/**
 * 
 * @export
 * @interface SendCode9
 */
export interface SendCode9 {
    /**
     * 
     * @type {BetaOrganizationServiceSendEmailVerificationCode}
     * @memberof SendCode9
     */
    sendCode: BetaOrganizationServiceSendEmailVerificationCode;
}

/**
 * Check if a given object implements the SendCode9 interface.
 */
export function instanceOfSendCode9(value: object): value is SendCode9 {
    if (!('sendCode' in value) || value['sendCode'] === undefined) return false;
    return true;
}

export function SendCode9FromJSON(json: any): SendCode9 {
    return SendCode9FromJSONTyped(json, false);
}

export function SendCode9FromJSONTyped(json: any, ignoreDiscriminator: boolean): SendCode9 {
    if (json == null) {
        return json;
    }
    return {
        
        'sendCode': BetaOrganizationServiceSendEmailVerificationCodeFromJSON(json['sendCode']),
    };
}

export function SendCode9ToJSON(json: any): SendCode9 {
    return SendCode9ToJSONTyped(json, false);
}

export function SendCode9ToJSONTyped(value?: SendCode9 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sendCode': BetaOrganizationServiceSendEmailVerificationCodeToJSON(value['sendCode']),
    };
}

