/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SessionServiceHeaderValues } from './SessionServiceHeaderValues.js';
import {
    SessionServiceHeaderValuesFromJSON,
    SessionServiceHeaderValuesFromJSONTyped,
    SessionServiceHeaderValuesToJSON,
    SessionServiceHeaderValuesToJSONTyped,
} from './SessionServiceHeaderValues.js';

/**
 * 
 * @export
 * @interface SessionServiceUserAgent
 */
export interface SessionServiceUserAgent {
    /**
     * 
     * @type {string}
     * @memberof SessionServiceUserAgent
     */
    fingerprintId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SessionServiceUserAgent
     */
    ip?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SessionServiceUserAgent
     */
    description?: string | null;
    /**
     * 
     * @type {{ [key: string]: SessionServiceHeaderValues; }}
     * @memberof SessionServiceUserAgent
     */
    header?: { [key: string]: SessionServiceHeaderValues; };
}

/**
 * Check if a given object implements the SessionServiceUserAgent interface.
 */
export function instanceOfSessionServiceUserAgent(value: object): value is SessionServiceUserAgent {
    return true;
}

export function SessionServiceUserAgentFromJSON(json: any): SessionServiceUserAgent {
    return SessionServiceUserAgentFromJSONTyped(json, false);
}

export function SessionServiceUserAgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionServiceUserAgent {
    if (json == null) {
        return json;
    }
    return {
        
        'fingerprintId': json['fingerprintId'] == null ? undefined : json['fingerprintId'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'description': json['description'] == null ? undefined : json['description'],
        'header': json['header'] == null ? undefined : (mapValues(json['header'], SessionServiceHeaderValuesFromJSON)),
    };
}

export function SessionServiceUserAgentToJSON(json: any): SessionServiceUserAgent {
    return SessionServiceUserAgentToJSONTyped(json, false);
}

export function SessionServiceUserAgentToJSONTyped(value?: SessionServiceUserAgent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fingerprintId': value['fingerprintId'],
        'ip': value['ip'],
        'description': value['description'],
        'header': value['header'] == null ? undefined : (mapValues(value['header'], SessionServiceHeaderValuesToJSON)),
    };
}

