/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SessionServiceOTPFactor } from './session-service-otp-factor.js';
import {
    SessionServiceOTPFactorFromJSON,
    SessionServiceOTPFactorFromJSONTyped,
    SessionServiceOTPFactorToJSON,
    SessionServiceOTPFactorToJSONTyped,
} from './session-service-otp-factor.js';
import type { SessionServiceIntentFactor } from './session-service-intent-factor.js';
import {
    SessionServiceIntentFactorFromJSON,
    SessionServiceIntentFactorFromJSONTyped,
    SessionServiceIntentFactorToJSON,
    SessionServiceIntentFactorToJSONTyped,
} from './session-service-intent-factor.js';
import type { SessionServiceWebAuthNFactor } from './session-service-web-auth-n-factor.js';
import {
    SessionServiceWebAuthNFactorFromJSON,
    SessionServiceWebAuthNFactorFromJSONTyped,
    SessionServiceWebAuthNFactorToJSON,
    SessionServiceWebAuthNFactorToJSONTyped,
} from './session-service-web-auth-n-factor.js';
import type { SessionServiceUserFactor } from './session-service-user-factor.js';
import {
    SessionServiceUserFactorFromJSON,
    SessionServiceUserFactorFromJSONTyped,
    SessionServiceUserFactorToJSON,
    SessionServiceUserFactorToJSONTyped,
} from './session-service-user-factor.js';
import type { SessionServicePasswordFactor } from './session-service-password-factor.js';
import {
    SessionServicePasswordFactorFromJSON,
    SessionServicePasswordFactorFromJSONTyped,
    SessionServicePasswordFactorToJSON,
    SessionServicePasswordFactorToJSONTyped,
} from './session-service-password-factor.js';
import type { SessionServiceTOTPFactor } from './session-service-totp-factor.js';
import {
    SessionServiceTOTPFactorFromJSON,
    SessionServiceTOTPFactorFromJSONTyped,
    SessionServiceTOTPFactorToJSON,
    SessionServiceTOTPFactorToJSONTyped,
} from './session-service-totp-factor.js';

/**
 * 
 * @export
 * @interface SessionServiceFactors
 */
export interface SessionServiceFactors {
    /**
     * 
     * @type {SessionServiceUserFactor}
     * @memberof SessionServiceFactors
     */
    user?: SessionServiceUserFactor;
    /**
     * 
     * @type {SessionServicePasswordFactor}
     * @memberof SessionServiceFactors
     */
    password?: SessionServicePasswordFactor;
    /**
     * 
     * @type {SessionServiceWebAuthNFactor}
     * @memberof SessionServiceFactors
     */
    webAuthN?: SessionServiceWebAuthNFactor;
    /**
     * 
     * @type {SessionServiceIntentFactor}
     * @memberof SessionServiceFactors
     */
    intent?: SessionServiceIntentFactor;
    /**
     * 
     * @type {SessionServiceTOTPFactor}
     * @memberof SessionServiceFactors
     */
    totp?: SessionServiceTOTPFactor;
    /**
     * 
     * @type {SessionServiceOTPFactor}
     * @memberof SessionServiceFactors
     */
    otpSms?: SessionServiceOTPFactor;
    /**
     * 
     * @type {SessionServiceOTPFactor}
     * @memberof SessionServiceFactors
     */
    otpEmail?: SessionServiceOTPFactor;
}

/**
 * Check if a given object implements the SessionServiceFactors interface.
 */
export function instanceOfSessionServiceFactors(value: object): value is SessionServiceFactors {
    return true;
}

export function SessionServiceFactorsFromJSON(json: any): SessionServiceFactors {
    return SessionServiceFactorsFromJSONTyped(json, false);
}

export function SessionServiceFactorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionServiceFactors {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : SessionServiceUserFactorFromJSON(json['user']),
        'password': json['password'] == null ? undefined : SessionServicePasswordFactorFromJSON(json['password']),
        'webAuthN': json['webAuthN'] == null ? undefined : SessionServiceWebAuthNFactorFromJSON(json['webAuthN']),
        'intent': json['intent'] == null ? undefined : SessionServiceIntentFactorFromJSON(json['intent']),
        'totp': json['totp'] == null ? undefined : SessionServiceTOTPFactorFromJSON(json['totp']),
        'otpSms': json['otpSms'] == null ? undefined : SessionServiceOTPFactorFromJSON(json['otpSms']),
        'otpEmail': json['otpEmail'] == null ? undefined : SessionServiceOTPFactorFromJSON(json['otpEmail']),
    };
}

export function SessionServiceFactorsToJSON(json: any): SessionServiceFactors {
    return SessionServiceFactorsToJSONTyped(json, false);
}

export function SessionServiceFactorsToJSONTyped(value?: SessionServiceFactors | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': SessionServiceUserFactorToJSON(value['user']),
        'password': SessionServicePasswordFactorToJSON(value['password']),
        'webAuthN': SessionServiceWebAuthNFactorToJSON(value['webAuthN']),
        'intent': SessionServiceIntentFactorToJSON(value['intent']),
        'totp': SessionServiceTOTPFactorToJSON(value['totp']),
        'otpSms': SessionServiceOTPFactorToJSON(value['otpSms']),
        'otpEmail': SessionServiceOTPFactorToJSON(value['otpEmail']),
    };
}

