/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SessionServiceOTPFactor
 */
export interface SessionServiceOTPFactor {
    /**
     * "time when the One-Time Password was last checked"
     * @type {Date}
     * @memberof SessionServiceOTPFactor
     */
    verifiedAt?: Date;
}

/**
 * Check if a given object implements the SessionServiceOTPFactor interface.
 */
export function instanceOfSessionServiceOTPFactor(value: object): value is SessionServiceOTPFactor {
    return true;
}

export function SessionServiceOTPFactorFromJSON(json: any): SessionServiceOTPFactor {
    return SessionServiceOTPFactorFromJSONTyped(json, false);
}

export function SessionServiceOTPFactorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionServiceOTPFactor {
    if (json == null) {
        return json;
    }
    return {
        
        'verifiedAt': json['verifiedAt'] == null ? undefined : (new Date(json['verifiedAt'])),
    };
}

export function SessionServiceOTPFactorToJSON(json: any): SessionServiceOTPFactor {
    return SessionServiceOTPFactorToJSONTyped(json, false);
}

export function SessionServiceOTPFactorToJSONTyped(value?: SessionServiceOTPFactor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verifiedAt': value['verifiedAt'] == null ? undefined : ((value['verifiedAt']).toISOString()),
    };
}

