/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SessionServiceCheckTOTP
 */
export interface SessionServiceCheckTOTP {
    /**
     * 
     * @type {string}
     * @memberof SessionServiceCheckTOTP
     */
    code?: string;
}

/**
 * Check if a given object implements the SessionServiceCheckTOTP interface.
 */
export function instanceOfSessionServiceCheckTOTP(value: object): value is SessionServiceCheckTOTP {
    return true;
}

export function SessionServiceCheckTOTPFromJSON(json: any): SessionServiceCheckTOTP {
    return SessionServiceCheckTOTPFromJSONTyped(json, false);
}

export function SessionServiceCheckTOTPFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionServiceCheckTOTP {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function SessionServiceCheckTOTPToJSON(json: any): SessionServiceCheckTOTP {
    return SessionServiceCheckTOTPToJSONTyped(json, false);
}

export function SessionServiceCheckTOTPToJSONTyped(value?: SessionServiceCheckTOTP | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

