/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SettingsServiceSetHostedLoginTranslationResponse
 */
export interface SettingsServiceSetHostedLoginTranslationResponse {
    /**
     * hash of the saved translation. Valid only when ignore_inheritance = true
     * @type {string}
     * @memberof SettingsServiceSetHostedLoginTranslationResponse
     */
    etag?: string;
}

/**
 * Check if a given object implements the SettingsServiceSetHostedLoginTranslationResponse interface.
 */
export function instanceOfSettingsServiceSetHostedLoginTranslationResponse(value: object): value is SettingsServiceSetHostedLoginTranslationResponse {
    return true;
}

export function SettingsServiceSetHostedLoginTranslationResponseFromJSON(json: any): SettingsServiceSetHostedLoginTranslationResponse {
    return SettingsServiceSetHostedLoginTranslationResponseFromJSONTyped(json, false);
}

export function SettingsServiceSetHostedLoginTranslationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsServiceSetHostedLoginTranslationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'etag': json['etag'] == null ? undefined : json['etag'],
    };
}

export function SettingsServiceSetHostedLoginTranslationResponseToJSON(json: any): SettingsServiceSetHostedLoginTranslationResponse {
    return SettingsServiceSetHostedLoginTranslationResponseToJSONTyped(json, false);
}

export function SettingsServiceSetHostedLoginTranslationResponseToJSONTyped(value?: SettingsServiceSetHostedLoginTranslationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'etag': value['etag'],
    };
}

