/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SettingsServiceRequestContext } from './SettingsServiceRequestContext.js';
import {
    SettingsServiceRequestContextFromJSON,
    SettingsServiceRequestContextFromJSONTyped,
    SettingsServiceRequestContextToJSON,
    SettingsServiceRequestContextToJSONTyped,
} from './SettingsServiceRequestContext.js';

/**
 * 
 * @export
 * @interface SettingsServiceGetBrandingSettingsRequest
 */
export interface SettingsServiceGetBrandingSettingsRequest {
    /**
     * 
     * @type {SettingsServiceRequestContext}
     * @memberof SettingsServiceGetBrandingSettingsRequest
     */
    ctx?: SettingsServiceRequestContext;
}

/**
 * Check if a given object implements the SettingsServiceGetBrandingSettingsRequest interface.
 */
export function instanceOfSettingsServiceGetBrandingSettingsRequest(value: object): value is SettingsServiceGetBrandingSettingsRequest {
    return true;
}

export function SettingsServiceGetBrandingSettingsRequestFromJSON(json: any): SettingsServiceGetBrandingSettingsRequest {
    return SettingsServiceGetBrandingSettingsRequestFromJSONTyped(json, false);
}

export function SettingsServiceGetBrandingSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsServiceGetBrandingSettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ctx': json['ctx'] == null ? undefined : SettingsServiceRequestContextFromJSON(json['ctx']),
    };
}

export function SettingsServiceGetBrandingSettingsRequestToJSON(json: any): SettingsServiceGetBrandingSettingsRequest {
    return SettingsServiceGetBrandingSettingsRequestToJSONTyped(json, false);
}

export function SettingsServiceGetBrandingSettingsRequestToJSONTyped(value?: SettingsServiceGetBrandingSettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ctx': SettingsServiceRequestContextToJSON(value['ctx']),
    };
}

