/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SettingsServiceRequestContext } from './settings-service-request-context.js';
import {
    SettingsServiceRequestContextFromJSON,
    SettingsServiceRequestContextFromJSONTyped,
    SettingsServiceRequestContextToJSON,
    SettingsServiceRequestContextToJSONTyped,
} from './settings-service-request-context.js';

/**
 * 
 * @export
 * @interface SettingsServiceGetLoginSettingsRequest
 */
export interface SettingsServiceGetLoginSettingsRequest {
    /**
     * 
     * @type {SettingsServiceRequestContext}
     * @memberof SettingsServiceGetLoginSettingsRequest
     */
    ctx?: SettingsServiceRequestContext;
}

/**
 * Check if a given object implements the SettingsServiceGetLoginSettingsRequest interface.
 */
export function instanceOfSettingsServiceGetLoginSettingsRequest(value: object): value is SettingsServiceGetLoginSettingsRequest {
    return true;
}

export function SettingsServiceGetLoginSettingsRequestFromJSON(json: any): SettingsServiceGetLoginSettingsRequest {
    return SettingsServiceGetLoginSettingsRequestFromJSONTyped(json, false);
}

export function SettingsServiceGetLoginSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsServiceGetLoginSettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ctx': json['ctx'] == null ? undefined : SettingsServiceRequestContextFromJSON(json['ctx']),
    };
}

export function SettingsServiceGetLoginSettingsRequestToJSON(json: any): SettingsServiceGetLoginSettingsRequest {
    return SettingsServiceGetLoginSettingsRequestToJSONTyped(json, false);
}

export function SettingsServiceGetLoginSettingsRequestToJSONTyped(value?: SettingsServiceGetLoginSettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ctx': SettingsServiceRequestContextToJSON(value['ctx']),
    };
}

