/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { UserServiceAuthFactorU2F } from './UserServiceAuthFactorU2F.js';
import {
    UserServiceAuthFactorU2FFromJSON,
    UserServiceAuthFactorU2FFromJSONTyped,
    UserServiceAuthFactorU2FToJSON,
    UserServiceAuthFactorU2FToJSONTyped,
} from './UserServiceAuthFactorU2F.js';

/**
 * 
 * @export
 * @interface U2f
 */
export interface U2f {
    /**
     * 
     * @type {UserServiceAuthFactorU2F}
     * @memberof U2f
     */
    u2f: UserServiceAuthFactorU2F;
}

/**
 * Check if a given object implements the U2f interface.
 */
export function instanceOfU2f(value: object): value is U2f {
    if (!('u2f' in value) || value['u2f'] === undefined) return false;
    return true;
}

export function U2fFromJSON(json: any): U2f {
    return U2fFromJSONTyped(json, false);
}

export function U2fFromJSONTyped(json: any, ignoreDiscriminator: boolean): U2f {
    if (json == null) {
        return json;
    }
    return {
        
        'u2f': UserServiceAuthFactorU2FFromJSON(json['u2f']),
    };
}

export function U2fToJSON(json: any): U2f {
    return U2fToJSONTyped(json, false);
}

export function U2fToJSONTyped(value?: U2f | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'u2f': UserServiceAuthFactorU2FToJSON(value['u2f']),
    };
}

