/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UserServicePaginationResponse
 */
export interface UserServicePaginationResponse {
    /**
     * Absolute number of objects matching the query, regardless of applied limit.
     * @type {any}
     * @memberof UserServicePaginationResponse
     */
    totalResult?: any | null;
    /**
     * Applied limit from query, defines maximum amount of objects per request, to compare if all objects are returned.
     * @type {any}
     * @memberof UserServicePaginationResponse
     */
    appliedLimit?: any | null;
}

/**
 * Check if a given object implements the UserServicePaginationResponse interface.
 */
export function instanceOfUserServicePaginationResponse(value: object): value is UserServicePaginationResponse {
    return true;
}

export function UserServicePaginationResponseFromJSON(json: any): UserServicePaginationResponse {
    return UserServicePaginationResponseFromJSONTyped(json, false);
}

export function UserServicePaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserServicePaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalResult': json['totalResult'] == null ? undefined : json['totalResult'],
        'appliedLimit': json['appliedLimit'] == null ? undefined : json['appliedLimit'],
    };
}

export function UserServicePaginationResponseToJSON(json: any): UserServicePaginationResponse {
    return UserServicePaginationResponseToJSONTyped(json, false);
}

export function UserServicePaginationResponseToJSONTyped(value?: UserServicePaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalResult': value['totalResult'],
        'appliedLimit': value['appliedLimit'],
    };
}

