/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UserServiceRemoveSecretRequest
 */
export interface UserServiceRemoveSecretRequest {
    /**
     * The users resource ID.
     * @type {string}
     * @memberof UserServiceRemoveSecretRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the UserServiceRemoveSecretRequest interface.
 */
export function instanceOfUserServiceRemoveSecretRequest(value: object): value is UserServiceRemoveSecretRequest {
    return true;
}

export function UserServiceRemoveSecretRequestFromJSON(json: any): UserServiceRemoveSecretRequest {
    return UserServiceRemoveSecretRequestFromJSONTyped(json, false);
}

export function UserServiceRemoveSecretRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserServiceRemoveSecretRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function UserServiceRemoveSecretRequestToJSON(json: any): UserServiceRemoveSecretRequest {
    return UserServiceRemoveSecretRequestToJSONTyped(json, false);
}

export function UserServiceRemoveSecretRequestToJSONTyped(value?: UserServiceRemoveSecretRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

