/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UserServiceSendInviteCode
 */
export interface UserServiceSendInviteCode {
    /**
     * Optionally set a url_template, which will be used in the invite mail sent by ZITADEL to guide the user to your invitation page.
     * If no template is set, the default ZITADEL url will be used.
     * 
     * The following placeholders can be used: UserID, OrgID, Code
     * @type {string}
     * @memberof UserServiceSendInviteCode
     */
    urlTemplate?: string;
    /**
     * Optionally set an application name, which will be used in the invite mail sent by ZITADEL.
     * If no application name is set, ZITADEL will be used as default.
     * @type {string}
     * @memberof UserServiceSendInviteCode
     */
    applicationName?: string;
}

/**
 * Check if a given object implements the UserServiceSendInviteCode interface.
 */
export function instanceOfUserServiceSendInviteCode(value: object): value is UserServiceSendInviteCode {
    return true;
}

export function UserServiceSendInviteCodeFromJSON(json: any): UserServiceSendInviteCode {
    return UserServiceSendInviteCodeFromJSONTyped(json, false);
}

export function UserServiceSendInviteCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserServiceSendInviteCode {
    if (json == null) {
        return json;
    }
    return {
        
        'urlTemplate': json['urlTemplate'] == null ? undefined : json['urlTemplate'],
        'applicationName': json['applicationName'] == null ? undefined : json['applicationName'],
    };
}

export function UserServiceSendInviteCodeToJSON(json: any): UserServiceSendInviteCode {
    return UserServiceSendInviteCodeToJSONTyped(json, false);
}

export function UserServiceSendInviteCodeToJSONTyped(value?: UserServiceSendInviteCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'urlTemplate': value['urlTemplate'],
        'applicationName': value['applicationName'],
    };
}

