/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { UserServiceDetails } from './UserServiceDetails.js';
import {
    UserServiceDetailsFromJSON,
    UserServiceDetailsFromJSONTyped,
    UserServiceDetailsToJSON,
    UserServiceDetailsToJSONTyped,
} from './UserServiceDetails.js';

/**
 * 
 * @export
 * @interface UserServiceUpdateHumanUserResponse
 */
export interface UserServiceUpdateHumanUserResponse {
    /**
     * 
     * @type {UserServiceDetails}
     * @memberof UserServiceUpdateHumanUserResponse
     */
    details?: UserServiceDetails;
    /**
     * 
     * @type {string}
     * @memberof UserServiceUpdateHumanUserResponse
     */
    emailCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserServiceUpdateHumanUserResponse
     */
    phoneCode?: string | null;
}

/**
 * Check if a given object implements the UserServiceUpdateHumanUserResponse interface.
 */
export function instanceOfUserServiceUpdateHumanUserResponse(value: object): value is UserServiceUpdateHumanUserResponse {
    return true;
}

export function UserServiceUpdateHumanUserResponseFromJSON(json: any): UserServiceUpdateHumanUserResponse {
    return UserServiceUpdateHumanUserResponseFromJSONTyped(json, false);
}

export function UserServiceUpdateHumanUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserServiceUpdateHumanUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'details': json['details'] == null ? undefined : UserServiceDetailsFromJSON(json['details']),
        'emailCode': json['emailCode'] == null ? undefined : json['emailCode'],
        'phoneCode': json['phoneCode'] == null ? undefined : json['phoneCode'],
    };
}

export function UserServiceUpdateHumanUserResponseToJSON(json: any): UserServiceUpdateHumanUserResponse {
    return UserServiceUpdateHumanUserResponseToJSONTyped(json, false);
}

export function UserServiceUpdateHumanUserResponseToJSONTyped(value?: UserServiceUpdateHumanUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': UserServiceDetailsToJSON(value['details']),
        'emailCode': value['emailCode'],
        'phoneCode': value['phoneCode'],
    };
}

