/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UserServiceIDPSAMLAccessInformation
 */
export interface UserServiceIDPSAMLAccessInformation {
    /**
     * 
     * @type {string}
     * @memberof UserServiceIDPSAMLAccessInformation
     */
    assertion?: string;
}

/**
 * Check if a given object implements the UserServiceIDPSAMLAccessInformation interface.
 */
export function instanceOfUserServiceIDPSAMLAccessInformation(value: object): value is UserServiceIDPSAMLAccessInformation {
    return true;
}

export function UserServiceIDPSAMLAccessInformationFromJSON(json: any): UserServiceIDPSAMLAccessInformation {
    return UserServiceIDPSAMLAccessInformationFromJSONTyped(json, false);
}

export function UserServiceIDPSAMLAccessInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserServiceIDPSAMLAccessInformation {
    if (json == null) {
        return json;
    }
    return {
        
        'assertion': json['assertion'] == null ? undefined : json['assertion'],
    };
}

export function UserServiceIDPSAMLAccessInformationToJSON(json: any): UserServiceIDPSAMLAccessInformation {
    return UserServiceIDPSAMLAccessInformationToJSONTyped(json, false);
}

export function UserServiceIDPSAMLAccessInformationToJSONTyped(value?: UserServiceIDPSAMLAccessInformation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assertion': value['assertion'],
    };
}

