/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ReturnCode5 } from './ReturnCode5.js';
import {
    instanceOfReturnCode5,
    ReturnCode5FromJSON,
    ReturnCode5FromJSONTyped,
    ReturnCode5ToJSON,
} from './ReturnCode5.js';
import type { SendLink1 } from './SendLink1.js';
import {
    instanceOfSendLink1,
    SendLink1FromJSON,
    SendLink1FromJSONTyped,
    SendLink1ToJSON,
} from './SendLink1.js';

/**
 * @type UserServicePasswordResetRequest
 * 
 * @export
 */
export type UserServicePasswordResetRequest = ReturnCode5 | SendLink1;

export function UserServicePasswordResetRequestFromJSON(json: any): UserServicePasswordResetRequest {
    return UserServicePasswordResetRequestFromJSONTyped(json, false);
}

export function UserServicePasswordResetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserServicePasswordResetRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfReturnCode5(json)) {
        return ReturnCode5FromJSONTyped(json, true);
    }
    if (instanceOfSendLink1(json)) {
        return SendLink1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function UserServicePasswordResetRequestToJSON(json: any): any {
    return UserServicePasswordResetRequestToJSONTyped(json, false);
}

export function UserServicePasswordResetRequestToJSONTyped(value?: UserServicePasswordResetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfReturnCode5(value)) {
        return ReturnCode5ToJSON(value as ReturnCode5);
    }
    if (instanceOfSendLink1(value)) {
        return SendLink1ToJSON(value as SendLink1);
    }

    return {};
}

