/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { UserServicePasskey } from './UserServicePasskey.js';
import {
    UserServicePasskeyFromJSON,
    UserServicePasskeyFromJSONTyped,
    UserServicePasskeyToJSON,
    UserServicePasskeyToJSONTyped,
} from './UserServicePasskey.js';
import type { UserServiceListDetails } from './UserServiceListDetails.js';
import {
    UserServiceListDetailsFromJSON,
    UserServiceListDetailsFromJSONTyped,
    UserServiceListDetailsToJSON,
    UserServiceListDetailsToJSONTyped,
} from './UserServiceListDetails.js';

/**
 * 
 * @export
 * @interface UserServiceListPasskeysResponse
 */
export interface UserServiceListPasskeysResponse {
    /**
     * 
     * @type {UserServiceListDetails}
     * @memberof UserServiceListPasskeysResponse
     */
    details?: UserServiceListDetails;
    /**
     * 
     * @type {Array<UserServicePasskey>}
     * @memberof UserServiceListPasskeysResponse
     */
    result?: Array<UserServicePasskey>;
}

/**
 * Check if a given object implements the UserServiceListPasskeysResponse interface.
 */
export function instanceOfUserServiceListPasskeysResponse(value: object): value is UserServiceListPasskeysResponse {
    return true;
}

export function UserServiceListPasskeysResponseFromJSON(json: any): UserServiceListPasskeysResponse {
    return UserServiceListPasskeysResponseFromJSONTyped(json, false);
}

export function UserServiceListPasskeysResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserServiceListPasskeysResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'details': json['details'] == null ? undefined : UserServiceListDetailsFromJSON(json['details']),
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(UserServicePasskeyFromJSON)),
    };
}

export function UserServiceListPasskeysResponseToJSON(json: any): UserServiceListPasskeysResponse {
    return UserServiceListPasskeysResponseToJSONTyped(json, false);
}

export function UserServiceListPasskeysResponseToJSONTyped(value?: UserServiceListPasskeysResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': UserServiceListDetailsToJSON(value['details']),
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(UserServicePasskeyToJSON)),
    };
}

