/* tslint:disable */
/* eslint-disable */
/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UserServiceHumanPhone
 */
export interface UserServiceHumanPhone {
    /**
     * 
     * @type {string}
     * @memberof UserServiceHumanPhone
     */
    phone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserServiceHumanPhone
     */
    isVerified?: boolean;
}

/**
 * Check if a given object implements the UserServiceHumanPhone interface.
 */
export function instanceOfUserServiceHumanPhone(value: object): value is UserServiceHumanPhone {
    return true;
}

export function UserServiceHumanPhoneFromJSON(json: any): UserServiceHumanPhone {
    return UserServiceHumanPhoneFromJSONTyped(json, false);
}

export function UserServiceHumanPhoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserServiceHumanPhone {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'] == null ? undefined : json['phone'],
        'isVerified': json['isVerified'] == null ? undefined : json['isVerified'],
    };
}

export function UserServiceHumanPhoneToJSON(json: any): UserServiceHumanPhone {
    return UserServiceHumanPhoneToJSONTyped(json, false);
}

export function UserServiceHumanPhoneToJSONTyped(value?: UserServiceHumanPhone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
        'isVerified': value['isVerified'],
    };
}

