// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

import { ObjectSerializer } from "./object-serializer.js";
import { ZitadelError } from "./errors/zitadel-error.js";

/**
 * Base error class for all API (transport-level) errors. Extends the branded
 * {@link ZitadelError} root so every error this SDK throws shares a common
 * `instanceof ZitadelError` ancestor.
 */
export class ApiError<T = unknown> extends ZitadelError {
  /** HTTP status code. */
  public readonly statusCode: number;

  /** Raw response body string, or null when the transport produced no body. */
  public readonly responseBody: string | null;

  /**
   * Response headers, or null when the transport produced no headers (e.g.
   * a send-phase failure before any response was received). Null is
   * distinct from an empty header map, matching the nullable-majority SDKs
   * (apierror-responsebody-headers-nullable-split).
   */
  public readonly responseHeaders: Record<string, string> | null;

  /** Deserialized error body, if available. */
  public readonly errorBody: T | null;

  constructor(
    statusCode: number,
    message: string,
    responseHeaders: Record<string, string> | null = null,
    responseBody: string | null = null,
    errorBody: T | null = null,
    options?: { cause?: unknown },
  ) {
    /* ES2022 cause option preserves the underlying network/IO error so
     * callers can drill down via `err.cause` instead of losing the
     * original stack trace. */
    super(message, options);
    this.name = "ApiError";
    this.statusCode = statusCode;
    this.responseHeaders = responseHeaders;
    this.responseBody = responseBody;
    this.errorBody = errorBody;
  }

  /**
   * Deserialize the raw response body into an instance of the given class.
   *
   * Useful when the API returns a structured error body that you want to
   * access in a strongly-typed way.
   *
   * @param clazz the model class constructor to deserialize into (pass the
   *   generated model class directly, e.g. `getTypedErrorBody(MyError)`)
   * @returns the deserialized error body
   */
  getTypedErrorBody<U>(clazz: new (...args: unknown[]) => U): U | null {
    /* F5: depth-cap JSON parsing for parity with Go/Java/Python (the body
     * may be attacker-controlled). */
    const json =
      this.responseBody != null
        ? ObjectSerializer.parseJson(this.responseBody)
        : null;
    return ObjectSerializer.deserialize(json, clazz);
  }
}
