// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

/* eslint-disable */

/**
 * Recursive "plain data" view of a generated model.
 *
 * Generated models are emitted as classes (they carry value-equality and
 * deserialisation helpers such as `equals`). Request bodies, however, are
 * routinely supplied as plain object literals — the runtime constructor and
 * the class-transformer pipeline accept that shape and rebuild real
 * instances. A bare `Model` type would force callers to instantiate every
 * nested class just to satisfy the structural type checker, so request
 * parameters are typed with `DeepInput<Model>` instead.
 *
 * `DeepInput<T>`:
 * <ul>
 *   <li>passes primitives through unchanged;</li>
 *   <li>maps arrays element-wise;</li>
 *   <li>for objects, drops method-valued members (e.g. `equals`) and makes
 *       every remaining property optional and recursively plain.</li>
 * </ul>
 *
 * A genuine model instance is still assignable to `DeepInput<Model>`, so
 * callers may pass either a plain literal or a constructed instance.
 */
export type Primitive =
  | string
  | number
  | boolean
  | bigint
  | symbol
  | null
  | undefined;

/**
 * Leaf value types that are objects at the type level but are accepted in
 * their serialised (wire) form on input. Temporal values and Dates round-trip
 * as ISO strings; Buffers as base64 strings (or the Buffer itself). These are
 * passed through verbatim — never structurally mapped — and additionally
 * accept their string input form.
 */
type InputLeaf =
  | Date
  | Buffer
  | {
      readonly toString: () => string;
      readonly [Symbol.toPrimitive]?: unknown;
    };

export type DeepInput<T> = T extends Primitive
  ? T
  : [T] extends [Date]
    ? Date | string
    : [T] extends [Buffer]
      ? Buffer | string
      : T extends
            | { readonly nanoseconds: number }
            | { readonly nanosecond: number }
        ? T | string
        : T extends Array<infer U>
          ? Array<DeepInput<U>>
          : T extends object
            ? {
                [K in keyof T as T[K] extends (...args: never[]) => unknown
                  ? never
                  : K]?: DeepInput<T[K]>;
              }
            : T;
