// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

/**
 * Utility for injecting W3C Trace Context headers (traceparent, tracestate)
 * into outgoing API requests when OpenTelemetry is available.
 *
 * If the @opentelemetry/api package is not installed, this function silently no-ops.
 */

/**
 * Inject the current OpenTelemetry trace context into the given headers object.
 *
 * @param headers - mutable record of request headers
 */
export async function injectTraceContext(
  headers: Record<string, string>,
): Promise<void> {
  try {
    /*
     * Static specifier (not a variable) so no-unsanitized/method is satisfied;
     * the import is still optional at runtime via the surrounding try/catch.
     */
    const otel = await (import("@opentelemetry/api") as Promise<{
      propagation: { inject: (ctx: unknown, carrier: unknown) => void };
      context: { active: () => unknown };
    }>);
    otel.propagation.inject(otel.context.active(), headers);
  } catch {
    /* empty */
  }
}
