name: Docker

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      image-name:
        type: string
        default: 'temp'

permissions:
  contents: read

jobs:
  Build-Container:
    runs-on: ubuntu-latest
    name: Build Container

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ inputs.image-name }}:${{ github.sha }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
