name: Compatibility

on:
  workflow_call:
    inputs:
      library_ref:
        required: true
        type: string
      sanity_ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  check-compatibility:
    name: With Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20', '21', '23', '24']
      fail-fast: false

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ inputs.library_ref }}
          path: project/library

      - name: Checkout sanity stub
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ inputs.sanity_ref }}
          path: project/sanity

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Library
        working-directory: project/library
        run: |
          npm ci
          npm run build

      - name: Check Installability
        working-directory: project/sanity
        run: npm install ../library
