name: Compatibility

on:
  workflow_call:
    inputs:
      library_ref:
        required: true
        type: string
      sanity_ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  check-compatibility:
    name: With Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['21', '22', '23', '24']
      fail-fast: false

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.library_ref }}
          path: project/library

      - name: Checkout sanity stub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.sanity_ref }}
          path: project/sanity

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Library
        working-directory: project/library
        run: |
          npm ci
          npm run build

      - name: Check Installability
        working-directory: project/sanity
        run: npm install ../library
