name: Release

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write
  packages: write
  id-token: write
  checks: read

defaults:
  run:
    working-directory: ./

jobs:
  publish-package:
    runs-on: ubuntu-latest
    name: To Artifactory

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@b9b25d45f70a5d94d88496aa4896bf9ed8f49b67 # v4.4.0
        with:
          node-version: 'lts/*'

      - name: Run semantic-release
        uses: mridang/action-semantic-release@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-force-install: 'true'
        env:
          DOCKER_REGISTRY_USER: ${{ github.actor }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
