name: Release

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write
  packages: write
  id-token: write
  checks: read

defaults:
  run:
    working-directory: ./

jobs:
  publish-package:
    runs-on: ubuntu-latest
    name: To Artifactory

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 'lts/*'

      - name: Run semantic-release
        uses: mridang/action-semantic-release@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-force-install: 'true'
        env:
          DOCKER_REGISTRY_USER: ${{ github.actor }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
